# Stress Spaces {#propspaces}

intro 

Much of this chapter is a modified, and in some places expanded, version of @deleeuw_E_16l.

## Configuration Space {#propconfspace}

So far we have defined stress on $\mathbb{R}^{n\times p}$, the space of all matrices with $n$ rows and $p$ columns. We call this *configuration space*.

Even for $n$ as small as four and $p$ as small as two the dimension of
the space of centered configurations is six, and there is no natural way
to visualize a function of six variables. 

centered matrices $\mathbb{R}_C^{n\times p}$  $p(n-1)$

lower triangular matrices $\mathbb{R}_T^{n\times p}$ $\sum_{s=1}^p (n-s)=np-\frac12 p(p+1)$

orthogonal matrices $\mathbb{R}_O^{n\times p}$ $\sum_{s=1}^p (n-s)=np-\frac12 p(p+1)$

using coordinates (as in CCD)

## Coefficient Space {#propcoefspace}

### On the Planes

What we can do is plot stress
on two-dimensional subspaces, either as a contour plot or as a perspective plot. Our two-dimensional subspaces are of the form $\alpha X+\beta Y$, where $X$ and $Y$ are fixed configurations. 

### General

Suppose $Y_1,\cdots,Y_r$ are $r$ linearly independent column-centered matrices 
in configuration space $\mathbb{R}^{n\times p}$. We write $\mathcal{Y}$ for the $r$-dimensional subspace spanned by the $Y_s$.

If $X\in\mathcal{Y}$ then there is a $\theta$ in coefficient space $\mathbb{R}^r$ such that $X=\sum_{s=1}^r\theta_s Y_s$. Define

$$
\tilde d_{ij}^2(\theta):=\text{tr}\ X'A_{ij}X=\theta'\tilde{A}_{ij}\theta,
$$
with 
$$
\{\tilde A_{ij}\}_{st}:=\text{tr}\ Y_s'A_{ij}Y_t.
$$
Now
$$
\tilde B(\theta):=\mathop{\sum\sum}_{1\leq i<j\leq n}w_{ij}\frac{\delta_{ij}}{\tilde d_{ij}(\theta)}\tilde A_{ij},
$$

$$
\tilde V:=\mathop{\sum\sum}_{1\leq i<j\leq n}w_{ij}\tilde A_{ij},
$$

and

$$
\tilde\sigma(\theta):=1-2\tilde\rho(\theta)+\tilde\eta^2(\theta)=1-2\ \theta'\tilde B(\theta)\theta+\theta'\tilde V\theta
$$
For the elements of $\tilde B$ and $\tilde V$ we see

\begin{align}
\tilde b_{st}(\theta)&=\text{tr}\ Y_s'B(X)Y_t,\\
\tilde v_{st}&=\text{tr}\ Y_s'VY_t.
\end{align}

Minimizing $\sigma$ over $X\in\mathcal{Y}$ is now equivalent to minimizing 
$\tilde\sigma$ over $\theta\in\mathbb{R}^r$.

The gradient in configuration space for all $X\in\mathbb{R}^{n\times p}$ is
$$
\frac12\nabla\sigma(X)=(V-B(X))X.
$$
$$
\frac12\nabla\tilde\sigma(\theta)=(\tilde V\theta-\tilde B(\theta)\theta)
$$
$$
\frac12\{\nabla\tilde\sigma(\theta)\}_s=\text{tr}\ Y_s'(VX-B(X)X)=\text{tr}\ Y_s'\nabla\sigma(X),
$$
with $X=\sum_{s=1}^r\theta_sY_s$.

Thus $\nabla\tilde\sigma(\theta)=0$ if and only if $\nabla\sigma(X)\in\mathcal{Y}_\perp$, the subspace of $\mathbb{R}^{n\times p}$ orthogonal to $\mathcal{Y}$. Specifically $\nabla\sigma(X)=0$ implies
$\nabla\tilde\sigma(\theta)=0$. If the 
$Y_s$ span all of $\mathbb{R}^{n\times p}$ then $\nabla\tilde\sigma(\theta)=0$
if and only if $\nabla\sigma(X)=0$.

For the relationship between the minimization problems in coefficient space and
configuration space  we also study the relationship
between the two Hessians.

For all $X$ and $Z$ in configuration space
$$
\frac12\nabla^2\sigma(X)(Z,Z)=\text{tr}\ Z'VZ-\mathop{\sum\sum}_{1\leq i<j\leq n}w_{ij}\frac{\delta_{ij}}{d_{ij}(X)}\left\{\text{tr}\ Z'A_{ij}Z-\frac{\{\text{tr}\ Z'A_{ij}Y\}^2}{d_{ij}^2(X)}\right\}
$$

For any $\theta$ in coefficient space
$$
\frac12\nabla^2\tilde\sigma(\theta)=\tilde V-\mathop{\sum\sum}_{1\leq i<j\leq n}w_{ij}\frac{\delta_{ij}}{d_{ij}(\theta)}\left\{\tilde A_{ij}-\frac{\tilde A_{ij}\theta\theta'\tilde A_{ij}}{d_{ij}^2(\theta)}\right\}
$$
and thus 

$$
\xi'\nabla^2\tilde\sigma(\theta)\xi=\nabla^2\sigma(X)(Z,Z).
$$
where $Z:=\sum_{s=1}^r\xi_s Y_s$ and $X:=\sum_{s=1}^r\theta_s Y_s$. 


Thus if $\theta$ is a local minimum in coefficient space then $\nabla^2\sigma(X)$ is positive semi-definite on
the subspace $\mathcal{Y}$. If $X\in\mathcal{Y}$ but $Z\not\in\mathcal{Y}$ it is perfectly possible that
$\nabla^2\sigma(X)(Z,Z)<0$, and thus $X$ can be a saddle point in 
configuration space. If $X\in\mathcal{Y}$ is a local minimum in
configuration space, then $\theta$ is a local minimum in coefficient
space. Of course if $\mathcal{Y}$ is the whole space then $\theta$
is a local minimum in coefficient space if and only if $X$ is a local minimum
in configuration space.

\begin{multline}
\sigma(X(\theta+\epsilon\xi))=\sigma(X(\theta)+\epsilon\mathcal{D}X(\theta)(\xi)+\frac12\epsilon^2\mathcal{D}^2X(\theta)(\xi,\xi))=\\
\sigma(X(\theta))+\epsilon\mathcal{D}\sigma(X(\theta))\mathcal{D}X(\theta)\xi+\frac12\epsilon^2\{\mathcal{D}\sigma(X(\theta))\mathcal{D}^2X(\theta)(\xi,\xi)+\mathcal{D}\sigma(X(\theta))\mathcal{D}\sigma(X(\theta))\}
\end{multline}

$$
\{\mathcal{D}^2X(\theta)(\xi,\xi)\}_{ip}=\sum\sum\xi_s\xi_t\mathcal{D}_{st}x_{ip}(\theta)=\xi'H_{ip}(\theta)\xi
$$
$$
\{\mathcal{D}X(\theta)(\xi)\}_{ip}=\sum\xi_s\mathcal{D}_sx_{ip}(\theta)=G_{ip}(\theta)\xi
$$

$$
\mathcal{D}\sigma(X(\theta))=\{V-B(X(\theta))\}X(\theta)=F(\theta)
$$

$$
\mathcal{D}\sigma(\theta)=\mathcal{D}\sigma(X(\theta))\mathcal{D}X(\theta)
$$

$\sigma(x_{11}(\theta),\cdots,x_{np}(\theta))$

$$
\mathcal{D}_s\sigma(\theta)=\sum_{i=1}^n\sum_{s=1}^p\mathcal{D}_{ip}\sigma(X(\theta))\mathcal{D}_sx_{ip}(\theta)
$$

$$
\mathcal{D}_{st}\sigma(\theta)=\sum_{i=1}^n\sum_{s=1}^p
\sum_{j=1}^n\sum_{r=1}^p\mathcal{D}_{is,jr}\sigma(X(\theta))\mathcal{D}_sx_{is}(\theta)\mathcal{D}_tx_{jr}(\theta)
+\sum_{i=1}^n\sum_{s=1}^p\mathcal{D}_{is}\sigma(X(\theta))\mathcal{D}_{st}x_{is}(\theta)
$$
Now let $Y_1,Y_2,\cdots,Y_r$ be linearly independent configurations in $\mathbb{R}^{n\times p}$, and consider minimizing stress over all linear combinations $X$ of the form $X=\sum_{s=1}^r \theta_sY_s$.

Each linear combination can be identified with a unique vector $\theta\in\mathbb{R}^r$, the coefficients of the linear combination. Thus we can also formulate our problem as minimizing stress over *coefficient space*, which is simply $\mathbb{R}^r$. We write $d_{ij}(\theta)$ for $d_{ij}(X)$ and 
$\sigma(\theta)$ for $\sigma(X)$. Note that 
$d_{ij}(\theta)=\sqrt{\theta'C_{ij}\theta}$, where
$C_{ij}$ has elements $\{C_{ij}\}_{st}:=\text{tr}\ Y_s'A_{ij}Y_t$.

If the $Y_t$ are actually a basis for configuration space (i.e. if $r=np$) then minimizing over configuration space and coordinate space is the same thing. For the $Y_t$ we could choose all rank one matrices, for example, of the form $a_i^{\ }b_s'$ where the $a_i$ are a basis for $\mathbb{R}^n$ and the $b_s$ are a basis for $\mathbb{R}^p$. And, in particular, the $a_i$ and $b_s$ can be chosen as unit vectors of length $n$ and $p$, respectively. That case we have $C_{ij}=I_p\otimes A_{ij}$, i.e. the direct sum of $p$ copies of $A_{ij}$. Also if $\theta=\text{vec}(X)$ then $d_{ij}(X)=\sqrt{\theta'(I_p\otimes A_{ij})\theta}$

If $r<np$ then coefficient space defines a proper subspace of configuration space. If it happens to be the $(n -1)p$ dimensional subspace of all column-centered matrices, then the two approaches still define the same minimization problem. But in general $r<(n-1)p$ with the $Y_s$ column-centered defines a *constrained MDS problem*, which we analyze in more detail in chapter \@ref(cmds).

Coefficient space is also a convenient place to deal with rotational indeterminacy in basic MDS. It follows from QR decomposition that any configuration matrix can be rotated in such a way that it upper diagonal elements (the $x_{ij}$ with $i<j$) are zero (define $X_p$ to be the first $p$ rows of $X$, compute $X_p'=QR$ with $Q$ square orthonormal and $R$ upper triangular, thus $X_p=R'Q'$ and $X_pQ=R'$, which is
lower triangular). The column-centered upper triangular configurations are a subspace of dimension $p(n-1)-p(p-1)/2$, and we can choose the $Y_s$ as a basis for this subspace. In this way we eliminate rotational indeterminacy in a relatively inexpensive way.

If $X=\sum_{s=1}^r \theta_sY_s$ then we define the symmetric positive definite matrix $B(\theta)$ of order $r$ with elements

\begin{equation}
b_{st}(\theta):=\text{tr}\ Y_s'B(X)Y_t,
(\#eq:propcoefb)
\end{equation}

where $B(X)$ is the usual B-matrix of order $n$ in configuration space, defined in equation \@ref(eq:bdef). Also define $V$ of order $r$ by

\begin{equation}
v_{st}:=\text{tr}\ Y_s'VY_t,
(\#eq:propcoefv)
\end{equation}

where the second $V$, of order $n$, is given by equation \@ref(eq:vdef). Then

\begin{equation}
\sigma(\theta)=1-2\ \theta'B(\theta)\theta+\theta'V\theta.
(\#eq:propcoefs)
\end{equation}

The relationship between the stationary points in configuration
space and coefficient space is fairly straightforward.

```{theorem, label = "confcoef"}

Suppose $\theta$ is in coefficient space and $X=\sum_{s=1}^r\theta_s Y_s$ is the corresponding point in configuration space.

1. If $X$ is a stationary point in configuration space then $\theta$ is a stationary point in coefficient space.
2. If $\theta$ is a stationary point in coefficient space then $X$ is a stationary point in configuration space
if and only if $\text{rank}(Y_1\mid\cdots\mid Y_r)\geq n-1$. (THIS IS WRONG)

```

::: {.proof}
We have $B(X)X=VX$, i.e. 
\begin{equation}
\sum_{s=1}^r \theta_s B(X)Y_s=\sum_{s=1}^r \theta_s VY_s.
(\#eq:propfitoff)
\end{equation}
Premultiplying both sides by $Y_t^T$ and taking the trace gives $B(\theta)\theta=V\theta$. This proves the first part.

For the second part, suppose $B(\theta)\theta=V\theta$ and define
$X=\sum_{s=1}^r\theta_s Y_s$. Then

\begin{equation}
\sum_{t=1}^r\text{tr}\ Y_s^T(B(X)-V)X=0.
(\#eq:propfftofi)
\end{equation}
  
Thus $B(X)X=VX$ if and only if $Y_s^T(B(X)-V)X=0$ for all $s$, which translates to the rank condition in the theorem (this is WRONG, correct).
:::
  
The advantage of working in coefficient space is that formulas tend to become more simple. Functions are defined on $\mathbb{R}^r$, and not a space of matrices, in which some coordinates belong to the same point (row) and others to other points (rows), and some are on the same dimension (column), while others are on different dimensions (columns).

Note that expressions such as \@ref(eq:propfitoff)
and \@ref(eq:propfitoff)
simplify if the $Y_s$ are $V$-orthonormal, i.e. if $\text{tr}\ Y_s'VY_t=\delta^{st}$ and thus $V=I$. It is easy to generate such an orthonormal set from the original $Y_s$ by using the Gram-Schmidt process. The R function gramy() in utilities.R does exactly that. Coefficient space, which is the span of the $Y_s$, is not changed by the orthogonalization process. 

For a $V$-orthonormal set $Y$ we have the stationary equations $B(\theta)\theta=\theta$, which says that $\theta$ is an eigenvector of $B(\theta)$ with eigenvalue 1.

The Hessian is

\begin{equation}
\mathcal{D}^2\sigma(\theta)=I-H(\theta),
(\#eq:hessmat)
\end{equation}

with 

\begin{equation}
H(\theta):=\mathcal{D}^2\rho(\theta)=\mathop{\sum\sum}_{1\leq i<j\leq n}w_{ij}\frac{\delta_{ij}}{d_{ij}(\theta)}\left\{C_{ij}-\frac{C_{ij}\theta\theta'C_{ij}}{\theta'C_{ij}\theta}\right\}.
(\#eq:rhohessdef)
\end{equation}

We have $0\lesssim H(\theta)\lesssim B(\theta)$ and thus $I-B(\theta)\lesssim\mathcal{D}^2\sigma(\theta)\lesssim I$.

Hessian in coef and conf space

## Spherical Space {#propspherespace}

\begin{equation}
\min_X\sigma(X)=\min_{\lambda\geq 0}\min_{\eta^2(X)=1}\sigma(\lambda X)=\min_{\eta^2(X)=1}\min_{\lambda\geq 0}\sigma(\lambda X)=
\min_{\eta^2(X)=1}1-\rho^2(X).
(\#eq:homequ)
\end{equation}

We see that basic MDS can also be formulated as maximization of $\rho$ over the ellipsoid $\{X\mid \eta^2(X)=1\}$ or, equivalently, over the convex ellipsoidal disk $\{X\mid \eta^2(X)\leq 1\}$. A similar formulation is available in coefficient space.

This shows that the MDS problem can be seen as a rather special nonlinear eigenvalue problem. @guttman_68 also discussed the similarities of MDS and eigenvalue problems, in particular as they related to the power method. In linear eigenvalue problems we maximize a convex quadratic form, in the MDS problem we maximize the homogeneous convex function $\rho$, in both cases over an ellipsoidal disk. The sublevel sets of $\rho$ defined as $\mathcal{L}_r:=\{X\mid \rho(X)\leq r\}$ are nested convex sets containing the origin. The largest of these sublevel sets that still intersects the ellipsoid $\eta^2(X)=1$ corresponds to the global minimum of stress (see section \@ref(picsphere)).

$\alpha X+\beta Y$ in sphere space one-dimensional \@ref(picline)

## Gramian Space

We can write $d_{ij}^2(X)=\text{tr}\ X'A_{ij}X = \text{tr}\ A_{ij}C,$
with $C=XX'$. This shows minimizing stress can also be formulated as minimizing

\begin{equation}
\sigma(C)=1+\text{tr}\ VC-2\mathop{\sum\sum}_{1\leq i<j\leq n}w_{ij}\delta_{ij}\sqrt{\text{tr}\ A_{ij}C}
(\#eq:stresspsd)
\end{equation}

over all $C\gtrsim 0$ of rank $r\leq p$. 

A fundamental result, which forms the basis of chapter \@ref(fullchapter) in this book, is that $\sigma$ is convex on *Gramian Space*, i.e. on the closed convex cone of all $C\gtrsim 0$.
