<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9 Interval MDS | Least Squares Euclidean Multidimensional Scaling</title>
  <meta name="description" content="null" />
  <meta name="generator" content="bookdown 0.22.3 and GitBook 2.6.7" />

  <meta property="og:title" content="9 Interval MDS | Least Squares Euclidean Multidimensional Scaling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="null" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9 Interval MDS | Least Squares Euclidean Multidimensional Scaling" />
  
  <meta name="twitter:description" content="null" />
  

<meta name="author" content="Jan de Leeuw" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="nonmtrmds.html"/>
<link rel="next" href="polynomial-and-splinical-mds.html"/>
<script src="libs/header-attrs-2.8.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#introhist"><i class="fa fa-check"></i><b>1.1</b> Brief History</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#milestones"><i class="fa fa-check"></i><b>1.1.1</b> Milestones</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#introbasic"><i class="fa fa-check"></i><b>1.2</b> Basic MDS</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#kruskals-stress"><i class="fa fa-check"></i><b>1.2.1</b> Kruskal’s stress</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#datasym"><i class="fa fa-check"></i><b>1.2.2</b> Data Asymmetry</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#local-and-global"><i class="fa fa-check"></i><b>1.2.3</b> Local and Global</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#introgeneralize"><i class="fa fa-check"></i><b>1.3</b> Generalizations</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#gennonmetric"><i class="fa fa-check"></i><b>1.3.1</b> Non-metric</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#genfstress"><i class="fa fa-check"></i><b>1.3.2</b> fstress</a></li>
<li class="chapter" data-level="1.3.3" data-path="intro.html"><a href="intro.html#gencons"><i class="fa fa-check"></i><b>1.3.3</b> Constraints</a></li>
<li class="chapter" data-level="1.3.4" data-path="intro.html"><a href="intro.html#inreplic"><i class="fa fa-check"></i><b>1.3.4</b> Replications</a></li>
<li class="chapter" data-level="1.3.5" data-path="intro.html"><a href="intro.html#genasym"><i class="fa fa-check"></i><b>1.3.5</b> Distance Asymmetry</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="propchapter.html"><a href="propchapter.html"><i class="fa fa-check"></i><b>2</b> Properties of Stress</a>
<ul>
<li class="chapter" data-level="2.1" data-path="propchapter.html"><a href="propchapter.html#propnotation"><i class="fa fa-check"></i><b>2.1</b> Notation</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="propchapter.html"><a href="propchapter.html#propexpand"><i class="fa fa-check"></i><b>2.1.1</b> Expanding</a></li>
<li class="chapter" data-level="2.1.2" data-path="propchapter.html"><a href="propchapter.html#propmatrix"><i class="fa fa-check"></i><b>2.1.2</b> Matrix Expressions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="propchapter.html"><a href="propchapter.html#propglobal"><i class="fa fa-check"></i><b>2.2</b> Global Properties</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="propchapter.html"><a href="propchapter.html#propbounded"><i class="fa fa-check"></i><b>2.2.1</b> Boundedness</a></li>
<li class="chapter" data-level="2.2.2" data-path="propchapter.html"><a href="propchapter.html#propinvariance"><i class="fa fa-check"></i><b>2.2.2</b> Invariance</a></li>
<li class="chapter" data-level="2.2.3" data-path="propchapter.html"><a href="propchapter.html#propcontinuity"><i class="fa fa-check"></i><b>2.2.3</b> Continuity</a></li>
<li class="chapter" data-level="2.2.4" data-path="propchapter.html"><a href="propchapter.html#propcoercive"><i class="fa fa-check"></i><b>2.2.4</b> Coercivity</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="propchapter.html"><a href="propchapter.html#propconvex"><i class="fa fa-check"></i><b>2.3</b> Convexity</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="propchapter.html"><a href="propchapter.html#distances"><i class="fa fa-check"></i><b>2.3.1</b> Distances</a></li>
<li class="chapter" data-level="2.3.2" data-path="propchapter.html"><a href="propchapter.html#propdc"><i class="fa fa-check"></i><b>2.3.2</b> DC Functions</a></li>
<li class="chapter" data-level="2.3.3" data-path="propchapter.html"><a href="propchapter.html#subdifferentials"><i class="fa fa-check"></i><b>2.3.3</b> Subdifferentials</a></li>
<li class="chapter" data-level="2.3.4" data-path="propchapter.html"><a href="propchapter.html#propnegdis"><i class="fa fa-check"></i><b>2.3.4</b> Negative Dissimilarities</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="propchapter.html"><a href="propchapter.html#propguttman"><i class="fa fa-check"></i><b>2.4</b> Guttman Transform</a></li>
<li class="chapter" data-level="2.5" data-path="propchapter.html"><a href="propchapter.html#propdiff"><i class="fa fa-check"></i><b>2.5</b> Differentiability</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="propchapter.html"><a href="propchapter.html#regularity"><i class="fa fa-check"></i><b>2.5.1</b> Regularity</a></li>
<li class="chapter" data-level="2.5.2" data-path="propchapter.html"><a href="propchapter.html#expansions"><i class="fa fa-check"></i><b>2.5.2</b> Expansions</a></li>
<li class="chapter" data-level="2.5.3" data-path="propchapter.html"><a href="propchapter.html#propdirderivs"><i class="fa fa-check"></i><b>2.5.3</b> Directional Derivatives</a></li>
<li class="chapter" data-level="2.5.4" data-path="propchapter.html"><a href="propchapter.html#propspecexp"><i class="fa fa-check"></i><b>2.5.4</b> Special Expansions</a></li>
<li class="chapter" data-level="2.5.5" data-path="propchapter.html"><a href="propchapter.html#propzerodist"><i class="fa fa-check"></i><b>2.5.5</b> Zero Distance Subspaces</a></li>
<li class="chapter" data-level="2.5.6" data-path="propchapter.html"><a href="propchapter.html#propdistsmo"><i class="fa fa-check"></i><b>2.5.6</b> Distance Smoothing</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="propchapter.html"><a href="propchapter.html#propstationary"><i class="fa fa-check"></i><b>2.6</b> Stationary Points</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="propchapter.html"><a href="propchapter.html#local-maxima"><i class="fa fa-check"></i><b>2.6.1</b> Local Maxima</a></li>
<li class="chapter" data-level="2.6.2" data-path="propchapter.html"><a href="propchapter.html#proplocmin"><i class="fa fa-check"></i><b>2.6.2</b> Local Minima</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="propchapter.html"><a href="propchapter.html#propenvelopes"><i class="fa fa-check"></i><b>2.7</b> Stress Envelopes</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="propchapter.html"><a href="propchapter.html#propcsmaj"><i class="fa fa-check"></i><b>2.7.1</b> CS Majorization</a></li>
<li class="chapter" data-level="2.7.2" data-path="propchapter.html"><a href="propchapter.html#propamgmmin"><i class="fa fa-check"></i><b>2.7.2</b> AM/GM Minorization</a></li>
<li class="chapter" data-level="2.7.3" data-path="propchapter.html"><a href="propchapter.html#dualities"><i class="fa fa-check"></i><b>2.7.3</b> Dualities</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="propchapter.html"><a href="propchapter.html#how-large-is-my-stress"><i class="fa fa-check"></i><b>2.8</b> How Large is My Stress ?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="propspaces.html"><a href="propspaces.html"><i class="fa fa-check"></i><b>3</b> Stress Spaces</a>
<ul>
<li class="chapter" data-level="3.1" data-path="propspaces.html"><a href="propspaces.html#propconfspace"><i class="fa fa-check"></i><b>3.1</b> Configuration Space</a></li>
<li class="chapter" data-level="3.2" data-path="propspaces.html"><a href="propspaces.html#propcoefspace"><i class="fa fa-check"></i><b>3.2</b> Coefficient Space</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="propspaces.html"><a href="propspaces.html#on-the-planes"><i class="fa fa-check"></i><b>3.2.1</b> On the Planes</a></li>
<li class="chapter" data-level="3.2.2" data-path="propspaces.html"><a href="propspaces.html#general"><i class="fa fa-check"></i><b>3.2.2</b> General</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="propspaces.html"><a href="propspaces.html#propspherespace"><i class="fa fa-check"></i><b>3.3</b> Sphere Space</a></li>
<li class="chapter" data-level="3.4" data-path="propspaces.html"><a href="propspaces.html#cross-product-space"><i class="fa fa-check"></i><b>3.4</b> Cross-Product Space</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="picsstress.html"><a href="picsstress.html"><i class="fa fa-check"></i><b>4</b> Pictures of Stress</a>
<ul>
<li class="chapter" data-level="4.1" data-path="picsstress.html"><a href="picsstress.html#coefficient-space"><i class="fa fa-check"></i><b>4.1</b> Coefficient Space</a></li>
<li class="chapter" data-level="4.2" data-path="picsstress.html"><a href="picsstress.html#global-perspective"><i class="fa fa-check"></i><b>4.2</b> Global Perspective</a></li>
<li class="chapter" data-level="4.3" data-path="picsstress.html"><a href="picsstress.html#global-contour"><i class="fa fa-check"></i><b>4.3</b> Global Contour</a></li>
<li class="chapter" data-level="4.4" data-path="picsstress.html"><a href="picsstress.html#stationary-points"><i class="fa fa-check"></i><b>4.4</b> Stationary Points</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="picsstress.html"><a href="picsstress.html#first-minimum"><i class="fa fa-check"></i><b>4.4.1</b> First Minimum</a></li>
<li class="chapter" data-level="4.4.2" data-path="picsstress.html"><a href="picsstress.html#second-minimum"><i class="fa fa-check"></i><b>4.4.2</b> Second Minimum</a></li>
<li class="chapter" data-level="4.4.3" data-path="picsstress.html"><a href="picsstress.html#third-minimum"><i class="fa fa-check"></i><b>4.4.3</b> Third Minimum</a></li>
<li class="chapter" data-level="4.4.4" data-path="picsstress.html"><a href="picsstress.html#first-saddle-point"><i class="fa fa-check"></i><b>4.4.4</b> First Saddle Point</a></li>
<li class="chapter" data-level="4.4.5" data-path="picsstress.html"><a href="picsstress.html#second-saddle-point"><i class="fa fa-check"></i><b>4.4.5</b> Second Saddle Point</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="picsstress.html"><a href="picsstress.html#picsphere"><i class="fa fa-check"></i><b>4.5</b> Another Look</a></li>
<li class="chapter" data-level="4.6" data-path="picsstress.html"><a href="picsstress.html#picline"><i class="fa fa-check"></i><b>4.6</b> A Final Look</a></li>
<li class="chapter" data-level="4.7" data-path="picsstress.html"><a href="picsstress.html#discuss"><i class="fa fa-check"></i><b>4.7</b> Discuss</a></li>
<li class="chapter" data-level="4.8" data-path="picsstress.html"><a href="picsstress.html#coordinates"><i class="fa fa-check"></i><b>4.8</b> Coordinates</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html"><i class="fa fa-check"></i><b>5</b> Classical Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#algebra"><i class="fa fa-check"></i><b>5.1</b> Algebra</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#torgerson-transform"><i class="fa fa-check"></i><b>5.1.1</b> Torgerson Transform</a></li>
<li class="chapter" data-level="5.1.2" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#schoenbergs-theorem"><i class="fa fa-check"></i><b>5.1.2</b> Schoenberg’s Theorem</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#approximation"><i class="fa fa-check"></i><b>5.2</b> Approximation</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#low-rank-approximation-of-the-torgersen-transform"><i class="fa fa-check"></i><b>5.2.1</b> Low Rank Approximation of the Torgersen Transform</a></li>
<li class="chapter" data-level="5.2.2" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#minimization-of-strain"><i class="fa fa-check"></i><b>5.2.2</b> Minimization of Strain</a></li>
<li class="chapter" data-level="5.2.3" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#approximation-from-below"><i class="fa fa-check"></i><b>5.2.3</b> Approximation from Below</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="minstr.html"><a href="minstr.html"><i class="fa fa-check"></i><b>6</b> Minimization of Stress</a>
<ul>
<li class="chapter" data-level="6.1" data-path="minstr.html"><a href="minstr.html#gradient-methods"><i class="fa fa-check"></i><b>6.1</b> Gradient Methods</a></li>
<li class="chapter" data-level="6.2" data-path="minstr.html"><a href="minstr.html#initial-configurations"><i class="fa fa-check"></i><b>6.2</b> Initial Configurations</a></li>
<li class="chapter" data-level="6.3" data-path="minstr.html"><a href="minstr.html#apmajmin"><i class="fa fa-check"></i><b>6.3</b> On MM Algorithms</a></li>
<li class="chapter" data-level="6.4" data-path="minstr.html"><a href="minstr.html#smacof-algorithm"><i class="fa fa-check"></i><b>6.4</b> Smacof Algorithm</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="minstr.html"><a href="minstr.html#global-convergence"><i class="fa fa-check"></i><b>6.4.1</b> Global Convergence</a></li>
<li class="chapter" data-level="6.4.2" data-path="minstr.html"><a href="minstr.html#from-the-cs-inequality"><i class="fa fa-check"></i><b>6.4.2</b> From the CS Inequality</a></li>
<li class="chapter" data-level="6.4.3" data-path="minstr.html"><a href="minstr.html#from-majorization"><i class="fa fa-check"></i><b>6.4.3</b> From Majorization</a></li>
<li class="chapter" data-level="6.4.4" data-path="minstr.html"><a href="minstr.html#mincomprot"><i class="fa fa-check"></i><b>6.4.4</b> Component Rotated Smacof</a></li>
<li class="chapter" data-level="6.4.5" data-path="minstr.html"><a href="minstr.html#minlocconv"><i class="fa fa-check"></i><b>6.4.5</b> Local Convergence</a></li>
<li class="chapter" data-level="6.4.6" data-path="minstr.html"><a href="minstr.html#negative-dissimilarities"><i class="fa fa-check"></i><b>6.4.6</b> Negative Dissimilarities</a></li>
<li class="chapter" data-level="6.4.7" data-path="minstr.html"><a href="minstr.html#minunweight"><i class="fa fa-check"></i><b>6.4.7</b> Unweighting</a></li>
<li class="chapter" data-level="6.4.8" data-path="minstr.html"><a href="minstr.html#smacof-in-coefficient-space"><i class="fa fa-check"></i><b>6.4.8</b> Smacof in Coefficient Space</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="minstr.html"><a href="minstr.html#regions-of-attraction"><i class="fa fa-check"></i><b>6.5</b> Regions of Attraction</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="minstr.html"><a href="minstr.html#smacof"><i class="fa fa-check"></i><b>6.5.1</b> Smacof</a></li>
<li class="chapter" data-level="6.5.2" data-path="minstr.html"><a href="minstr.html#newton"><i class="fa fa-check"></i><b>6.5.2</b> Newton</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chacceleration.html"><a href="chacceleration.html"><i class="fa fa-check"></i><b>7</b> Acceleration of Convergence</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chacceleration.html"><a href="chacceleration.html#accelsimple"><i class="fa fa-check"></i><b>7.1</b> Simple Acceleration</a></li>
<li class="chapter" data-level="7.2" data-path="chacceleration.html"><a href="chacceleration.html#one-parameter-methods"><i class="fa fa-check"></i><b>7.2</b> One-Parameter Methods</a></li>
<li class="chapter" data-level="7.3" data-path="chacceleration.html"><a href="chacceleration.html#squarem"><i class="fa fa-check"></i><b>7.3</b> SQUAREM</a></li>
<li class="chapter" data-level="7.4" data-path="chacceleration.html"><a href="chacceleration.html#vector-extrapolation-methods"><i class="fa fa-check"></i><b>7.4</b> Vector extrapolation methods</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nonmtrmds.html"><a href="nonmtrmds.html"><i class="fa fa-check"></i><b>8</b> Nonmetric MDS</a>
<ul>
<li class="chapter" data-level="8.1" data-path="nonmtrmds.html"><a href="nonmtrmds.html#generalities"><i class="fa fa-check"></i><b>8.1</b> Generalities</a></li>
<li class="chapter" data-level="8.2" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmssingledouble"><i class="fa fa-check"></i><b>8.2</b> Single and Double Phase</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="nonmtrmds.html"><a href="nonmtrmds.html#double-phase"><i class="fa fa-check"></i><b>8.2.1</b> Double Phase</a></li>
<li class="chapter" data-level="8.2.2" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmssinglephase"><i class="fa fa-check"></i><b>8.2.2</b> Single Phase</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="nonmtrmds.html"><a href="nonmtrmds.html#affine-nmds"><i class="fa fa-check"></i><b>8.3</b> Affine NMDS</a></li>
<li class="chapter" data-level="8.4" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmdsconic"><i class="fa fa-check"></i><b>8.4</b> Conic MDS</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmdsnorm"><i class="fa fa-check"></i><b>8.4.1</b> Normalization</a></li>
<li class="chapter" data-level="8.4.2" data-path="nonmtrmds.html"><a href="nonmtrmds.html#inner-iterations"><i class="fa fa-check"></i><b>8.4.2</b> Inner Iterations</a></li>
<li class="chapter" data-level="8.4.3" data-path="nonmtrmds.html"><a href="nonmtrmds.html#stress-1-and-stress-2"><i class="fa fa-check"></i><b>8.4.3</b> Stress-1 and Stress-2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="intinterval.html"><a href="intinterval.html"><i class="fa fa-check"></i><b>9</b> Interval MDS</a>
<ul>
<li class="chapter" data-level="9.1" data-path="intinterval.html"><a href="intinterval.html#intadditive"><i class="fa fa-check"></i><b>9.1</b> The Additive Constant</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="intinterval.html"><a href="intinterval.html#exactad"><i class="fa fa-check"></i><b>9.1.1</b> Algebra</a></li>
<li class="chapter" data-level="9.1.2" data-path="intinterval.html"><a href="intinterval.html#examples"><i class="fa fa-check"></i><b>9.1.2</b> Examples</a></li>
<li class="chapter" data-level="9.1.3" data-path="intinterval.html"><a href="intinterval.html#variation"><i class="fa fa-check"></i><b>9.1.3</b> A Variation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html"><i class="fa fa-check"></i><b>10</b> Polynomial and Splinical MDS</a>
<ul>
<li class="chapter" data-level="10.1" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#polynomial-mds"><i class="fa fa-check"></i><b>10.1</b> Polynomial MDS</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#monotone-polynomials"><i class="fa fa-check"></i><b>10.1.1</b> Monotone Polynomials</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#splinical-mds"><i class="fa fa-check"></i><b>10.2</b> Splinical MDS</a></li>
<li class="chapter" data-level="10.3" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#mathsplines"><i class="fa fa-check"></i><b>10.3</b> Splines</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#mathbsplines"><i class="fa fa-check"></i><b>10.3.1</b> B-splines</a></li>
<li class="chapter" data-level="10.3.2" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#mathisplines"><i class="fa fa-check"></i><b>10.3.2</b> I-splines</a></li>
<li class="chapter" data-level="10.3.3" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#time-series-example"><i class="fa fa-check"></i><b>10.3.3</b> Time Series Example</a></li>
<li class="chapter" data-level="10.3.4" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#monotone-splines"><i class="fa fa-check"></i><b>10.3.4</b> Monotone Splines</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chapordinal.html"><a href="chapordinal.html"><i class="fa fa-check"></i><b>11</b> Ordinal MDS</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chapordinal.html"><a href="chapordinal.html#mathmonreg"><i class="fa fa-check"></i><b>11.1</b> Monotone Regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chapordinal.html"><a href="chapordinal.html#mathsimpiso"><i class="fa fa-check"></i><b>11.1.1</b> Simple Monotone Regression</a></li>
<li class="chapter" data-level="11.1.2" data-path="chapordinal.html"><a href="chapordinal.html#mathweigmr"><i class="fa fa-check"></i><b>11.1.2</b> Weighted Monotone Regression</a></li>
<li class="chapter" data-level="11.1.3" data-path="chapordinal.html"><a href="chapordinal.html#mathnorcone"><i class="fa fa-check"></i><b>11.1.3</b> Normalized Cone Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chapordinal.html"><a href="chapordinal.html#nmdsals"><i class="fa fa-check"></i><b>11.2</b> Alternating Least Squares</a></li>
<li class="chapter" data-level="11.3" data-path="chapordinal.html"><a href="chapordinal.html#nmdskruskal"><i class="fa fa-check"></i><b>11.3</b> Kruskal’s Approach</a></li>
<li class="chapter" data-level="11.4" data-path="chapordinal.html"><a href="chapordinal.html#nmdsguttman"><i class="fa fa-check"></i><b>11.4</b> Guttman’s Approach</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="chapordinal.html"><a href="chapordinal.html#smoothness-of-ordinal-loss-functions"><i class="fa fa-check"></i><b>11.4.1</b> Smoothness of Ordinal Loss Functions</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="chapordinal.html"><a href="chapordinal.html#scaling-with-distance-bounds"><i class="fa fa-check"></i><b>11.5</b> Scaling with Distance Bounds</a></li>
<li class="chapter" data-level="11.6" data-path="chapordinal.html"><a href="chapordinal.html#bounds-on-stress"><i class="fa fa-check"></i><b>11.6</b> Bounds on Stress</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unidimensional.html"><a href="unidimensional.html"><i class="fa fa-check"></i><b>12</b> Unidimensional Scaling</a>
<ul>
<li class="chapter" data-level="12.1" data-path="unidimensional.html"><a href="unidimensional.html#an-example"><i class="fa fa-check"></i><b>12.1</b> An example</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="unidimensional.html"><a href="unidimensional.html#perspective"><i class="fa fa-check"></i><b>12.1.1</b> Perspective</a></li>
<li class="chapter" data-level="12.1.2" data-path="unidimensional.html"><a href="unidimensional.html#contour"><i class="fa fa-check"></i><b>12.1.2</b> Contour</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="unidimensional.html"><a href="unidimensional.html#order-formulation"><i class="fa fa-check"></i><b>12.2</b> Order Formulation</a></li>
<li class="chapter" data-level="12.3" data-path="unidimensional.html"><a href="unidimensional.html#permutation-formulation"><i class="fa fa-check"></i><b>12.3</b> Permutation Formulation</a></li>
<li class="chapter" data-level="12.4" data-path="unidimensional.html"><a href="unidimensional.html#sign-matrix-formulation"><i class="fa fa-check"></i><b>12.4</b> Sign Matrix Formulation</a></li>
<li class="chapter" data-level="12.5" data-path="unidimensional.html"><a href="unidimensional.html#unialgorithms"><i class="fa fa-check"></i><b>12.5</b> Algorithms for UMDS</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="unidimensional.html"><a href="unidimensional.html#unismacof"><i class="fa fa-check"></i><b>12.5.1</b> SMACOF</a></li>
<li class="chapter" data-level="12.5.2" data-path="unidimensional.html"><a href="unidimensional.html#unismoothed"><i class="fa fa-check"></i><b>12.5.2</b> SMACOF (smoothed)</a></li>
<li class="chapter" data-level="12.5.3" data-path="unidimensional.html"><a href="unidimensional.html#unibranchbound"><i class="fa fa-check"></i><b>12.5.3</b> Branch-and-Bound</a></li>
<li class="chapter" data-level="12.5.4" data-path="unidimensional.html"><a href="unidimensional.html#unidynamic"><i class="fa fa-check"></i><b>12.5.4</b> Dynamic Programming</a></li>
<li class="chapter" data-level="12.5.5" data-path="unidimensional.html"><a href="unidimensional.html#uniannealing"><i class="fa fa-check"></i><b>12.5.5</b> Simulated Annealing</a></li>
<li class="chapter" data-level="12.5.6" data-path="unidimensional.html"><a href="unidimensional.html#unipenalty"><i class="fa fa-check"></i><b>12.5.6</b> Penalty Methods</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="fullchapter.html"><a href="fullchapter.html"><i class="fa fa-check"></i><b>13</b> Full-dimensional Scaling</a>
<ul>
<li class="chapter" data-level="13.1" data-path="fullchapter.html"><a href="fullchapter.html#fullconvex"><i class="fa fa-check"></i><b>13.1</b> Convexity</a></li>
<li class="chapter" data-level="13.2" data-path="fullchapter.html"><a href="fullchapter.html#fulloptimal"><i class="fa fa-check"></i><b>13.2</b> Optimality</a></li>
<li class="chapter" data-level="13.3" data-path="fullchapter.html"><a href="fullchapter.html#fulliteration"><i class="fa fa-check"></i><b>13.3</b> Iteration</a></li>
<li class="chapter" data-level="13.4" data-path="fullchapter.html"><a href="fullchapter.html#fullcpspace"><i class="fa fa-check"></i><b>13.4</b> Cross Product Space</a></li>
<li class="chapter" data-level="13.5" data-path="fullchapter.html"><a href="fullchapter.html#full-dimensional-scaling"><i class="fa fa-check"></i><b>13.5</b> Full-dimensional Scaling</a></li>
<li class="chapter" data-level="13.6" data-path="fullchapter.html"><a href="fullchapter.html#ekman-example-1"><i class="fa fa-check"></i><b>13.6</b> Ekman example</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chunfolding.html"><a href="chunfolding.html"><i class="fa fa-check"></i><b>14</b> Unfolding</a>
<ul>
<li class="chapter" data-level="14.1" data-path="chunfolding.html"><a href="chunfolding.html#algebra-1"><i class="fa fa-check"></i><b>14.1</b> Algebra</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="chunfolding.html"><a href="chunfolding.html#one-dimensional"><i class="fa fa-check"></i><b>14.1.1</b> One-dimensional</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="chunfolding.html"><a href="chunfolding.html#classical-unfolding"><i class="fa fa-check"></i><b>14.2</b> Classical Unfolding</a></li>
<li class="chapter" data-level="14.3" data-path="chunfolding.html"><a href="chunfolding.html#nonmetric-unfolding"><i class="fa fa-check"></i><b>14.3</b> Nonmetric Unfolding</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="chunfolding.html"><a href="chunfolding.html#unfdegenerate"><i class="fa fa-check"></i><b>14.3.1</b> Degenerate Solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="cmds.html"><a href="cmds.html"><i class="fa fa-check"></i><b>15</b> Constrained Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="15.1" data-path="cmds.html"><a href="cmds.html#baspar"><i class="fa fa-check"></i><b>15.1</b> Basic Partitioning</a></li>
<li class="chapter" data-level="15.2" data-path="cmds.html"><a href="cmds.html#majawa"><i class="fa fa-check"></i><b>15.2</b> Unweigthing</a></li>
<li class="chapter" data-level="15.3" data-path="cmds.html"><a href="cmds.html#constraints-on-the-distances"><i class="fa fa-check"></i><b>15.3</b> Constraints on the Distances</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="cmds.html"><a href="cmds.html#rectangles"><i class="fa fa-check"></i><b>15.3.1</b> Rectangles</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="cmds.html"><a href="cmds.html#lincons"><i class="fa fa-check"></i><b>15.4</b> Linear Constraints</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="cmds.html"><a href="cmds.html#uniqueness"><i class="fa fa-check"></i><b>15.4.1</b> Uniqueness</a></li>
<li class="chapter" data-level="15.4.2" data-path="cmds.html"><a href="cmds.html#combinations"><i class="fa fa-check"></i><b>15.4.2</b> Combinations</a></li>
<li class="chapter" data-level="15.4.3" data-path="cmds.html"><a href="cmds.html#stepsize"><i class="fa fa-check"></i><b>15.4.3</b> Step Size</a></li>
<li class="chapter" data-level="15.4.4" data-path="cmds.html"><a href="cmds.html#singdesign"><i class="fa fa-check"></i><b>15.4.4</b> Single Design Matrix</a></li>
<li class="chapter" data-level="15.4.5" data-path="cmds.html"><a href="cmds.html#multdesign"><i class="fa fa-check"></i><b>15.4.5</b> Multiple Design Matrices</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="cmds.html"><a href="cmds.html#circmds"><i class="fa fa-check"></i><b>15.5</b> Circular MDS</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="cmds.html"><a href="cmds.html#circhist"><i class="fa fa-check"></i><b>15.5.1</b> Some History</a></li>
<li class="chapter" data-level="15.5.2" data-path="cmds.html"><a href="cmds.html#circprimal"><i class="fa fa-check"></i><b>15.5.2</b> Primal Methods</a></li>
<li class="chapter" data-level="15.5.3" data-path="cmds.html"><a href="cmds.html#circdual"><i class="fa fa-check"></i><b>15.5.3</b> Dual Methods</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="cmds.html"><a href="cmds.html#ellimcds"><i class="fa fa-check"></i><b>15.6</b> Elliptical MDS</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="cmds.html"><a href="cmds.html#elliprimal"><i class="fa fa-check"></i><b>15.6.1</b> Primal</a></li>
<li class="chapter" data-level="15.6.2" data-path="cmds.html"><a href="cmds.html#ellidual"><i class="fa fa-check"></i><b>15.6.2</b> Dual</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="cmds.html"><a href="cmds.html#distance-bounds"><i class="fa fa-check"></i><b>15.7</b> Distance Bounds</a></li>
<li class="chapter" data-level="15.8" data-path="cmds.html"><a href="cmds.html#localized-mds"><i class="fa fa-check"></i><b>15.8</b> Localized MDS</a></li>
<li class="chapter" data-level="15.9" data-path="cmds.html"><a href="cmds.html#mds-as-mva"><i class="fa fa-check"></i><b>15.9</b> MDS as MVA</a></li>
<li class="chapter" data-level="15.10" data-path="cmds.html"><a href="cmds.html#conshorseshoes"><i class="fa fa-check"></i><b>15.10</b> Horseshoes</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="asymmds.html"><a href="asymmds.html"><i class="fa fa-check"></i><b>16</b> Asymmetry in MDS</a>
<ul>
<li class="chapter" data-level="16.1" data-path="asymmds.html"><a href="asymmds.html#conditional-rankings"><i class="fa fa-check"></i><b>16.1</b> Conditional Rankings</a></li>
<li class="chapter" data-level="16.2" data-path="asymmds.html"><a href="asymmds.html#confusion-matrices"><i class="fa fa-check"></i><b>16.2</b> Confusion Matrices</a></li>
<li class="chapter" data-level="16.3" data-path="asymmds.html"><a href="asymmds.html#the-slide-vector"><i class="fa fa-check"></i><b>16.3</b> The Slide Vector</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="chindif.html"><a href="chindif.html"><i class="fa fa-check"></i><b>17</b> Individual Differences</a>
<ul>
<li class="chapter" data-level="17.1" data-path="chindif.html"><a href="chindif.html#indifrepl"><i class="fa fa-check"></i><b>17.1</b> Replications</a></li>
<li class="chapter" data-level="17.2" data-path="chindif.html"><a href="chindif.html#indifindscal"><i class="fa fa-check"></i><b>17.2</b> INDSCAL/PARAFAC</a></li>
<li class="chapter" data-level="17.3" data-path="chindif.html"><a href="chindif.html#indifidioscal"><i class="fa fa-check"></i><b>17.3</b> IDIOSCAL/TUCKALS</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chnominal.html"><a href="chnominal.html"><i class="fa fa-check"></i><b>18</b> Nominal MDS</a>
<ul>
<li class="chapter" data-level="18.1" data-path="chnominal.html"><a href="chnominal.html#binary-dissimilarities"><i class="fa fa-check"></i><b>18.1</b> Binary Dissimilarities</a></li>
<li class="chapter" data-level="18.2" data-path="chnominal.html"><a href="chnominal.html#indicator-matrix"><i class="fa fa-check"></i><b>18.2</b> Indicator matrix</a></li>
<li class="chapter" data-level="18.3" data-path="chnominal.html"><a href="chnominal.html#unfolding-indicator-matrices"><i class="fa fa-check"></i><b>18.3</b> Unfolding Indicator Matrices</a></li>
<li class="chapter" data-level="18.4" data-path="chnominal.html"><a href="chnominal.html#linear-separation"><i class="fa fa-check"></i><b>18.4</b> Linear Separation</a></li>
<li class="chapter" data-level="18.5" data-path="chnominal.html"><a href="chnominal.html#circular-separation"><i class="fa fa-check"></i><b>18.5</b> Circular Separation</a></li>
<li class="chapter" data-level="18.6" data-path="chnominal.html"><a href="chnominal.html#multidimensional-scalogram-analysis"><i class="fa fa-check"></i><b>18.6</b> Multidimensional Scalogram Analysis</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="ssstr.html"><a href="ssstr.html"><i class="fa fa-check"></i><b>19</b> Sstress and strain</a>
<ul>
<li class="chapter" data-level="19.1" data-path="ssstr.html"><a href="ssstr.html#sstress"><i class="fa fa-check"></i><b>19.1</b> sstress</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="ssstr.html"><a href="ssstr.html#sstress-and-stress"><i class="fa fa-check"></i><b>19.1.1</b> sstress and stress</a></li>
<li class="chapter" data-level="19.1.2" data-path="ssstr.html"><a href="ssstr.html#decomposition"><i class="fa fa-check"></i><b>19.1.2</b> Decomposition</a></li>
<li class="chapter" data-level="19.1.3" data-path="ssstr.html"><a href="ssstr.html#full-dimensional-sstress"><i class="fa fa-check"></i><b>19.1.3</b> Full-dimensional sstress</a></li>
<li class="chapter" data-level="19.1.4" data-path="ssstr.html"><a href="ssstr.html#minimizing-sstress"><i class="fa fa-check"></i><b>19.1.4</b> Minimizing sstress</a></li>
<li class="chapter" data-level="19.1.5" data-path="ssstr.html"><a href="ssstr.html#bounds-for-sstress"><i class="fa fa-check"></i><b>19.1.5</b> Bounds for sstress</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="ssstr.html"><a href="ssstr.html#strain"><i class="fa fa-check"></i><b>19.2</b> strain</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="ssstr.html"><a href="ssstr.html#unweighted"><i class="fa fa-check"></i><b>19.2.1</b> Unweighted</a></li>
<li class="chapter" data-level="19.2.2" data-path="ssstr.html"><a href="ssstr.html#using-additivity"><i class="fa fa-check"></i><b>19.2.2</b> Using Additivity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="chrstress.html"><a href="chrstress.html"><i class="fa fa-check"></i><b>20</b> fstress and rstress</a>
<ul>
<li class="chapter" data-level="20.1" data-path="chrstress.html"><a href="chrstress.html#fstress"><i class="fa fa-check"></i><b>20.1</b> fstress</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="chrstress.html"><a href="chrstress.html#use-of-weights"><i class="fa fa-check"></i><b>20.1.1</b> Use of Weights</a></li>
<li class="chapter" data-level="20.1.2" data-path="chrstress.html"><a href="chrstress.html#convexity"><i class="fa fa-check"></i><b>20.1.2</b> Convexity</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="chrstress.html"><a href="chrstress.html#rstress"><i class="fa fa-check"></i><b>20.2</b> rStress</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="chrstress.html"><a href="chrstress.html#using-weights"><i class="fa fa-check"></i><b>20.2.1</b> Using Weights</a></li>
<li class="chapter" data-level="20.2.2" data-path="chrstress.html"><a href="chrstress.html#minimizing-rstress"><i class="fa fa-check"></i><b>20.2.2</b> Minimizing rstress</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="chrstress.html"><a href="chrstress.html#mstress"><i class="fa fa-check"></i><b>20.3</b> mstress</a></li>
<li class="chapter" data-level="20.4" data-path="chrstress.html"><a href="chrstress.html#astress"><i class="fa fa-check"></i><b>20.4</b> astress</a></li>
<li class="chapter" data-level="20.5" data-path="chrstress.html"><a href="chrstress.html#pstress"><i class="fa fa-check"></i><b>20.5</b> pstress</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html"><i class="fa fa-check"></i><b>21</b> Alternative Least Squares Loss</a>
<ul>
<li class="chapter" data-level="21.1" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#sammons-mds"><i class="fa fa-check"></i><b>21.1</b> Sammon’s MDS</a></li>
<li class="chapter" data-level="21.2" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#mcgees-work"><i class="fa fa-check"></i><b>21.2</b> McGee’s Work</a></li>
<li class="chapter" data-level="21.3" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#shepards-nonmetric-mds"><i class="fa fa-check"></i><b>21.3</b> Shepard’s Nonmetric MDS</a></li>
<li class="chapter" data-level="21.4" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#guttmans-nonmetric-mds"><i class="fa fa-check"></i><b>21.4</b> Guttman’s Nonmetric MDS</a></li>
<li class="chapter" data-level="21.5" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#positive-orthant-nonmetric-mds"><i class="fa fa-check"></i><b>21.5</b> Positive Orthant Nonmetric MDS</a></li>
<li class="chapter" data-level="21.6" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#interrole"><i class="fa fa-check"></i><b>21.6</b> Role Reversal</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html"><i class="fa fa-check"></i><b>22</b> Inverse Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="22.1" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#basic-imds"><i class="fa fa-check"></i><b>22.1</b> Basic IMDS</a></li>
<li class="chapter" data-level="22.2" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#non-negative-dissimilarities"><i class="fa fa-check"></i><b>22.2</b> Non-negative Dissimilarities</a></li>
<li class="chapter" data-level="22.3" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#zero-weights-andor-distances"><i class="fa fa-check"></i><b>22.3</b> Zero Weights and/or Distances</a></li>
<li class="chapter" data-level="22.4" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#examples-1"><i class="fa fa-check"></i><b>22.4</b> Examples</a>
<ul>
<li class="chapter" data-level="22.4.1" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#first-example"><i class="fa fa-check"></i><b>22.4.1</b> First Example</a></li>
<li class="chapter" data-level="22.4.2" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#second-example"><i class="fa fa-check"></i><b>22.4.2</b> Second Example</a></li>
<li class="chapter" data-level="22.4.3" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#third-example"><i class="fa fa-check"></i><b>22.4.3</b> Third Example</a></li>
<li class="chapter" data-level="22.4.4" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#fourth-example"><i class="fa fa-check"></i><b>22.4.4</b> Fourth Example</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#mds-sensitivity"><i class="fa fa-check"></i><b>22.5</b> MDS Sensitivity</a></li>
<li class="chapter" data-level="22.6" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#second-order-inverse-mds"><i class="fa fa-check"></i><b>22.6</b> Second Order Inverse MDS</a></li>
<li class="chapter" data-level="22.7" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#inverse-fds"><i class="fa fa-check"></i><b>22.7</b> Inverse FDS</a></li>
<li class="chapter" data-level="22.8" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#multiple-solutions"><i class="fa fa-check"></i><b>22.8</b> Multiple Solutions</a></li>
<li class="chapter" data-level="22.9" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#minimizing-istress"><i class="fa fa-check"></i><b>22.9</b> Minimizing iStress</a></li>
<li class="chapter" data-level="22.10" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#order-three"><i class="fa fa-check"></i><b>22.10</b> Order three</a></li>
<li class="chapter" data-level="22.11" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#order-four"><i class="fa fa-check"></i><b>22.11</b> Order Four</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="stability.html"><a href="stability.html"><i class="fa fa-check"></i><b>23</b> Stability of MDS Solutions</a>
<ul>
<li class="chapter" data-level="23.1" data-path="stability.html"><a href="stability.html#null-distribution"><i class="fa fa-check"></i><b>23.1</b> Null Distribution</a></li>
<li class="chapter" data-level="23.2" data-path="stability.html"><a href="stability.html#pseudo-confidence-ellipsoids"><i class="fa fa-check"></i><b>23.2</b> Pseudo-confidence Ellipsoids</a></li>
<li class="chapter" data-level="23.3" data-path="stability.html"><a href="stability.html#a-pseudo-bootstrap"><i class="fa fa-check"></i><b>23.3</b> A Pseudo-Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="global.html"><a href="global.html"><i class="fa fa-check"></i><b>24</b> In Search of Global Minima</a>
<ul>
<li class="chapter" data-level="24.1" data-path="global.html"><a href="global.html#random-starts"><i class="fa fa-check"></i><b>24.1</b> Random Starts</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="global.html"><a href="global.html#examples-2"><i class="fa fa-check"></i><b>24.1.1</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="global.html"><a href="global.html#tunneling-filling-annealing-etc."><i class="fa fa-check"></i><b>24.2</b> Tunneling, Filling, Annealing, etc.</a></li>
<li class="chapter" data-level="24.3" data-path="global.html"><a href="global.html#globcutplanes"><i class="fa fa-check"></i><b>24.3</b> Cutting Planes</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="global.html"><a href="global.html#globalcircle"><i class="fa fa-check"></i><b>24.3.1</b> On the Circle</a></li>
<li class="chapter" data-level="24.3.2" data-path="global.html"><a href="global.html#cauchy-step-size"><i class="fa fa-check"></i><b>24.3.2</b> Cauchy Step Size</a></li>
<li class="chapter" data-level="24.3.3" data-path="global.html"><a href="global.html#balls"><i class="fa fa-check"></i><b>24.3.3</b> Balls</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="global.html"><a href="global.html#distance-smoothing"><i class="fa fa-check"></i><b>24.4</b> Distance Smoothing</a></li>
<li class="chapter" data-level="24.5" data-path="global.html"><a href="global.html#penalizing-dimensions"><i class="fa fa-check"></i><b>24.5</b> Penalizing Dimensions</a>
<ul>
<li class="chapter" data-level="24.5.1" data-path="global.html"><a href="global.html#local-minima"><i class="fa fa-check"></i><b>24.5.1</b> Local Minima</a></li>
<li class="chapter" data-level="24.5.2" data-path="global.html"><a href="global.html#algorithm"><i class="fa fa-check"></i><b>24.5.2</b> Algorithm</a></li>
<li class="chapter" data-level="24.5.3" data-path="global.html"><a href="global.html#examples-3"><i class="fa fa-check"></i><b>24.5.3</b> Examples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="mathadd.html"><a href="mathadd.html"><i class="fa fa-check"></i><b>25</b> Mathematical Addenda</a>
<ul>
<li class="chapter" data-level="25.1" data-path="mathadd.html"><a href="mathadd.html#apnotation"><i class="fa fa-check"></i><b>25.1</b> Notation</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="mathadd.html"><a href="mathadd.html#symbols"><i class="fa fa-check"></i><b>25.1.1</b> Symbols</a></li>
<li class="chapter" data-level="25.1.2" data-path="mathadd.html"><a href="mathadd.html#summation"><i class="fa fa-check"></i><b>25.1.2</b> Summation</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="mathadd.html"><a href="mathadd.html#apmatrices"><i class="fa fa-check"></i><b>25.2</b> Matrices</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="mathadd.html"><a href="mathadd.html#apmspaces"><i class="fa fa-check"></i><b>25.2.1</b> Matrix Spaces</a></li>
<li class="chapter" data-level="25.2.2" data-path="mathadd.html"><a href="mathadd.html#apconstants"><i class="fa fa-check"></i><b>25.2.2</b> Constants</a></li>
<li class="chapter" data-level="25.2.3" data-path="mathadd.html"><a href="mathadd.html#difmat"><i class="fa fa-check"></i><b>25.2.3</b> Diff Matrices</a></li>
<li class="chapter" data-level="25.2.4" data-path="mathadd.html"><a href="mathadd.html#apsign"><i class="fa fa-check"></i><b>25.2.4</b> Sign Matrices</a></li>
<li class="chapter" data-level="25.2.5" data-path="mathadd.html"><a href="mathadd.html#apcombo"><i class="fa fa-check"></i><b>25.2.5</b> Sums and Products</a></li>
<li class="chapter" data-level="25.2.6" data-path="mathadd.html"><a href="mathadd.html#apinverse"><i class="fa fa-check"></i><b>25.2.6</b> Inverse</a></li>
<li class="chapter" data-level="25.2.7" data-path="mathadd.html"><a href="mathadd.html#aploewner"><i class="fa fa-check"></i><b>25.2.7</b> The Loewner order</a></li>
<li class="chapter" data-level="25.2.8" data-path="mathadd.html"><a href="mathadd.html#apeigen"><i class="fa fa-check"></i><b>25.2.8</b> Eigen Decomposition</a></li>
<li class="chapter" data-level="25.2.9" data-path="mathadd.html"><a href="mathadd.html#apsvd"><i class="fa fa-check"></i><b>25.2.9</b> Singular Value Decomposition</a></li>
<li class="chapter" data-level="25.2.10" data-path="mathadd.html"><a href="mathadd.html#apmpi"><i class="fa fa-check"></i><b>25.2.10</b> Moore-Penrose Inverse</a></li>
<li class="chapter" data-level="25.2.11" data-path="mathadd.html"><a href="mathadd.html#apfullrank"><i class="fa fa-check"></i><b>25.2.11</b> Full-rank Decomposition</a></li>
<li class="chapter" data-level="25.2.12" data-path="mathadd.html"><a href="mathadd.html#apsdc"><i class="fa fa-check"></i><b>25.2.12</b> SDC matrices</a></li>
</ul></li>
<li class="chapter" data-level="25.3" data-path="mathadd.html"><a href="mathadd.html#apineq"><i class="fa fa-check"></i><b>25.3</b> Inequalities</a>
<ul>
<li class="chapter" data-level="25.3.1" data-path="mathadd.html"><a href="mathadd.html#apcs"><i class="fa fa-check"></i><b>25.3.1</b> Cauchy-Schwartz</a></li>
<li class="chapter" data-level="25.3.2" data-path="mathadd.html"><a href="mathadd.html#apamgm"><i class="fa fa-check"></i><b>25.3.2</b> Arithmetic/Geometric Mean</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="mathadd.html"><a href="mathadd.html#apanal"><i class="fa fa-check"></i><b>25.4</b> Calculus/Analysis</a>
<ul>
<li class="chapter" data-level="25.4.1" data-path="mathadd.html"><a href="mathadd.html#appfunctions"><i class="fa fa-check"></i><b>25.4.1</b> Functions</a></li>
<li class="chapter" data-level="25.4.2" data-path="mathadd.html"><a href="mathadd.html#appdiffer"><i class="fa fa-check"></i><b>25.4.2</b> Differentiation</a></li>
<li class="chapter" data-level="25.4.3" data-path="mathadd.html"><a href="mathadd.html#apdirder"><i class="fa fa-check"></i><b>25.4.3</b> Directional Derivatives</a></li>
<li class="chapter" data-level="25.4.4" data-path="mathadd.html"><a href="mathadd.html#local-minima-critical-points"><i class="fa fa-check"></i><b>25.4.4</b> Local Minima, Critical Points</a></li>
<li class="chapter" data-level="25.4.5" data-path="mathadd.html"><a href="mathadd.html#necessary"><i class="fa fa-check"></i><b>25.4.5</b> Necessary Conditions</a></li>
<li class="chapter" data-level="25.4.6" data-path="mathadd.html"><a href="mathadd.html#hopital"><i class="fa fa-check"></i><b>25.4.6</b> l’Hôpital’s Rule</a></li>
<li class="chapter" data-level="25.4.7" data-path="mathadd.html"><a href="mathadd.html#mathimplcit"><i class="fa fa-check"></i><b>25.4.7</b> Implicit Functions</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="mathadd.html"><a href="mathadd.html#mathconvexfuncs"><i class="fa fa-check"></i><b>25.5</b> Convexity</a>
<ul>
<li class="chapter" data-level="25.5.1" data-path="mathadd.html"><a href="mathadd.html#mathextminima"><i class="fa fa-check"></i><b>25.5.1</b> Existence of Minima</a></li>
<li class="chapter" data-level="25.5.2" data-path="mathadd.html"><a href="mathadd.html#mathduality"><i class="fa fa-check"></i><b>25.5.2</b> Duality</a></li>
<li class="chapter" data-level="25.5.3" data-path="mathadd.html"><a href="mathadd.html#mathsubdif"><i class="fa fa-check"></i><b>25.5.3</b> Subdifferentials</a></li>
<li class="chapter" data-level="25.5.4" data-path="mathadd.html"><a href="mathadd.html#mathextdcfunc"><i class="fa fa-check"></i><b>25.5.4</b> DC Functions</a></li>
<li class="chapter" data-level="25.5.5" data-path="mathadd.html"><a href="mathadd.html#mathdanskin"><i class="fa fa-check"></i><b>25.5.5</b> Danskin-Berge Theorem</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="mathadd.html"><a href="mathadd.html#apiterate"><i class="fa fa-check"></i><b>25.6</b> Fixed-Point Iterations</a>
<ul>
<li class="chapter" data-level="25.6.1" data-path="mathadd.html"><a href="mathadd.html#point-to-set-maps"><i class="fa fa-check"></i><b>25.6.1</b> Point-to-set Maps</a></li>
<li class="chapter" data-level="25.6.2" data-path="mathadd.html"><a href="mathadd.html#zangwill"><i class="fa fa-check"></i><b>25.6.2</b> Zangwill’s Theorem</a></li>
<li class="chapter" data-level="25.6.3" data-path="mathadd.html"><a href="mathadd.html#ostrowski"><i class="fa fa-check"></i><b>25.6.3</b> Ostrowski’s Theorem</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="mathadd.html"><a href="mathadd.html#mathls"><i class="fa fa-check"></i><b>25.7</b> Least Squares</a>
<ul>
<li class="chapter" data-level="25.7.1" data-path="mathadd.html"><a href="mathadd.html#mathquprog"><i class="fa fa-check"></i><b>25.7.1</b> Quadratic Programming</a></li>
</ul></li>
<li class="chapter" data-level="25.8" data-path="mathadd.html"><a href="mathadd.html#mathpenal"><i class="fa fa-check"></i><b>25.8</b> Quadratic penalties</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="apcode.html"><a href="apcode.html"><i class="fa fa-check"></i><b>A</b> Code</a>
<ul>
<li class="chapter" data-level="A.1" data-path="apcode.html"><a href="apcode.html#rapcode"><i class="fa fa-check"></i><b>A.1</b> R Code</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="apcode.html"><a href="apcode.html#aputilitiescode"><i class="fa fa-check"></i><b>A.1.1</b> utilities.R</a></li>
<li class="chapter" data-level="A.1.2" data-path="apcode.html"><a href="apcode.html#apindexingcode"><i class="fa fa-check"></i><b>A.1.2</b> commom/indexing.r</a></li>
<li class="chapter" data-level="A.1.3" data-path="apcode.html"><a href="apcode.html#apiocode"><i class="fa fa-check"></i><b>A.1.3</b> commom/io.r</a></li>
<li class="chapter" data-level="A.1.4" data-path="apcode.html"><a href="apcode.html#aplinearcode"><i class="fa fa-check"></i><b>A.1.4</b> commom/linear.r</a></li>
<li class="chapter" data-level="A.1.5" data-path="apcode.html"><a href="apcode.html#appermcode"><i class="fa fa-check"></i><b>A.1.5</b> commom/nextPC.r</a></li>
<li class="chapter" data-level="A.1.6" data-path="apcode.html"><a href="apcode.html#apsmacofcode"><i class="fa fa-check"></i><b>A.1.6</b> commom/smacof.r</a></li>
<li class="chapter" data-level="A.1.7" data-path="apcode.html"><a href="apcode.html#apcodeprop"><i class="fa fa-check"></i><b>A.1.7</b> properties.R</a></li>
<li class="chapter" data-level="A.1.8" data-path="apcode.html"><a href="apcode.html#apcodepic"><i class="fa fa-check"></i><b>A.1.8</b> pictures.R</a></li>
<li class="chapter" data-level="A.1.9" data-path="apcode.html"><a href="apcode.html#apcodeclass"><i class="fa fa-check"></i><b>A.1.9</b> classical.R</a></li>
<li class="chapter" data-level="A.1.10" data-path="apcode.html"><a href="apcode.html#apcodeminim"><i class="fa fa-check"></i><b>A.1.10</b> minimization.R</a></li>
<li class="chapter" data-level="A.1.11" data-path="apcode.html"><a href="apcode.html#apcodefull"><i class="fa fa-check"></i><b>A.1.11</b> full.R</a></li>
<li class="chapter" data-level="A.1.12" data-path="apcode.html"><a href="apcode.html#apcodeunfold"><i class="fa fa-check"></i><b>A.1.12</b> unfolding.R</a></li>
<li class="chapter" data-level="A.1.13" data-path="apcode.html"><a href="apcode.html#apcodencons"><i class="fa fa-check"></i><b>A.1.13</b> constrained.R</a></li>
<li class="chapter" data-level="A.1.14" data-path="apcode.html"><a href="apcode.html#apcodenominal"><i class="fa fa-check"></i><b>A.1.14</b> nominal.R</a></li>
<li class="chapter" data-level="A.1.15" data-path="apcode.html"><a href="apcode.html#apcodesstress"><i class="fa fa-check"></i><b>A.1.15</b> sstress.R</a></li>
<li class="chapter" data-level="A.1.16" data-path="apcode.html"><a href="apcode.html#apcodeinverse"><i class="fa fa-check"></i><b>A.1.16</b> inverse.R</a></li>
<li class="chapter" data-level="A.1.17" data-path="apcode.html"><a href="apcode.html#apcodeglobal"><i class="fa fa-check"></i><b>A.1.17</b> global.R</a></li>
<li class="chapter" data-level="A.1.18" data-path="apcode.html"><a href="apcode.html#apcodemathadd"><i class="fa fa-check"></i><b>A.1.18</b> mathadd.R</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="apcode.html"><a href="apcode.html#c-code"><i class="fa fa-check"></i><b>A.2</b> C code</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="apcode.html"><a href="apcode.html#deboor.c"><i class="fa fa-check"></i><b>A.2.1</b> deboor.c</a></li>
<li class="chapter" data-level="A.2.2" data-path="apcode.html"><a href="apcode.html#cleanup.c"><i class="fa fa-check"></i><b>A.2.2</b> cleanup.c</a></li>
<li class="chapter" data-level="A.2.3" data-path="apcode.html"><a href="apcode.html#jacobi.c"><i class="fa fa-check"></i><b>A.2.3</b> jacobi.c</a></li>
<li class="chapter" data-level="A.2.4" data-path="apcode.html"><a href="apcode.html#jbkties.c"><i class="fa fa-check"></i><b>A.2.4</b> jbkTies.c</a></li>
<li class="chapter" data-level="A.2.5" data-path="apcode.html"><a href="apcode.html#matrix.c"><i class="fa fa-check"></i><b>A.2.5</b> matrix.c</a></li>
<li class="chapter" data-level="A.2.6" data-path="apcode.html"><a href="apcode.html#jeffrey.c"><i class="fa fa-check"></i><b>A.2.6</b> jeffrey.c</a></li>
<li class="chapter" data-level="A.2.7" data-path="apcode.html"><a href="apcode.html#mysort.c"><i class="fa fa-check"></i><b>A.2.7</b> mySort.c</a></li>
<li class="chapter" data-level="A.2.8" data-path="apcode.html"><a href="apcode.html#nextpc.c"><i class="fa fa-check"></i><b>A.2.8</b> nextPC.c</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="apdatasets.html"><a href="apdatasets.html"><i class="fa fa-check"></i><b>B</b> Data</a>
<ul>
<li class="chapter" data-level="B.1" data-path="apdatasets.html"><a href="apdatasets.html#apdatadsmall"><i class="fa fa-check"></i><b>B.1</b> Small</a></li>
<li class="chapter" data-level="B.2" data-path="apdatasets.html"><a href="apdatasets.html#apdatagruijter"><i class="fa fa-check"></i><b>B.2</b> De Gruijter</a></li>
<li class="chapter" data-level="B.3" data-path="apdatasets.html"><a href="apdatasets.html#apdataekman"><i class="fa fa-check"></i><b>B.3</b> Ekman</a></li>
<li class="chapter" data-level="B.4" data-path="apdatasets.html"><a href="apdatasets.html#apdataveg"><i class="fa fa-check"></i><b>B.4</b> Vegetables</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="apunlicense.html"><a href="apunlicense.html"><i class="fa fa-check"></i><b>C</b> Unlicense</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Least Squares Euclidean Multidimensional Scaling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intinterval" class="section level1" number="9">
<h1><span class="header-section-number">9</span> Interval MDS</h1>
<p>intro: additive vs interval
basic vs ratio</p>
<div id="intadditive" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> The Additive Constant</h2>
<p>In the early history of MDS dissimilarities were computed from comparative judgments in the
Thurstonian tradition.</p>
<p>triads paired comparisons etc positive orthant</p>
<p>These early techniques only gave numbers on an interval scale, i.e. dissimilarities known only up to a linear transformation. In order to get positive dissimilarities a rational origin needed to be found in some way. This is the <em>additive constant problem</em>. It can be seen as the first example of nonmetric MDS, in which we have only partially known dissimilarities.</p>
<p><span class="math display" id="eq:twoadd">\[\begin{align}
\begin{split}
(\delta_{ij}+\alpha)&amp;\approx d_{ij}(X),\\
\delta_{ij}&amp;\approx d_{ij}(X)+\alpha.
\end{split}
\tag{9.1}
\end{align}\]</span></p>
<p>The additive constant techniques were more important in the fifties and sixties than they are these days, because they have largely been replaced by iterative nonmetric MDS techniques.</p>
<p>An early algorithm to fit the additive constant based on Schoenberg’s
theorem was given by <span class="citation"><a href="#ref-messick_abelson_56" role="doc-biblioref">Messick and Abelson</a> (<a href="#ref-messick_abelson_56" role="doc-biblioref">1956</a>)</span>. Torgerson based, i.e. the eigenvalues of <span class="math inline">\(\tau(\Delta^{(2)})\)</span>. It was a somewhat hopeful iterative technique, without a convergence proof, designed to make the sum of the <span class="math inline">\(n-p\)</span> smallest eigenvalues equal to zero. This is of course only a necessary condition for best approximation, not a sufficient one.</p>
<p>In addition, the Messick-Abelson algorithm sometimes yielded solutions
in which the Torgerson transform of the squared dissimilarities had
negative eigenvalues, which could even be quite large. That is also
somewhat of a problem. Consequently <span class="citation"><a href="#ref-cooper_72" role="doc-biblioref">Cooper</a> (<a href="#ref-cooper_72" role="doc-biblioref">1972</a>)</span> proposed an
alternative additive constant algorithm, taking his clue from the work
of Kruskal.</p>
<p>The solution was to redefine stress as a function of both the
configuration and the additive constant. Thus</p>
<p><span class="math display" id="eq:nmcooper1">\[\begin{equation}
\sigma(X,\alpha):=\mathop{\sum\sum}_{1\leq j&lt;i\leq n}w_{ij}(\delta_{ij}+\alpha-d_{ij}(X))^2,
\tag{9.2}
\end{equation}\]</span></p>
<p>and we minimize this stress over both <span class="math inline">\(X\)</span> and <span class="math inline">\(\alpha\)</span>.</p>
<p>Double phase (ALS)</p>
<p><span class="math inline">\(\delta_{ij}+\alpha\geq 0\)</span></p>
<p>Single Phase</p>
<p><span class="math display" id="eq:nmcooper2">\[\begin{equation}
\sigma(X):=\min_\alpha\mathop{\sum\sum}_{1\leq j&lt;i\leq n}w_{ij}(\delta_{ij}+\alpha-d_{ij}(X))^2,
\tag{9.3}
\end{equation}\]</span></p>
<div id="exactad" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Algebra</h3>
<p>The additive constant problem is to find
<span class="math inline">\(X\in\mathbb{R}^{n\times p}\)</span> and <span class="math inline">\(\alpha\)</span> such that
<span class="math inline">\(\Delta+\alpha(E-I)\approx D(X)\)</span>. In this section we look for
all <span class="math inline">\(\alpha\)</span> such that <span class="math inline">\(\Delta+\alpha(E-I)\)</span> is Euclidean, i.e.
such that there is a configuration <span class="math inline">\(X\)</span> with <span class="math inline">\(\Delta+\alpha(E-I)=D(X)\)</span>.
This is a one-parameter generalization of Schoenberg’s theorem.</p>
<p>It makes sense to require <span class="math inline">\(\alpha\geq 0\)</span>, because a negative
<span class="math inline">\(\alpha\)</span> would more appropriately be called a subtractive constant.
Also, we may want to make sure that the off-diagonal elements of <span class="math inline">\(\Delta+\alpha(E-I)\)</span> are non-negative, i.e. that <span class="math inline">\(\alpha\geq-\delta_{ij}\)</span> for all <span class="math inline">\(i&gt;j\)</span>. Note that if we allow a negative <span class="math inline">\(\alpha\)</span> then if all off-diagonal <span class="math inline">\(\delta_{ij}\)</span> are equal, say to <span class="math inline">\(\delta&gt;0\)</span>, we have the trivial solution <span class="math inline">\(\alpha=-\delta\)</span> and <span class="math inline">\(X=0\)</span>.</p>
<p>We start with a simple construction.</p>

<div class="theorem">
<span id="thm:nmn1" class="theorem"><strong>Theorem 9.1  </strong></span>For all <span class="math inline">\(\Delta\)</span> there is an <span class="math inline">\(\alpha_0\geq 0\)</span> such that for all <span class="math inline">\(\alpha\geq\alpha_0\)</span> we have <span class="math inline">\(\Delta+\alpha(E-I))\)</span> Euclidean of dimension <span class="math inline">\(r\leq n-1\)</span>.
</div>

<div class="proof">
<p>\iffalse{} <span class="proof"><em>Proof. </em></span> We have, using <span class="math inline">\(\Delta\times(E-I)=\Delta\)</span> and <span class="math inline">\((E-I)\times(E-I)=E-I\)</span>,</p>
<p><span class="math display" id="eq:tau1">\[\begin{equation}
  \tau((\Delta+\alpha(E-I))\times(\Delta+\alpha(E-I)))=
  \tau(\Delta\times\Delta)+2\alpha\tau(\Delta)+\frac12\alpha^2J.
\tag{9.4}
\end{equation}\]</span></p>
Thus each off-diagonal element is a concave quadratic in <span class="math inline">\(\alpha\)</span>, which
is negative for <span class="math inline">\(\alpha\)</span> big enough. Choose <span class="math inline">\(\alpha_0\geq 0\)</span> to make all
off-diagonal elements negative (and all dissimilarities non-negative). A doubly-centered matrix with all off-diagonal elements negative is positive semi-definite of rank <span class="math inline">\(n-1\)</span> (<span class="citation"><a href="#ref-taussky_49" role="doc-biblioref">Taussky</a> (<a href="#ref-taussky_49" role="doc-biblioref">1949</a>)</span>).
</div>
<p>Note that by the same argument we can also find a negative <span class="math inline">\(\alpha_0\)</span> that makes all off-diagonal elements negative and thus <span class="math inline">\(\Delta+\alpha(E-I))\)</span> is again Euclidean of dimension <span class="math inline">\(r\leq n-1\)</span>. But this <span class="math inline">\(\alpha_0\)</span> will usually result in negative dissimilarities.</p>
<p>Theorem <a href="intinterval.html#thm:nmn1">9.1</a> can be sharpened for non-Euclidean <span class="math inline">\(\Delta\)</span>.
Define the following function of <span class="math inline">\(\alpha\)</span>:</p>
<p><span class="math display" id="eq:lambdas">\[\begin{equation}
\lambda_\star(\alpha):=\min_{x&#39;x=1, x&#39;e=0}x&#39;\{\tau(\Delta\times\Delta)+2\alpha\tau(\Delta)+\frac12\alpha^2J\}x.
\tag{9.5}
\end{equation}\]</span></p>
<p>This is the smallest non-trivial eigenvalue of the Torgerson transform in
<a href="intinterval.html#eq:tau1">(9.4)</a>. The matrix <span class="math inline">\(\Delta+\alpha(E-I)\)</span> is Euclidean if and only if <span class="math inline">\(\lambda_\star(\alpha)\geq 0\)</span>. Note that <span class="math inline">\(\lambda_\star\)</span> is continuous, by a simple special case of the Maximum Theorem (<span class="citation"><a href="#ref-berge_63" role="doc-biblioref">Berge</a> (<a href="#ref-berge_63" role="doc-biblioref">1963</a>)</span>, Chapter VI, section 3), and coercive, i.e. <span class="math inline">\(\lambda_\star(\alpha)\rightarrow +\infty\)</span> if <span class="math inline">\(|\alpha|\rightarrow +\infty\)</span>.</p>

<div class="theorem">
<span id="thm:nmn2" class="theorem"><strong>Theorem 9.2  </strong></span>For all non-Euclidean <span class="math inline">\(\Delta\)</span> there is an <span class="math inline">\(\alpha_1&gt;0\)</span> such that for all <span class="math inline">\(\alpha\geq\alpha_1\)</span> we have that <span class="math inline">\(\Delta+\alpha(E-I))\)</span> Euclidean of dimension <span class="math inline">\(r\leq n-2\)</span>.
</div>

<div class="proof">
\iffalse{} <span class="proof"><em>Proof. </em></span> Because <span class="math inline">\(\Delta\)</span> is non-Euclidean we have <span class="math inline">\(\lambda_\star(0)&lt;0\)</span>. By the construction in theorem <a href="intinterval.html#thm:nmn1">9.1</a> there is an <span class="math inline">\(\alpha_0\)</span> such that
<span class="math inline">\(\lambda_\star(\alpha)&gt;0\)</span> for all <span class="math inline">\(\alpha&gt;\alpha_0\)</span>. By the Maximum Theorem
the function <span class="math inline">\(\lambda_\star\)</span> is continuous, and thus, by Bolzano’s theorem, there is an <span class="math inline">\(\alpha_1\)</span> between <span class="math inline">\(0\)</span> and <span class="math inline">\(\alpha_0\)</span> such that <span class="math inline">\(\lambda_\star(\alpha_1)=0\)</span>. If there is more than one zero between
<span class="math inline">\(0\)</span> and <span class="math inline">\(\alpha_0\)</span> we take the largest one as <span class="math inline">\(\alpha_1\)</span>.
</div>
<p>The problem with extending theorem <a href="intinterval.html#thm:nmn2">9.2</a> to Euclidean <span class="math inline">\(\Delta\)</span> is that the equation <span class="math inline">\(\lambda_\star(\alpha)=0\)</span> may have only negative roots, or, even more seriously, no roots at all. This may not be too important from the practical point of view, because observed dissimilarities will usually not be exactly Euclidean. Nevertheless I feel compelled to address it.</p>

<div class="theorem">
<span id="thm:nmn3" class="theorem"><strong>Theorem 9.3  </strong></span>If <span class="math inline">\(\Delta\)</span> is Euclidean then <span class="math inline">\(\lambda_\star(\alpha)\)</span> is non-negative and non-decreasing on <span class="math inline">\([0,+\infty)\)</span>.
</div>

<div class="proof">
\iffalse{} <span class="proof"><em>Proof. </em></span> If <span class="math inline">\(\Delta\)</span> is Euclidean, then <span class="math inline">\(\sqrt{\Delta}\)</span>, which is short for the matrix with the square roots of the dissimilarities, is Euclidean as well. This follows because the square root is a Schoenberg transform (<span class="citation"><a href="#ref-schoenberg_37" role="doc-biblioref">Schoenberg</a> (<a href="#ref-schoenberg_37" role="doc-biblioref">1937</a>)</span>, <span class="citation"><a href="#ref-bavaud_11" role="doc-biblioref">Bavaud</a> (<a href="#ref-bavaud_11" role="doc-biblioref">2011</a>)</span>), and it implies that <span class="math inline">\(\tau(\Delta)=\tau(\sqrt{\Delta}\times\sqrt{\Delta})\)</span> is positive semi-definite. Thus the matrix <a href="intinterval.html#eq:tau1">(9.4)</a> is positive semi-definite for all <span class="math inline">\(\alpha\geq 0\)</span>. By Danskin’s Theorem the one-sided directional derivative of <span class="math inline">\(\lambda_\star\)</span> at <span class="math inline">\(\alpha\)</span> is <span class="math inline">\(2x(\alpha)&#39;\tau(\Delta)x(\alpha)+\alpha\)</span>, where <span class="math inline">\(x(\alpha)\)</span> is one of the minimizing eigenvectors. Because the one-sided derivative is non-negative, the function is non-decreasing (in fact increasing if <span class="math inline">\(\alpha&gt;0\)</span>).
</div>
<p>Of course <span class="math inline">\(\lambda_\star(\alpha)=0\)</span> can still have negative solutions, and in particular it will have at least one negative solution if <span class="math inline">\(\lambda_\star(\alpha)\leq 0\)</span> for any <span class="math inline">\(\alpha\)</span>. There can even be negative solutions with <span class="math inline">\(\Delta+\alpha(E-I)\)</span> non-negative.</p>
<p>The solutions of <span class="math inline">\(\lambda_\star(\alpha)=0\)</span> can be computed and studied in more detail, using results first presented in the psychometric literature by <span class="citation"><a href="#ref-cailliez_83" role="doc-biblioref">Cailliez</a> (<a href="#ref-cailliez_83" role="doc-biblioref">1983</a>)</span>. We reproduce his analysis here, with a somewhat different discussion that relies more on existing mathematical results.</p>
<p>In order to find the smallest <span class="math inline">\(\alpha\)</span> we solve the quadratic eigenvalue problem (<span class="citation"><a href="#ref-tisseur_meerbergen_01" role="doc-biblioref">Tisseur and Meerbergen</a> (<a href="#ref-tisseur_meerbergen_01" role="doc-biblioref">2001</a>)</span>)</p>
<p><span class="math display" id="eq:qep1">\[\begin{equation}
\{\tau(\Delta\times\Delta)+2\alpha\tau(\Delta)+\frac12\alpha^2J\}y=0.
\tag{9.6}
\end{equation}\]</span></p>
<p>A solution <span class="math inline">\((y,\alpha)\)</span> of #ref(eq:qep1) is an eigen pair, in which <span class="math inline">\(y\)</span> is an eigenvector, and <span class="math inline">\(\alpha\)</span> the corresponding eigenvalue. The trivial solution <span class="math inline">\(y=e\)</span> satisfies #ref(eq:qep1) for any <span class="math inline">\(\alpha\)</span>. We are not really interested in the non-trivial eigenvectors here, but we will look at the relationship between the eigenvalues and the solutions of <span class="math inline">\(\lambda_\star(\alpha)=0\)</span>.</p>
<p>The eigenvalues can be complex, in which case they do not interest us.
If <span class="math inline">\(\alpha\)</span> is a non-trivial real eigenvalue, then the rank of the Torgerson transform of the matrix in #ref(eq:qep1) is <span class="math inline">\(n-2\)</span>, but</p>
<p>To get rid of the annoying trivial solution <span class="math inline">\(y=e\)</span> we use a square
orthonormal matrix whose first column is proportional to <span class="math inline">\(e\)</span>. Suppose
<span class="math inline">\(L\)</span> contains the remaining <span class="math inline">\(n-1\)</span> columns. Now solve</p>
<p><span class="math display" id="eq:qep2">\[\begin{equation}
\{L&#39;\tau(\Delta\times\Delta)L+2\alpha L&#39;\tau(\Delta)L+\frac12\alpha^2I\}y=0.
\tag{9.7}
\end{equation}\]</span></p>
<p>Note that the determinant of the polynomial matrix in <a href="intinterval.html#eq:qep2">(9.7)</a> is
a polynomial of degree <span class="math inline">\(2(n-1)\)</span> in <span class="math inline">\(\alpha\)</span>, which has <span class="math inline">\(2(n-1)\)</span> real or
complex roots.</p>
<p>The next step is linearization (<span class="citation"><a href="#ref-gohberg_lancaster_rodman_09" role="doc-biblioref">Gohberg, Lancaster, and Rodman</a> (<a href="#ref-gohberg_lancaster_rodman_09" role="doc-biblioref">2009</a>)</span>, chapter
1), which means finding a linear or generalized linear eigen problem with the
same roots as <a href="intinterval.html#eq:qep2">(9.7)</a>. In our case this is the eigenvalue problem for the matrix</p>
<p><span class="math display" id="eq:qep3">\[\begin{equation}
\begin{bmatrix}
\hfill 0&amp;\hfill I\\
-2L&#39;\tau(\Delta\times\Delta)L&amp;-4L&#39;\tau(\Delta)L
\end{bmatrix}
\tag{9.8}
\end{equation}\]</span></p>
</div>
<div id="examples" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Examples</h3>
<div id="small-example" class="section level4" number="9.1.2.1">
<h4><span class="header-section-number">9.1.2.1</span> Small Example</h4>
<p>Here is a small artificial dissimilarity matrix.</p>
<pre><code>##   1  2  3  4 
## 1 +0 +1 +2 +5
## 2 +1 +0 +4 +2
## 3 +2 +4 +0 +1
## 4 +5 +2 +1 +0</code></pre>
<p>It is constructed such that <span class="math inline">\(\delta_{14}&gt;\delta_{12}+\delta_{24}\)</span> and
that <span class="math inline">\(\delta_{23}&gt;\delta_{21}+\delta_{13}\)</span>. Because the triangle
inequality is violated the dissimilarities are not distances in any
metric space, and certainly not in a Euclidean one. Because the minimum
dissimilarity is <span class="math inline">\(+1\)</span>, we require that the additive constant <span class="math inline">\(\alpha\)</span> is
at least <span class="math inline">\(-1\)</span>.</p>
<p>The R function treq() in appendix <a href="apcode.html#apcodeclass">A.1.9</a> finds the smallest
additive constant such that all triangle inequalities are satisfied. For
this example it is <span class="math inline">\(\alpha=2\)</span>.</p>
<p>The Torgerson transform of <span class="math inline">\(\Delta\times\Delta\)</span> is</p>
<pre><code>##   1      2      3      4     
## 1 +4.312 +2.688 +1.188 -8.188
## 2 +2.688 +2.062 -5.938 +1.188
## 3 +1.188 -5.938 +2.062 +2.688
## 4 -8.188 +1.188 +2.688 +4.312</code></pre>
<p>with eigenvalues</p>
<pre><code>## [1] +12.954 +7.546  +0.000  -7.750</code></pre>
<p>The smallest eigenvalue -7.75 is appropriately negative, and
theorem <a href="intinterval.html#thm:nmn2">9.2</a> shows that <span class="math inline">\(\Delta\times\Delta+7.75(E-I)\)</span>
are squared distances between four points in the plane.</p>
<p>The upper bound for the smallest <span class="math inline">\(\alpha\)</span> from theorem <a href="intinterval.html#thm:nmn1">9.1</a>,
computed by the R function acbound(), is 9.309475.</p>
<p>It is useful to look at a graphical representation of the minimum
non-trivial eigenvalue of
<span class="math inline">\(\tau((\Delta+\alpha(E-I))\times(\Delta+\alpha(E-I)))\)</span> as a function of
<span class="math inline">\(\alpha\)</span>. The R function aceval() generates the data for the plot.</p>
<p><img src="_main_files/figure-html/acplot-1.png" width="672" /></p>
<p>We see that the minimum non-trivial eigenvalue is a continuous function of <span class="math inline">\(\alpha\)</span>,but one which certainly is not convex or concave or differentiable. The graph crosses the horizontal axes near -8, -3, and +6.</p>
<p>To make this precise we apply the theory of section xxx. The R function
acqep() finds the six non-trivial eigenvalues</p>
<pre><code>## [1] -8.192582+0.000000i  5.713075+0.000000i -3.500000+2.179449i
## [4] -3.500000-2.179449i -2.807418+0.000000i -2.713075+0.000000i</code></pre>
<p>Two of the eigenvalues are complex conjugates, four are real. Of the
real eigenvalues three are negative, and only one is positive, equal to
+5.713.
The table above gives the eigenvalues of the Torgerson transform, using
all four real eigenvalues for <span class="math inline">\(\alpha\)</span>. The three negative ones do result in a positive semi-definite matrix with rank equal to <span class="math inline">\(n-2\)</span>, but they also
create negative dissimilarities.</p>
<pre><code>##  -8.193  ******  +38.098 +13.885  +0.000  -0.000 
##  +5.713  ******  +61.116 +43.441  +0.000  -0.000 
##  -2.807  ******   +3.115  +0.402  -0.000  -0.000 
##  -2.713  ******   +3.228  +0.215  +0.000  +0.000</code></pre>
</div>
<div id="de-gruijter-example" class="section level4" number="9.1.2.2">
<h4><span class="header-section-number">9.1.2.2</span> De Gruijter Example</h4>
<p><img src="_main_files/figure-html/gruadd-1.png" width="672" /></p>
<pre><code>##  [1] -20.527411+0.000000i -10.174103+0.000000i  -9.472504+0.000000i
##  [4]  -6.622263+0.352619i  -6.622263-0.352619i  -5.885691+0.287544i
##  [7]  -5.885691-0.287544i  -5.640580+0.366889i  -5.640580-0.366889i
## [10]  -4.391289+0.253248i  -4.391289-0.253248i  -3.708911+0.386844i
## [13]  -3.708911-0.386844i  -3.238930+0.000000i  -2.311379+0.000000i
## [16]  -1.369315+0.000000i</code></pre>
</div>
<div id="ekman-example" class="section level4" number="9.1.2.3">
<h4><span class="header-section-number">9.1.2.3</span> Ekman Example</h4>
<p><img src="_main_files/figure-html/ekkadd-1.png" width="672" /></p>
<pre><code>##  [1] -5.713009655+0.0000000i -3.782729083+0.0000000i -1.791313475+0.0000000i
##  [4] -1.628964140+0.0000000i -0.976213035+0.0000000i -0.744289350+0.0495939i
##  [7] -0.744289350-0.0495939i -0.682321433+0.0000000i -0.534849034+0.0000000i
## [10] -0.513033529+0.0000000i -0.497908376+0.0248145i -0.497908376-0.0248145i
## [13] -0.372321687+0.1313892i -0.372321687-0.1313892i -0.388308013+0.0000000i
## [16] -0.229813135+0.1825985i -0.229813135-0.1825985i -0.286712033+0.0000000i
## [19] -0.212601059+0.1185199i -0.212601059-0.1185199i  0.206312577+0.0000000i
## [22] -0.194299448+0.0000000i  0.132767430+0.0000000i -0.079646956+0.0000000i
## [25] -0.024193535+0.0000000i -0.006762279+0.0000000i</code></pre>
<p><img src="_main_files/figure-html/ekk3add-1.png" width="672" /></p>
<pre><code>##  [1] -7.9740652+0.0000000i -4.8679294+0.0000000i -1.2242342+0.0000000i
##  [4] -0.9822376+0.0000000i  0.7856448+0.0000000i  0.6486775+0.0000000i
##  [7] -0.5540332+0.0000000i -0.5426006+0.0129703i -0.5426006-0.0129703i
## [10]  0.4864182+0.0000000i -0.1118921+0.3923586i -0.1118921-0.3923586i
## [13]  0.3829746+0.0000000i  0.3530897+0.0000000i -0.3516103+0.0000000i
## [16] -0.3073607+0.0000000i -0.1265941+0.2630789i -0.1265941-0.2630789i
## [19] -0.0735448+0.2698631i -0.0735448-0.2698631i -0.2333027+0.0000000i
## [22] -0.0081376+0.1948006i -0.0081376-0.1948006i -0.1380254+0.1175071i
## [25] -0.1380254-0.1175071i  0.1205026+0.0000000i</code></pre>
</div>
</div>
<div id="variation" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> A Variation</h3>
<p>Alternatively, we could define our approximation problem as finding
<span class="math inline">\(X\in\mathbb{R}^{n\times p}\)</span> and <span class="math inline">\(\alpha\)</span> such that
<span class="math inline">\(\sqrt{\delta_{ij}^2+\alpha}\approx d_{ij}(X)\)</span>, or, equivalently,
<span class="math inline">\(\Delta\times\Delta+\alpha(E-I)\approx D(X)\times D(X)\)</span>.</p>

<div class="theorem">
<span id="thm:nmn4" class="theorem"><strong>Theorem 9.4  </strong></span>For any <span class="math inline">\(X\in\mathbb{R}^{n\times p}\)</span> with <span class="math inline">\(p=n-2\)</span> there is an <span class="math inline">\(\alpha\)</span>
such that <span class="math inline">\(\sqrt{\delta_{ij}^2+\alpha}= d_{ij}(X)\)</span>.
</div>

<div class="proof">
<p>\iffalse{} <span class="proof"><em>Proof. </em></span> Now we have</p>
<p><span class="math display" id="eq:tau2">\[\begin{equation}
\tau(\Delta\times\Delta+\alpha(E-I)))=
  \tau(\Delta\times\Delta)+\frac12\alpha J.
\tag{9.9}
\end{equation}\]</span></p>
The eigenvalues of
<span class="math inline">\(\tau(\Delta\times\Delta)+\frac12\alpha J\)</span> are zero and
<span class="math inline">\(\lambda_s+\frac12\alpha\)</span>, where the <span class="math inline">\(\lambda_s\)</span> are the <span class="math inline">\(n-1\)</span>
non-trivial eigenvalues of <span class="math inline">\(\tau(\Delta\times\Delta)\)</span>. If
<span class="math inline">\(\underline{\lambda}\)</span> is smallest eigenvalue we choose
<span class="math inline">\(\alpha=-2\underline{\lambda}\)</span>, and
<span class="math inline">\(\tau(\Delta\times\Delta)+\frac12\alpha J\)</span> is positive semi-definite of
rank <span class="math inline">\(r\leq n-2\)</span>.
</div>
<p>Note that theorem <a href="intinterval.html#thm:nmn2">9.2</a> implies that for any <span class="math inline">\(\Delta\)</span> there is
a strictly increasing differentiable transformation to the space of
Euclidean distance matrices in <span class="math inline">\(n-2\)</span> dimensions. This is a version of
what is sometimes described as <em>Guttman’s n-2 theorem</em> (<span class="citation"><a href="#ref-lingoes_71" role="doc-biblioref">Lingoes</a> (<a href="#ref-lingoes_71" role="doc-biblioref">1971</a>)</span>).
The proof we have given is that from <span class="citation"><a href="#ref-deleeuw_R_70b" role="doc-biblioref">De Leeuw</a> (<a href="#ref-deleeuw_R_70b" role="doc-biblioref">1970</a>)</span>, Appendix B.</p>
<p>ALS Negative delta</p>
<p>Euclidean
<span class="math display">\[
\sqrt{2-2\ \cos |i-j|\theta}
\]</span>
Circular
<span class="math display">\[
|i-j|\frac{2\pi}{n}
\]</span>
Linear
<span class="math display">\[
|i-j|
\]</span>
<img src="_main_files/figure-html/breakcircle1-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><img src="_main_files/figure-html/breakcircle2-1.png" width="672" style="display: block; margin: auto;" /></p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bavaud_11" class="csl-entry">
Bavaud, F. 2011. <span>“<span class="nocase">On the Schoenberg Transformations in Data Analysis: Theory and Illustrations</span>.”</span> <em>Journal of Classification</em> 28: 297–314.
</div>
<div id="ref-berge_63" class="csl-entry">
Berge, C. 1963. <em>Topological Spaces</em>. Oliver &amp; Boyd.
</div>
<div id="ref-cailliez_83" class="csl-entry">
Cailliez, F. 1983. <span>“<span class="nocase">The Analytical Solutyion to the Additive Constant Problem</span>.”</span> <em>Psychometrika</em> 48 (2): 305–8.
</div>
<div id="ref-cooper_72" class="csl-entry">
Cooper, L. G. 1972. <span>“<span class="nocase">A New Solution to the Additive Constant Problem in Metric Multidimensional Scaling</span>.”</span> <em>Psychometrika</em> 37 (3): 311–22.
</div>
<div id="ref-deleeuw_R_70b" class="csl-entry">
———. 1970. <span>“<span>The Euclidean Distance Model</span>.”</span> Research Note 002-70. Department of Data Theory FSW/RUL. <a href="http://deleeuwpdx.net/janspubs/1970/reports/deleeuw_R_70b.pdf">http://deleeuwpdx.net/janspubs/1970/reports/deleeuw_R_70b.pdf</a>.
</div>
<div id="ref-gohberg_lancaster_rodman_09" class="csl-entry">
Gohberg, I., P. Lancaster, and L. Rodman. 2009. <em>Matrix Polynomials</em>. Classic in Applied Mathematics. SIAM.
</div>
<div id="ref-lingoes_71" class="csl-entry">
———. 1971. <span>“<span class="nocase">Some Boundary Conditions for a Monotone Analysis of Symmetric Matrices</span>.”</span> <em>Psychometrika</em> 36 (2): 195–203.
</div>
<div id="ref-messick_abelson_56" class="csl-entry">
Messick, S. J., and R. P. Abelson. 1956. <span>“<span class="nocase">The Additive Constant Problem in Multidimensional Scaling</span>.”</span> <em>Psychometrika</em> 21 (1–17).
</div>
<div id="ref-schoenberg_37" class="csl-entry">
———. 1937. <span>“<span class="nocase">On Certain Metric Spaces Arising From Euclidean Spaces by a Change of Metric and Their Imbedding in Hilbert Space</span>.”</span> <em>Annals of Mathematics</em> 38 (4): 787–93.
</div>
<div id="ref-taussky_49" class="csl-entry">
Taussky, O. 1949. <span>“<span class="nocase">A Recurring Theorem on Determinants</span>.”</span> <em>American Mathematical Monthly</em> 56: 672–76.
</div>
<div id="ref-tisseur_meerbergen_01" class="csl-entry">
Tisseur, F., and K. Meerbergen. 2001. <span>“<span>The Quadratic Eigenvalue Problem</span>.”</span> <em><span>SIAM</span> Review</em> 43 (2): 235–86.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="nonmtrmds.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="polynomial-and-splinical-mds.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "none"
},
"keep_md": true,
"toolbar": {
"position": "fixed"
},
"toc_depth": 5
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
