<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>22 Inverse Multidimensional Scaling | Least Squares Euclidean Multidimensional Scaling</title>
  <meta name="description" content="null" />
  <meta name="generator" content="bookdown 0.22.3 and GitBook 2.6.7" />

  <meta property="og:title" content="22 Inverse Multidimensional Scaling | Least Squares Euclidean Multidimensional Scaling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="null" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="22 Inverse Multidimensional Scaling | Least Squares Euclidean Multidimensional Scaling" />
  
  <meta name="twitter:description" content="null" />
  

<meta name="author" content="Jan de Leeuw" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="alternative-least-squares-loss.html"/>
<link rel="next" href="stability.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#introhist"><i class="fa fa-check"></i><b>1.1</b> Brief History</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#milestones"><i class="fa fa-check"></i><b>1.1.1</b> Milestones</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#introbasic"><i class="fa fa-check"></i><b>1.2</b> Basic MDS</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#kruskals-stress"><i class="fa fa-check"></i><b>1.2.1</b> Kruskal’s stress</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#datasym"><i class="fa fa-check"></i><b>1.2.2</b> Data Asymmetry</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#local-and-global"><i class="fa fa-check"></i><b>1.2.3</b> Local and Global</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#introgeneralize"><i class="fa fa-check"></i><b>1.3</b> Generalizations</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#gennonmetric"><i class="fa fa-check"></i><b>1.3.1</b> Non-metric MDS</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#genfstress"><i class="fa fa-check"></i><b>1.3.2</b> fstress</a></li>
<li class="chapter" data-level="1.3.3" data-path="intro.html"><a href="intro.html#gencons"><i class="fa fa-check"></i><b>1.3.3</b> Constraints</a></li>
<li class="chapter" data-level="1.3.4" data-path="intro.html"><a href="intro.html#inreplic"><i class="fa fa-check"></i><b>1.3.4</b> Replications</a></li>
<li class="chapter" data-level="1.3.5" data-path="intro.html"><a href="intro.html#genasym"><i class="fa fa-check"></i><b>1.3.5</b> Distance Asymmetry</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="propchapter.html"><a href="propchapter.html"><i class="fa fa-check"></i><b>2</b> Properties of Stress</a>
<ul>
<li class="chapter" data-level="2.1" data-path="propchapter.html"><a href="propchapter.html#propnotation"><i class="fa fa-check"></i><b>2.1</b> Notation</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="propchapter.html"><a href="propchapter.html#propexpand"><i class="fa fa-check"></i><b>2.1.1</b> Expanding</a></li>
<li class="chapter" data-level="2.1.2" data-path="propchapter.html"><a href="propchapter.html#propmatrix"><i class="fa fa-check"></i><b>2.1.2</b> Matrix Expressions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="propchapter.html"><a href="propchapter.html#propglobal"><i class="fa fa-check"></i><b>2.2</b> Simple Properties</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="propchapter.html"><a href="propchapter.html#propbounded"><i class="fa fa-check"></i><b>2.2.1</b> Boundedness</a></li>
<li class="chapter" data-level="2.2.2" data-path="propchapter.html"><a href="propchapter.html#propinvariance"><i class="fa fa-check"></i><b>2.2.2</b> Invariance</a></li>
<li class="chapter" data-level="2.2.3" data-path="propchapter.html"><a href="propchapter.html#propcontinuity"><i class="fa fa-check"></i><b>2.2.3</b> Continuity</a></li>
<li class="chapter" data-level="2.2.4" data-path="propchapter.html"><a href="propchapter.html#propcoercive"><i class="fa fa-check"></i><b>2.2.4</b> Coercivity</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="propchapter.html"><a href="propchapter.html#propdiff"><i class="fa fa-check"></i><b>2.3</b> Differentiability</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="propchapter.html"><a href="propchapter.html#notation-and-terminology"><i class="fa fa-check"></i><b>2.3.1</b> Notation and Terminology</a></li>
<li class="chapter" data-level="2.3.2" data-path="propchapter.html"><a href="propchapter.html#non-zero-distances"><i class="fa fa-check"></i><b>2.3.2</b> Non-zero Distances</a></li>
<li class="chapter" data-level="2.3.3" data-path="propchapter.html"><a href="propchapter.html#apdirder"><i class="fa fa-check"></i><b>2.3.3</b> Directional Derivatives</a></li>
<li class="chapter" data-level="2.3.4" data-path="propchapter.html"><a href="propchapter.html#squared-distances"><i class="fa fa-check"></i><b>2.3.4</b> Squared Distances</a></li>
<li class="chapter" data-level="2.3.5" data-path="propchapter.html"><a href="propchapter.html#distances"><i class="fa fa-check"></i><b>2.3.5</b> Distances</a></li>
<li class="chapter" data-level="2.3.6" data-path="propchapter.html"><a href="propchapter.html#rho-and-stress"><i class="fa fa-check"></i><b>2.3.6</b> Rho and stress</a></li>
<li class="chapter" data-level="2.3.7" data-path="propchapter.html"><a href="propchapter.html#expansions"><i class="fa fa-check"></i><b>2.3.7</b> Expansions</a></li>
<li class="chapter" data-level="2.3.8" data-path="propchapter.html"><a href="propchapter.html#propdirderivs"><i class="fa fa-check"></i><b>2.3.8</b> Directional Derivatives</a></li>
<li class="chapter" data-level="2.3.9" data-path="propchapter.html"><a href="propchapter.html#propspecexp"><i class="fa fa-check"></i><b>2.3.9</b> Special Expansions</a></li>
<li class="chapter" data-level="2.3.10" data-path="propchapter.html"><a href="propchapter.html#propzerodist"><i class="fa fa-check"></i><b>2.3.10</b> Zero Distance Subspaces</a></li>
<li class="chapter" data-level="2.3.11" data-path="propchapter.html"><a href="propchapter.html#propdistsmo"><i class="fa fa-check"></i><b>2.3.11</b> Distance Smoothing</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="propchapter.html"><a href="propchapter.html#propconvex"><i class="fa fa-check"></i><b>2.4</b> Convexity</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="propchapter.html"><a href="propchapter.html#distances-2"><i class="fa fa-check"></i><b>2.4.1</b> Distances</a></li>
<li class="chapter" data-level="2.4.2" data-path="propchapter.html"><a href="propchapter.html#propdc"><i class="fa fa-check"></i><b>2.4.2</b> DC Functions</a></li>
<li class="chapter" data-level="2.4.3" data-path="propchapter.html"><a href="propchapter.html#subdifferentials"><i class="fa fa-check"></i><b>2.4.3</b> Subdifferentials</a></li>
<li class="chapter" data-level="2.4.4" data-path="propchapter.html"><a href="propchapter.html#propnegdis"><i class="fa fa-check"></i><b>2.4.4</b> Negative Dissimilarities</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="propchapter.html"><a href="propchapter.html#propguttman"><i class="fa fa-check"></i><b>2.5</b> Guttman Transform</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="propchapter.html"><a href="propchapter.html#subdifferentials-1"><i class="fa fa-check"></i><b>2.5.1</b> Subdifferentials</a></li>
<li class="chapter" data-level="2.5.2" data-path="propchapter.html"><a href="propchapter.html#derivative"><i class="fa fa-check"></i><b>2.5.2</b> Derivative</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="propchapter.html"><a href="propchapter.html#propstationary"><i class="fa fa-check"></i><b>2.6</b> Stationary Points</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="propchapter.html"><a href="propchapter.html#local-maxima"><i class="fa fa-check"></i><b>2.6.1</b> Local Maxima</a></li>
<li class="chapter" data-level="2.6.2" data-path="propchapter.html"><a href="propchapter.html#proplocmin"><i class="fa fa-check"></i><b>2.6.2</b> Local Minima</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="propchapter.html"><a href="propchapter.html#propenvelopes"><i class="fa fa-check"></i><b>2.7</b> Stress Envelopes</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="propchapter.html"><a href="propchapter.html#propcsmaj"><i class="fa fa-check"></i><b>2.7.1</b> CS Majorization</a></li>
<li class="chapter" data-level="2.7.2" data-path="propchapter.html"><a href="propchapter.html#propamgmmin"><i class="fa fa-check"></i><b>2.7.2</b> AM/GM Minorization</a></li>
<li class="chapter" data-level="2.7.3" data-path="propchapter.html"><a href="propchapter.html#dualities"><i class="fa fa-check"></i><b>2.7.3</b> Dualities</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="propchapter.html"><a href="propchapter.html#how-large-is-my-stress"><i class="fa fa-check"></i><b>2.8</b> How Large is My Stress ?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="propspaces.html"><a href="propspaces.html"><i class="fa fa-check"></i><b>3</b> Stress Spaces</a>
<ul>
<li class="chapter" data-level="3.1" data-path="propspaces.html"><a href="propspaces.html#propconfspace"><i class="fa fa-check"></i><b>3.1</b> Configuration Space</a></li>
<li class="chapter" data-level="3.2" data-path="propspaces.html"><a href="propspaces.html#propcoefspace"><i class="fa fa-check"></i><b>3.2</b> Coefficient Space</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="propspaces.html"><a href="propspaces.html#on-the-planes"><i class="fa fa-check"></i><b>3.2.1</b> On the Planes</a></li>
<li class="chapter" data-level="3.2.2" data-path="propspaces.html"><a href="propspaces.html#general"><i class="fa fa-check"></i><b>3.2.2</b> General</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="propspaces.html"><a href="propspaces.html#propspherespace"><i class="fa fa-check"></i><b>3.3</b> Spherical Space</a></li>
<li class="chapter" data-level="3.4" data-path="propspaces.html"><a href="propspaces.html#gramian-space"><i class="fa fa-check"></i><b>3.4</b> Gramian Space</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="picsstress.html"><a href="picsstress.html"><i class="fa fa-check"></i><b>4</b> Pictures of Stress</a>
<ul>
<li class="chapter" data-level="4.1" data-path="picsstress.html"><a href="picsstress.html#coefficient-space"><i class="fa fa-check"></i><b>4.1</b> Coefficient Space</a></li>
<li class="chapter" data-level="4.2" data-path="picsstress.html"><a href="picsstress.html#global-perspective"><i class="fa fa-check"></i><b>4.2</b> Global Perspective</a></li>
<li class="chapter" data-level="4.3" data-path="picsstress.html"><a href="picsstress.html#global-contour"><i class="fa fa-check"></i><b>4.3</b> Global Contour</a></li>
<li class="chapter" data-level="4.4" data-path="picsstress.html"><a href="picsstress.html#stationary-points"><i class="fa fa-check"></i><b>4.4</b> Stationary Points</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="picsstress.html"><a href="picsstress.html#first-minimum"><i class="fa fa-check"></i><b>4.4.1</b> First Minimum</a></li>
<li class="chapter" data-level="4.4.2" data-path="picsstress.html"><a href="picsstress.html#second-minimum"><i class="fa fa-check"></i><b>4.4.2</b> Second Minimum</a></li>
<li class="chapter" data-level="4.4.3" data-path="picsstress.html"><a href="picsstress.html#third-minimum"><i class="fa fa-check"></i><b>4.4.3</b> Third Minimum</a></li>
<li class="chapter" data-level="4.4.4" data-path="picsstress.html"><a href="picsstress.html#first-saddle-point"><i class="fa fa-check"></i><b>4.4.4</b> First Saddle Point</a></li>
<li class="chapter" data-level="4.4.5" data-path="picsstress.html"><a href="picsstress.html#second-saddle-point"><i class="fa fa-check"></i><b>4.4.5</b> Second Saddle Point</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="picsstress.html"><a href="picsstress.html#picsphere"><i class="fa fa-check"></i><b>4.5</b> Another Look</a></li>
<li class="chapter" data-level="4.6" data-path="picsstress.html"><a href="picsstress.html#picline"><i class="fa fa-check"></i><b>4.6</b> A Final Look</a></li>
<li class="chapter" data-level="4.7" data-path="picsstress.html"><a href="picsstress.html#discuss"><i class="fa fa-check"></i><b>4.7</b> Discuss</a></li>
<li class="chapter" data-level="4.8" data-path="picsstress.html"><a href="picsstress.html#coordinates"><i class="fa fa-check"></i><b>4.8</b> Coordinates</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html"><i class="fa fa-check"></i><b>5</b> Classical Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#algebra"><i class="fa fa-check"></i><b>5.1</b> Algebra</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#torgerson-transform"><i class="fa fa-check"></i><b>5.1.1</b> Torgerson Transform</a></li>
<li class="chapter" data-level="5.1.2" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#schoenbergs-theorem"><i class="fa fa-check"></i><b>5.1.2</b> Schoenberg’s Theorem</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#approximation"><i class="fa fa-check"></i><b>5.2</b> Approximation</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#low-rank-approximation-of-the-torgersen-transform"><i class="fa fa-check"></i><b>5.2.1</b> Low Rank Approximation of the Torgersen Transform</a></li>
<li class="chapter" data-level="5.2.2" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#minimization-of-strain"><i class="fa fa-check"></i><b>5.2.2</b> Minimization of Strain</a></li>
<li class="chapter" data-level="5.2.3" data-path="classical-multidimensional-scaling.html"><a href="classical-multidimensional-scaling.html#approximation-from-below"><i class="fa fa-check"></i><b>5.2.3</b> Approximation from Below</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="minstr.html"><a href="minstr.html"><i class="fa fa-check"></i><b>6</b> Minimization of Stress</a>
<ul>
<li class="chapter" data-level="6.1" data-path="minstr.html"><a href="minstr.html#gradient-methods"><i class="fa fa-check"></i><b>6.1</b> Gradient Methods</a></li>
<li class="chapter" data-level="6.2" data-path="minstr.html"><a href="minstr.html#initial-configurations"><i class="fa fa-check"></i><b>6.2</b> Initial Configurations</a></li>
<li class="chapter" data-level="6.3" data-path="minstr.html"><a href="minstr.html#apmajmin"><i class="fa fa-check"></i><b>6.3</b> On MM Algorithms</a></li>
<li class="chapter" data-level="6.4" data-path="minstr.html"><a href="minstr.html#smacof-algorithm"><i class="fa fa-check"></i><b>6.4</b> Smacof Algorithm</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="minstr.html"><a href="minstr.html#global-convergence"><i class="fa fa-check"></i><b>6.4.1</b> Global Convergence</a></li>
<li class="chapter" data-level="6.4.2" data-path="minstr.html"><a href="minstr.html#from-the-cs-inequality"><i class="fa fa-check"></i><b>6.4.2</b> From the CS Inequality</a></li>
<li class="chapter" data-level="6.4.3" data-path="minstr.html"><a href="minstr.html#from-majorization"><i class="fa fa-check"></i><b>6.4.3</b> From Majorization</a></li>
<li class="chapter" data-level="6.4.4" data-path="minstr.html"><a href="minstr.html#mincomprot"><i class="fa fa-check"></i><b>6.4.4</b> Component Rotated Smacof</a></li>
<li class="chapter" data-level="6.4.5" data-path="minstr.html"><a href="minstr.html#minlocconv"><i class="fa fa-check"></i><b>6.4.5</b> Local Convergence</a></li>
<li class="chapter" data-level="6.4.6" data-path="minstr.html"><a href="minstr.html#negative-dissimilarities"><i class="fa fa-check"></i><b>6.4.6</b> Negative Dissimilarities</a></li>
<li class="chapter" data-level="6.4.7" data-path="minstr.html"><a href="minstr.html#minunweight"><i class="fa fa-check"></i><b>6.4.7</b> Unweighting</a></li>
<li class="chapter" data-level="6.4.8" data-path="minstr.html"><a href="minstr.html#smacof-in-coefficient-space"><i class="fa fa-check"></i><b>6.4.8</b> Smacof in Coefficient Space</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="minstr.html"><a href="minstr.html#regions-of-attraction"><i class="fa fa-check"></i><b>6.5</b> Regions of Attraction</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="minstr.html"><a href="minstr.html#smacof"><i class="fa fa-check"></i><b>6.5.1</b> Smacof</a></li>
<li class="chapter" data-level="6.5.2" data-path="minstr.html"><a href="minstr.html#newton"><i class="fa fa-check"></i><b>6.5.2</b> Newton</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chacceleration.html"><a href="chacceleration.html"><i class="fa fa-check"></i><b>7</b> Acceleration of Convergence</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chacceleration.html"><a href="chacceleration.html#accelsimple"><i class="fa fa-check"></i><b>7.1</b> Simple Acceleration</a></li>
<li class="chapter" data-level="7.2" data-path="chacceleration.html"><a href="chacceleration.html#one-parameter-methods"><i class="fa fa-check"></i><b>7.2</b> One-Parameter Methods</a></li>
<li class="chapter" data-level="7.3" data-path="chacceleration.html"><a href="chacceleration.html#squarem"><i class="fa fa-check"></i><b>7.3</b> SQUAREM</a></li>
<li class="chapter" data-level="7.4" data-path="chacceleration.html"><a href="chacceleration.html#vector-extrapolation-methods"><i class="fa fa-check"></i><b>7.4</b> Vector extrapolation methods</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nonmtrmds.html"><a href="nonmtrmds.html"><i class="fa fa-check"></i><b>8</b> Nonmetric MDS</a>
<ul>
<li class="chapter" data-level="8.1" data-path="nonmtrmds.html"><a href="nonmtrmds.html#generalities"><i class="fa fa-check"></i><b>8.1</b> Generalities</a></li>
<li class="chapter" data-level="8.2" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmssingledouble"><i class="fa fa-check"></i><b>8.2</b> Single and Double Phase</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="nonmtrmds.html"><a href="nonmtrmds.html#double-phase"><i class="fa fa-check"></i><b>8.2.1</b> Double Phase</a></li>
<li class="chapter" data-level="8.2.2" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmssinglephase"><i class="fa fa-check"></i><b>8.2.2</b> Single Phase</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="nonmtrmds.html"><a href="nonmtrmds.html#affine-nmds"><i class="fa fa-check"></i><b>8.3</b> Affine NMDS</a></li>
<li class="chapter" data-level="8.4" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmdsconic"><i class="fa fa-check"></i><b>8.4</b> Conic MDS</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="nonmtrmds.html"><a href="nonmtrmds.html#nmdsnorm"><i class="fa fa-check"></i><b>8.4.1</b> Normalization</a></li>
<li class="chapter" data-level="8.4.2" data-path="nonmtrmds.html"><a href="nonmtrmds.html#hard-squeeze-and-soft-squeeze"><i class="fa fa-check"></i><b>8.4.2</b> Hard Squeeze and Soft Squeeze</a></li>
<li class="chapter" data-level="8.4.3" data-path="nonmtrmds.html"><a href="nonmtrmds.html#inner-iterations"><i class="fa fa-check"></i><b>8.4.3</b> Inner Iterations</a></li>
<li class="chapter" data-level="8.4.4" data-path="nonmtrmds.html"><a href="nonmtrmds.html#stress-1-and-stress-2"><i class="fa fa-check"></i><b>8.4.4</b> Stress-1 and Stress-2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="intinterval.html"><a href="intinterval.html"><i class="fa fa-check"></i><b>9</b> Interval MDS</a>
<ul>
<li class="chapter" data-level="9.1" data-path="intinterval.html"><a href="intinterval.html#intadditive"><i class="fa fa-check"></i><b>9.1</b> The Additive Constant</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="intinterval.html"><a href="intinterval.html#exactad"><i class="fa fa-check"></i><b>9.1.1</b> Algebra</a></li>
<li class="chapter" data-level="9.1.2" data-path="intinterval.html"><a href="intinterval.html#examples"><i class="fa fa-check"></i><b>9.1.2</b> Examples</a></li>
<li class="chapter" data-level="9.1.3" data-path="intinterval.html"><a href="intinterval.html#variation"><i class="fa fa-check"></i><b>9.1.3</b> A Variation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html"><i class="fa fa-check"></i><b>10</b> Polynomial and Splinical MDS</a>
<ul>
<li class="chapter" data-level="10.1" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#polynomial-mds"><i class="fa fa-check"></i><b>10.1</b> Polynomial MDS</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#monotone-polynomials"><i class="fa fa-check"></i><b>10.1.1</b> Monotone Polynomials</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#splinical-mds"><i class="fa fa-check"></i><b>10.2</b> Splinical MDS</a></li>
<li class="chapter" data-level="10.3" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#mathsplines"><i class="fa fa-check"></i><b>10.3</b> Splines</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#mathbsplines"><i class="fa fa-check"></i><b>10.3.1</b> B-splines</a></li>
<li class="chapter" data-level="10.3.2" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#mathisplines"><i class="fa fa-check"></i><b>10.3.2</b> I-splines</a></li>
<li class="chapter" data-level="10.3.3" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#time-series-example"><i class="fa fa-check"></i><b>10.3.3</b> Time Series Example</a></li>
<li class="chapter" data-level="10.3.4" data-path="polynomial-and-splinical-mds.html"><a href="polynomial-and-splinical-mds.html#monotone-splines"><i class="fa fa-check"></i><b>10.3.4</b> Monotone Splines</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chapordinal.html"><a href="chapordinal.html"><i class="fa fa-check"></i><b>11</b> Ordinal MDS</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chapordinal.html"><a href="chapordinal.html#mathmonreg"><i class="fa fa-check"></i><b>11.1</b> Monotone Regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chapordinal.html"><a href="chapordinal.html#mathsimpiso"><i class="fa fa-check"></i><b>11.1.1</b> Simple Monotone Regression</a></li>
<li class="chapter" data-level="11.1.2" data-path="chapordinal.html"><a href="chapordinal.html#mathweigmr"><i class="fa fa-check"></i><b>11.1.2</b> Weighted Monotone Regression</a></li>
<li class="chapter" data-level="11.1.3" data-path="chapordinal.html"><a href="chapordinal.html#mathnorcone"><i class="fa fa-check"></i><b>11.1.3</b> Normalized Cone Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chapordinal.html"><a href="chapordinal.html#nmdsals"><i class="fa fa-check"></i><b>11.2</b> Alternating Least Squares</a></li>
<li class="chapter" data-level="11.3" data-path="chapordinal.html"><a href="chapordinal.html#nmdskruskal"><i class="fa fa-check"></i><b>11.3</b> Kruskal’s Approach</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="chapordinal.html"><a href="chapordinal.html#kruskals-stress-1"><i class="fa fa-check"></i><b>11.3.1</b> Kruskal’s Stress</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="chapordinal.html"><a href="chapordinal.html#nmdsguttman"><i class="fa fa-check"></i><b>11.4</b> Guttman’s Approach</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="chapordinal.html"><a href="chapordinal.html#smoothness-of-ordinal-loss-functions"><i class="fa fa-check"></i><b>11.4.1</b> Smoothness of Ordinal Loss Functions</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="chapordinal.html"><a href="chapordinal.html#scaling-with-distance-bounds"><i class="fa fa-check"></i><b>11.5</b> Scaling with Distance Bounds</a></li>
<li class="chapter" data-level="11.6" data-path="chapordinal.html"><a href="chapordinal.html#bounds-on-stress"><i class="fa fa-check"></i><b>11.6</b> Bounds on Stress</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unidimensional.html"><a href="unidimensional.html"><i class="fa fa-check"></i><b>12</b> Unidimensional Scaling</a>
<ul>
<li class="chapter" data-level="12.1" data-path="unidimensional.html"><a href="unidimensional.html#an-example"><i class="fa fa-check"></i><b>12.1</b> An example</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="unidimensional.html"><a href="unidimensional.html#perspective"><i class="fa fa-check"></i><b>12.1.1</b> Perspective</a></li>
<li class="chapter" data-level="12.1.2" data-path="unidimensional.html"><a href="unidimensional.html#contour"><i class="fa fa-check"></i><b>12.1.2</b> Contour</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="unidimensional.html"><a href="unidimensional.html#order-formulation"><i class="fa fa-check"></i><b>12.2</b> Order Formulation</a></li>
<li class="chapter" data-level="12.3" data-path="unidimensional.html"><a href="unidimensional.html#permutation-formulation"><i class="fa fa-check"></i><b>12.3</b> Permutation Formulation</a></li>
<li class="chapter" data-level="12.4" data-path="unidimensional.html"><a href="unidimensional.html#sign-matrix-formulation"><i class="fa fa-check"></i><b>12.4</b> Sign Matrix Formulation</a></li>
<li class="chapter" data-level="12.5" data-path="unidimensional.html"><a href="unidimensional.html#unialgorithms"><i class="fa fa-check"></i><b>12.5</b> Algorithms for UMDS</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="unidimensional.html"><a href="unidimensional.html#unismacof"><i class="fa fa-check"></i><b>12.5.1</b> SMACOF</a></li>
<li class="chapter" data-level="12.5.2" data-path="unidimensional.html"><a href="unidimensional.html#unismoothed"><i class="fa fa-check"></i><b>12.5.2</b> SMACOF (smoothed)</a></li>
<li class="chapter" data-level="12.5.3" data-path="unidimensional.html"><a href="unidimensional.html#unibranchbound"><i class="fa fa-check"></i><b>12.5.3</b> Branch-and-Bound</a></li>
<li class="chapter" data-level="12.5.4" data-path="unidimensional.html"><a href="unidimensional.html#unidynamic"><i class="fa fa-check"></i><b>12.5.4</b> Dynamic Programming</a></li>
<li class="chapter" data-level="12.5.5" data-path="unidimensional.html"><a href="unidimensional.html#uniannealing"><i class="fa fa-check"></i><b>12.5.5</b> Simulated Annealing</a></li>
<li class="chapter" data-level="12.5.6" data-path="unidimensional.html"><a href="unidimensional.html#unipenalty"><i class="fa fa-check"></i><b>12.5.6</b> Penalty Methods</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="fullchapter.html"><a href="fullchapter.html"><i class="fa fa-check"></i><b>13</b> Full-dimensional Scaling</a>
<ul>
<li class="chapter" data-level="13.1" data-path="fullchapter.html"><a href="fullchapter.html#fullconvex"><i class="fa fa-check"></i><b>13.1</b> Convexity</a></li>
<li class="chapter" data-level="13.2" data-path="fullchapter.html"><a href="fullchapter.html#fulloptimal"><i class="fa fa-check"></i><b>13.2</b> Optimality</a></li>
<li class="chapter" data-level="13.3" data-path="fullchapter.html"><a href="fullchapter.html#fulliteration"><i class="fa fa-check"></i><b>13.3</b> Iteration</a></li>
<li class="chapter" data-level="13.4" data-path="fullchapter.html"><a href="fullchapter.html#fullcpspace"><i class="fa fa-check"></i><b>13.4</b> Cross Product Space</a></li>
<li class="chapter" data-level="13.5" data-path="fullchapter.html"><a href="fullchapter.html#full-dimensional-scaling"><i class="fa fa-check"></i><b>13.5</b> Full-dimensional Scaling</a></li>
<li class="chapter" data-level="13.6" data-path="fullchapter.html"><a href="fullchapter.html#ekman-example-1"><i class="fa fa-check"></i><b>13.6</b> Ekman example</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chunfolding.html"><a href="chunfolding.html"><i class="fa fa-check"></i><b>14</b> Unfolding</a>
<ul>
<li class="chapter" data-level="14.1" data-path="chunfolding.html"><a href="chunfolding.html#algebra-1"><i class="fa fa-check"></i><b>14.1</b> Algebra</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="chunfolding.html"><a href="chunfolding.html#one-dimensional"><i class="fa fa-check"></i><b>14.1.1</b> One-dimensional</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="chunfolding.html"><a href="chunfolding.html#classical-unfolding"><i class="fa fa-check"></i><b>14.2</b> Classical Unfolding</a></li>
<li class="chapter" data-level="14.3" data-path="chunfolding.html"><a href="chunfolding.html#nonmetric-unfolding"><i class="fa fa-check"></i><b>14.3</b> Nonmetric Unfolding</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="chunfolding.html"><a href="chunfolding.html#unfdegenerate"><i class="fa fa-check"></i><b>14.3.1</b> Degenerate Solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="cmds.html"><a href="cmds.html"><i class="fa fa-check"></i><b>15</b> Constrained Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="15.1" data-path="cmds.html"><a href="cmds.html#baspar"><i class="fa fa-check"></i><b>15.1</b> Basic Partitioning</a></li>
<li class="chapter" data-level="15.2" data-path="cmds.html"><a href="cmds.html#majawa"><i class="fa fa-check"></i><b>15.2</b> Unweigthing</a></li>
<li class="chapter" data-level="15.3" data-path="cmds.html"><a href="cmds.html#constraints-on-the-distances"><i class="fa fa-check"></i><b>15.3</b> Constraints on the Distances</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="cmds.html"><a href="cmds.html#rectangles"><i class="fa fa-check"></i><b>15.3.1</b> Rectangles</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="cmds.html"><a href="cmds.html#lincons"><i class="fa fa-check"></i><b>15.4</b> Linear Constraints</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="cmds.html"><a href="cmds.html#uniqueness"><i class="fa fa-check"></i><b>15.4.1</b> Uniqueness</a></li>
<li class="chapter" data-level="15.4.2" data-path="cmds.html"><a href="cmds.html#combinations"><i class="fa fa-check"></i><b>15.4.2</b> Combinations</a></li>
<li class="chapter" data-level="15.4.3" data-path="cmds.html"><a href="cmds.html#stepsize"><i class="fa fa-check"></i><b>15.4.3</b> Step Size</a></li>
<li class="chapter" data-level="15.4.4" data-path="cmds.html"><a href="cmds.html#singdesign"><i class="fa fa-check"></i><b>15.4.4</b> Single Design Matrix</a></li>
<li class="chapter" data-level="15.4.5" data-path="cmds.html"><a href="cmds.html#multdesign"><i class="fa fa-check"></i><b>15.4.5</b> Multiple Design Matrices</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="cmds.html"><a href="cmds.html#circmds"><i class="fa fa-check"></i><b>15.5</b> Circular MDS</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="cmds.html"><a href="cmds.html#circhist"><i class="fa fa-check"></i><b>15.5.1</b> Some History</a></li>
<li class="chapter" data-level="15.5.2" data-path="cmds.html"><a href="cmds.html#circprimal"><i class="fa fa-check"></i><b>15.5.2</b> Primal Methods</a></li>
<li class="chapter" data-level="15.5.3" data-path="cmds.html"><a href="cmds.html#circdual"><i class="fa fa-check"></i><b>15.5.3</b> Dual Methods</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="cmds.html"><a href="cmds.html#ellimcds"><i class="fa fa-check"></i><b>15.6</b> Elliptical MDS</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="cmds.html"><a href="cmds.html#elliprimal"><i class="fa fa-check"></i><b>15.6.1</b> Primal</a></li>
<li class="chapter" data-level="15.6.2" data-path="cmds.html"><a href="cmds.html#ellidual"><i class="fa fa-check"></i><b>15.6.2</b> Dual</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="cmds.html"><a href="cmds.html#distance-bounds"><i class="fa fa-check"></i><b>15.7</b> Distance Bounds</a></li>
<li class="chapter" data-level="15.8" data-path="cmds.html"><a href="cmds.html#localized-mds"><i class="fa fa-check"></i><b>15.8</b> Localized MDS</a></li>
<li class="chapter" data-level="15.9" data-path="cmds.html"><a href="cmds.html#mds-as-mva"><i class="fa fa-check"></i><b>15.9</b> MDS as MVA</a></li>
<li class="chapter" data-level="15.10" data-path="cmds.html"><a href="cmds.html#conshorseshoes"><i class="fa fa-check"></i><b>15.10</b> Horseshoes</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="asymmds.html"><a href="asymmds.html"><i class="fa fa-check"></i><b>16</b> Asymmetry in MDS</a>
<ul>
<li class="chapter" data-level="16.1" data-path="asymmds.html"><a href="asymmds.html#conditional-rankings"><i class="fa fa-check"></i><b>16.1</b> Conditional Rankings</a></li>
<li class="chapter" data-level="16.2" data-path="asymmds.html"><a href="asymmds.html#confusion-matrices"><i class="fa fa-check"></i><b>16.2</b> Confusion Matrices</a></li>
<li class="chapter" data-level="16.3" data-path="asymmds.html"><a href="asymmds.html#the-slide-vector"><i class="fa fa-check"></i><b>16.3</b> The Slide Vector</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="chindif.html"><a href="chindif.html"><i class="fa fa-check"></i><b>17</b> Individual Differences</a>
<ul>
<li class="chapter" data-level="17.1" data-path="chindif.html"><a href="chindif.html#indifrepl"><i class="fa fa-check"></i><b>17.1</b> Replications</a></li>
<li class="chapter" data-level="17.2" data-path="chindif.html"><a href="chindif.html#indifindscal"><i class="fa fa-check"></i><b>17.2</b> INDSCAL/PARAFAC</a></li>
<li class="chapter" data-level="17.3" data-path="chindif.html"><a href="chindif.html#indifidioscal"><i class="fa fa-check"></i><b>17.3</b> IDIOSCAL/TUCKALS</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chnominal.html"><a href="chnominal.html"><i class="fa fa-check"></i><b>18</b> Nominal MDS</a>
<ul>
<li class="chapter" data-level="18.1" data-path="chnominal.html"><a href="chnominal.html#binary-dissimilarities"><i class="fa fa-check"></i><b>18.1</b> Binary Dissimilarities</a></li>
<li class="chapter" data-level="18.2" data-path="chnominal.html"><a href="chnominal.html#indicator-matrix"><i class="fa fa-check"></i><b>18.2</b> Indicator matrix</a></li>
<li class="chapter" data-level="18.3" data-path="chnominal.html"><a href="chnominal.html#unfolding-indicator-matrices"><i class="fa fa-check"></i><b>18.3</b> Unfolding Indicator Matrices</a></li>
<li class="chapter" data-level="18.4" data-path="chnominal.html"><a href="chnominal.html#linear-separation"><i class="fa fa-check"></i><b>18.4</b> Linear Separation</a></li>
<li class="chapter" data-level="18.5" data-path="chnominal.html"><a href="chnominal.html#circular-separation"><i class="fa fa-check"></i><b>18.5</b> Circular Separation</a></li>
<li class="chapter" data-level="18.6" data-path="chnominal.html"><a href="chnominal.html#multidimensional-scalogram-analysis"><i class="fa fa-check"></i><b>18.6</b> Multidimensional Scalogram Analysis</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="ssstr.html"><a href="ssstr.html"><i class="fa fa-check"></i><b>19</b> Sstress and strain</a>
<ul>
<li class="chapter" data-level="19.1" data-path="ssstr.html"><a href="ssstr.html#sstress"><i class="fa fa-check"></i><b>19.1</b> sstress</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="ssstr.html"><a href="ssstr.html#sstress-and-stress"><i class="fa fa-check"></i><b>19.1.1</b> sstress and stress</a></li>
<li class="chapter" data-level="19.1.2" data-path="ssstr.html"><a href="ssstr.html#decomposition"><i class="fa fa-check"></i><b>19.1.2</b> Decomposition</a></li>
<li class="chapter" data-level="19.1.3" data-path="ssstr.html"><a href="ssstr.html#full-dimensional-sstress"><i class="fa fa-check"></i><b>19.1.3</b> Full-dimensional sstress</a></li>
<li class="chapter" data-level="19.1.4" data-path="ssstr.html"><a href="ssstr.html#minimizing-sstress"><i class="fa fa-check"></i><b>19.1.4</b> Minimizing sstress</a></li>
<li class="chapter" data-level="19.1.5" data-path="ssstr.html"><a href="ssstr.html#bounds-for-sstress"><i class="fa fa-check"></i><b>19.1.5</b> Bounds for sstress</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="ssstr.html"><a href="ssstr.html#strain"><i class="fa fa-check"></i><b>19.2</b> strain</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="ssstr.html"><a href="ssstr.html#unweighted"><i class="fa fa-check"></i><b>19.2.1</b> Unweighted</a></li>
<li class="chapter" data-level="19.2.2" data-path="ssstr.html"><a href="ssstr.html#using-additivity"><i class="fa fa-check"></i><b>19.2.2</b> Using Additivity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="chrstress.html"><a href="chrstress.html"><i class="fa fa-check"></i><b>20</b> fstress and rstress</a>
<ul>
<li class="chapter" data-level="20.1" data-path="chrstress.html"><a href="chrstress.html#fstress"><i class="fa fa-check"></i><b>20.1</b> fstress</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="chrstress.html"><a href="chrstress.html#use-of-weights"><i class="fa fa-check"></i><b>20.1.1</b> Use of Weights</a></li>
<li class="chapter" data-level="20.1.2" data-path="chrstress.html"><a href="chrstress.html#convexity"><i class="fa fa-check"></i><b>20.1.2</b> Convexity</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="chrstress.html"><a href="chrstress.html#rstress"><i class="fa fa-check"></i><b>20.2</b> rStress</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="chrstress.html"><a href="chrstress.html#using-weights"><i class="fa fa-check"></i><b>20.2.1</b> Using Weights</a></li>
<li class="chapter" data-level="20.2.2" data-path="chrstress.html"><a href="chrstress.html#minimizing-rstress"><i class="fa fa-check"></i><b>20.2.2</b> Minimizing rstress</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="chrstress.html"><a href="chrstress.html#mstress"><i class="fa fa-check"></i><b>20.3</b> mstress</a></li>
<li class="chapter" data-level="20.4" data-path="chrstress.html"><a href="chrstress.html#astress"><i class="fa fa-check"></i><b>20.4</b> astress</a></li>
<li class="chapter" data-level="20.5" data-path="chrstress.html"><a href="chrstress.html#pstress"><i class="fa fa-check"></i><b>20.5</b> pstress</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html"><i class="fa fa-check"></i><b>21</b> Alternative Least Squares Loss</a>
<ul>
<li class="chapter" data-level="21.1" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#sammons-mds"><i class="fa fa-check"></i><b>21.1</b> Sammon’s MDS</a></li>
<li class="chapter" data-level="21.2" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#mcgees-work"><i class="fa fa-check"></i><b>21.2</b> McGee’s Work</a></li>
<li class="chapter" data-level="21.3" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#shepards-nonmetric-mds"><i class="fa fa-check"></i><b>21.3</b> Shepard’s Nonmetric MDS</a></li>
<li class="chapter" data-level="21.4" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#guttmans-nonmetric-mds"><i class="fa fa-check"></i><b>21.4</b> Guttman’s Nonmetric MDS</a></li>
<li class="chapter" data-level="21.5" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#positive-orthant-nonmetric-mds"><i class="fa fa-check"></i><b>21.5</b> Positive Orthant Nonmetric MDS</a></li>
<li class="chapter" data-level="21.6" data-path="alternative-least-squares-loss.html"><a href="alternative-least-squares-loss.html#interrole"><i class="fa fa-check"></i><b>21.6</b> Role Reversal</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html"><i class="fa fa-check"></i><b>22</b> Inverse Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="22.1" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#basic-imds"><i class="fa fa-check"></i><b>22.1</b> Basic IMDS</a></li>
<li class="chapter" data-level="22.2" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#non-negative-dissimilarities"><i class="fa fa-check"></i><b>22.2</b> Non-negative Dissimilarities</a></li>
<li class="chapter" data-level="22.3" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#zero-weights-andor-distances"><i class="fa fa-check"></i><b>22.3</b> Zero Weights and/or Distances</a></li>
<li class="chapter" data-level="22.4" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#examples-1"><i class="fa fa-check"></i><b>22.4</b> Examples</a>
<ul>
<li class="chapter" data-level="22.4.1" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#first-example"><i class="fa fa-check"></i><b>22.4.1</b> First Example</a></li>
<li class="chapter" data-level="22.4.2" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#second-example"><i class="fa fa-check"></i><b>22.4.2</b> Second Example</a></li>
<li class="chapter" data-level="22.4.3" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#third-example"><i class="fa fa-check"></i><b>22.4.3</b> Third Example</a></li>
<li class="chapter" data-level="22.4.4" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#fourth-example"><i class="fa fa-check"></i><b>22.4.4</b> Fourth Example</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#mds-sensitivity"><i class="fa fa-check"></i><b>22.5</b> MDS Sensitivity</a></li>
<li class="chapter" data-level="22.6" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#second-order-inverse-mds"><i class="fa fa-check"></i><b>22.6</b> Second Order Inverse MDS</a></li>
<li class="chapter" data-level="22.7" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#inverse-fds"><i class="fa fa-check"></i><b>22.7</b> Inverse FDS</a></li>
<li class="chapter" data-level="22.8" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#multiple-solutions"><i class="fa fa-check"></i><b>22.8</b> Multiple Solutions</a></li>
<li class="chapter" data-level="22.9" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#minimizing-istress"><i class="fa fa-check"></i><b>22.9</b> Minimizing iStress</a></li>
<li class="chapter" data-level="22.10" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#order-three"><i class="fa fa-check"></i><b>22.10</b> Order three</a></li>
<li class="chapter" data-level="22.11" data-path="inverse-multidimensional-scaling.html"><a href="inverse-multidimensional-scaling.html#order-four"><i class="fa fa-check"></i><b>22.11</b> Order Four</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="stability.html"><a href="stability.html"><i class="fa fa-check"></i><b>23</b> Stability of MDS Solutions</a>
<ul>
<li class="chapter" data-level="23.1" data-path="stability.html"><a href="stability.html#null-distribution"><i class="fa fa-check"></i><b>23.1</b> Null Distribution</a></li>
<li class="chapter" data-level="23.2" data-path="stability.html"><a href="stability.html#pseudo-confidence-ellipsoids"><i class="fa fa-check"></i><b>23.2</b> Pseudo-confidence Ellipsoids</a></li>
<li class="chapter" data-level="23.3" data-path="stability.html"><a href="stability.html#a-pseudo-bootstrap"><i class="fa fa-check"></i><b>23.3</b> A Pseudo-Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="global.html"><a href="global.html"><i class="fa fa-check"></i><b>24</b> In Search of Global Minima</a>
<ul>
<li class="chapter" data-level="24.1" data-path="global.html"><a href="global.html#random-starts"><i class="fa fa-check"></i><b>24.1</b> Random Starts</a>
<ul>
<li class="chapter" data-level="24.1.1" data-path="global.html"><a href="global.html#examples-2"><i class="fa fa-check"></i><b>24.1.1</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="global.html"><a href="global.html#tunneling-filling-annealing-etc."><i class="fa fa-check"></i><b>24.2</b> Tunneling, Filling, Annealing, etc.</a></li>
<li class="chapter" data-level="24.3" data-path="global.html"><a href="global.html#globcutplanes"><i class="fa fa-check"></i><b>24.3</b> Cutting Planes</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="global.html"><a href="global.html#globalcircle"><i class="fa fa-check"></i><b>24.3.1</b> On the Circle</a></li>
<li class="chapter" data-level="24.3.2" data-path="global.html"><a href="global.html#cauchy-step-size"><i class="fa fa-check"></i><b>24.3.2</b> Cauchy Step Size</a></li>
<li class="chapter" data-level="24.3.3" data-path="global.html"><a href="global.html#balls"><i class="fa fa-check"></i><b>24.3.3</b> Balls</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="global.html"><a href="global.html#distance-smoothing"><i class="fa fa-check"></i><b>24.4</b> Distance Smoothing</a></li>
<li class="chapter" data-level="24.5" data-path="global.html"><a href="global.html#penalizing-dimensions"><i class="fa fa-check"></i><b>24.5</b> Penalizing Dimensions</a>
<ul>
<li class="chapter" data-level="24.5.1" data-path="global.html"><a href="global.html#local-minima"><i class="fa fa-check"></i><b>24.5.1</b> Local Minima</a></li>
<li class="chapter" data-level="24.5.2" data-path="global.html"><a href="global.html#algorithm"><i class="fa fa-check"></i><b>24.5.2</b> Algorithm</a></li>
<li class="chapter" data-level="24.5.3" data-path="global.html"><a href="global.html#examples-3"><i class="fa fa-check"></i><b>24.5.3</b> Examples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="mathadd.html"><a href="mathadd.html"><i class="fa fa-check"></i><b>25</b> Mathematical Addenda</a>
<ul>
<li class="chapter" data-level="25.1" data-path="mathadd.html"><a href="mathadd.html#apnotation"><i class="fa fa-check"></i><b>25.1</b> Notation</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="mathadd.html"><a href="mathadd.html#symbols"><i class="fa fa-check"></i><b>25.1.1</b> Symbols</a></li>
<li class="chapter" data-level="25.1.2" data-path="mathadd.html"><a href="mathadd.html#summation"><i class="fa fa-check"></i><b>25.1.2</b> Summation</a></li>
</ul></li>
<li class="chapter" data-level="25.2" data-path="mathadd.html"><a href="mathadd.html#apmatrices"><i class="fa fa-check"></i><b>25.2</b> Matrices</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="mathadd.html"><a href="mathadd.html#apmspaces"><i class="fa fa-check"></i><b>25.2.1</b> Matrix Spaces</a></li>
<li class="chapter" data-level="25.2.2" data-path="mathadd.html"><a href="mathadd.html#apconstants"><i class="fa fa-check"></i><b>25.2.2</b> Constants</a></li>
<li class="chapter" data-level="25.2.3" data-path="mathadd.html"><a href="mathadd.html#difmat"><i class="fa fa-check"></i><b>25.2.3</b> Diff Matrices</a></li>
<li class="chapter" data-level="25.2.4" data-path="mathadd.html"><a href="mathadd.html#apsign"><i class="fa fa-check"></i><b>25.2.4</b> Sign Matrices</a></li>
<li class="chapter" data-level="25.2.5" data-path="mathadd.html"><a href="mathadd.html#apcombo"><i class="fa fa-check"></i><b>25.2.5</b> Sums and Products</a></li>
<li class="chapter" data-level="25.2.6" data-path="mathadd.html"><a href="mathadd.html#apinverse"><i class="fa fa-check"></i><b>25.2.6</b> Inverse</a></li>
<li class="chapter" data-level="25.2.7" data-path="mathadd.html"><a href="mathadd.html#aploewner"><i class="fa fa-check"></i><b>25.2.7</b> The Loewner order</a></li>
<li class="chapter" data-level="25.2.8" data-path="mathadd.html"><a href="mathadd.html#apeigen"><i class="fa fa-check"></i><b>25.2.8</b> Eigen Decomposition</a></li>
<li class="chapter" data-level="25.2.9" data-path="mathadd.html"><a href="mathadd.html#apsvd"><i class="fa fa-check"></i><b>25.2.9</b> Singular Value Decomposition</a></li>
<li class="chapter" data-level="25.2.10" data-path="mathadd.html"><a href="mathadd.html#apmpi"><i class="fa fa-check"></i><b>25.2.10</b> Moore-Penrose Inverse</a></li>
<li class="chapter" data-level="25.2.11" data-path="mathadd.html"><a href="mathadd.html#apfullrank"><i class="fa fa-check"></i><b>25.2.11</b> Full-rank Decomposition</a></li>
<li class="chapter" data-level="25.2.12" data-path="mathadd.html"><a href="mathadd.html#apsdc"><i class="fa fa-check"></i><b>25.2.12</b> SDC matrices</a></li>
</ul></li>
<li class="chapter" data-level="25.3" data-path="mathadd.html"><a href="mathadd.html#apineq"><i class="fa fa-check"></i><b>25.3</b> Inequalities</a>
<ul>
<li class="chapter" data-level="25.3.1" data-path="mathadd.html"><a href="mathadd.html#apcs"><i class="fa fa-check"></i><b>25.3.1</b> Cauchy-Schwartz</a></li>
<li class="chapter" data-level="25.3.2" data-path="mathadd.html"><a href="mathadd.html#apamgm"><i class="fa fa-check"></i><b>25.3.2</b> Arithmetic/Geometric Mean</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="mathadd.html"><a href="mathadd.html#apanal"><i class="fa fa-check"></i><b>25.4</b> Calculus/Analysis</a>
<ul>
<li class="chapter" data-level="25.4.1" data-path="mathadd.html"><a href="mathadd.html#appfunctions"><i class="fa fa-check"></i><b>25.4.1</b> Functions</a></li>
<li class="chapter" data-level="25.4.2" data-path="mathadd.html"><a href="mathadd.html#appdiffer"><i class="fa fa-check"></i><b>25.4.2</b> Differentiation</a></li>
<li class="chapter" data-level="25.4.3" data-path="mathadd.html"><a href="mathadd.html#local-minima-critical-points"><i class="fa fa-check"></i><b>25.4.3</b> Local Minima, Critical Points</a></li>
<li class="chapter" data-level="25.4.4" data-path="mathadd.html"><a href="mathadd.html#necessary"><i class="fa fa-check"></i><b>25.4.4</b> Necessary Conditions</a></li>
<li class="chapter" data-level="25.4.5" data-path="mathadd.html"><a href="mathadd.html#hopital"><i class="fa fa-check"></i><b>25.4.5</b> l’Hôpital’s Rule</a></li>
<li class="chapter" data-level="25.4.6" data-path="mathadd.html"><a href="mathadd.html#mathimplcit"><i class="fa fa-check"></i><b>25.4.6</b> Implicit Functions</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="mathadd.html"><a href="mathadd.html#mathconvexfuncs"><i class="fa fa-check"></i><b>25.5</b> Convexity</a>
<ul>
<li class="chapter" data-level="25.5.1" data-path="mathadd.html"><a href="mathadd.html#mathextminima"><i class="fa fa-check"></i><b>25.5.1</b> Existence of Minima</a></li>
<li class="chapter" data-level="25.5.2" data-path="mathadd.html"><a href="mathadd.html#mathduality"><i class="fa fa-check"></i><b>25.5.2</b> Duality</a></li>
<li class="chapter" data-level="25.5.3" data-path="mathadd.html"><a href="mathadd.html#mathsubdif"><i class="fa fa-check"></i><b>25.5.3</b> Subdifferentials</a></li>
<li class="chapter" data-level="25.5.4" data-path="mathadd.html"><a href="mathadd.html#mathextdcfunc"><i class="fa fa-check"></i><b>25.5.4</b> DC Functions</a></li>
<li class="chapter" data-level="25.5.5" data-path="mathadd.html"><a href="mathadd.html#mathdanskin"><i class="fa fa-check"></i><b>25.5.5</b> Danskin-Berge Theorem</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="mathadd.html"><a href="mathadd.html#apiterate"><i class="fa fa-check"></i><b>25.6</b> Fixed-Point Iterations</a>
<ul>
<li class="chapter" data-level="25.6.1" data-path="mathadd.html"><a href="mathadd.html#point-to-set-maps"><i class="fa fa-check"></i><b>25.6.1</b> Point-to-set Maps</a></li>
<li class="chapter" data-level="25.6.2" data-path="mathadd.html"><a href="mathadd.html#zangwill"><i class="fa fa-check"></i><b>25.6.2</b> Zangwill’s Theorem</a></li>
<li class="chapter" data-level="25.6.3" data-path="mathadd.html"><a href="mathadd.html#ostrowski"><i class="fa fa-check"></i><b>25.6.3</b> Ostrowski’s Theorem</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="mathadd.html"><a href="mathadd.html#mathls"><i class="fa fa-check"></i><b>25.7</b> Least Squares</a>
<ul>
<li class="chapter" data-level="25.7.1" data-path="mathadd.html"><a href="mathadd.html#mathquprog"><i class="fa fa-check"></i><b>25.7.1</b> Quadratic Programming</a></li>
</ul></li>
<li class="chapter" data-level="25.8" data-path="mathadd.html"><a href="mathadd.html#mathpenal"><i class="fa fa-check"></i><b>25.8</b> Quadratic penalties</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="apcode.html"><a href="apcode.html"><i class="fa fa-check"></i><b>A</b> Code</a>
<ul>
<li class="chapter" data-level="A.1" data-path="apcode.html"><a href="apcode.html#rapcode"><i class="fa fa-check"></i><b>A.1</b> R Code</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="apcode.html"><a href="apcode.html#aputilitiescode"><i class="fa fa-check"></i><b>A.1.1</b> utilities.R</a></li>
<li class="chapter" data-level="A.1.2" data-path="apcode.html"><a href="apcode.html#apindexingcode"><i class="fa fa-check"></i><b>A.1.2</b> commom/indexing.r</a></li>
<li class="chapter" data-level="A.1.3" data-path="apcode.html"><a href="apcode.html#apiocode"><i class="fa fa-check"></i><b>A.1.3</b> commom/io.r</a></li>
<li class="chapter" data-level="A.1.4" data-path="apcode.html"><a href="apcode.html#aplinearcode"><i class="fa fa-check"></i><b>A.1.4</b> commom/linear.r</a></li>
<li class="chapter" data-level="A.1.5" data-path="apcode.html"><a href="apcode.html#appermcode"><i class="fa fa-check"></i><b>A.1.5</b> commom/nextPC.r</a></li>
<li class="chapter" data-level="A.1.6" data-path="apcode.html"><a href="apcode.html#apsmacofcode"><i class="fa fa-check"></i><b>A.1.6</b> commom/smacof.r</a></li>
<li class="chapter" data-level="A.1.7" data-path="apcode.html"><a href="apcode.html#apcodeprop"><i class="fa fa-check"></i><b>A.1.7</b> properties.R</a></li>
<li class="chapter" data-level="A.1.8" data-path="apcode.html"><a href="apcode.html#apcodepic"><i class="fa fa-check"></i><b>A.1.8</b> pictures.R</a></li>
<li class="chapter" data-level="A.1.9" data-path="apcode.html"><a href="apcode.html#apcodeclass"><i class="fa fa-check"></i><b>A.1.9</b> classical.R</a></li>
<li class="chapter" data-level="A.1.10" data-path="apcode.html"><a href="apcode.html#apcodeminim"><i class="fa fa-check"></i><b>A.1.10</b> minimization.R</a></li>
<li class="chapter" data-level="A.1.11" data-path="apcode.html"><a href="apcode.html#apcodefull"><i class="fa fa-check"></i><b>A.1.11</b> full.R</a></li>
<li class="chapter" data-level="A.1.12" data-path="apcode.html"><a href="apcode.html#apcodeunfold"><i class="fa fa-check"></i><b>A.1.12</b> unfolding.R</a></li>
<li class="chapter" data-level="A.1.13" data-path="apcode.html"><a href="apcode.html#apcodencons"><i class="fa fa-check"></i><b>A.1.13</b> constrained.R</a></li>
<li class="chapter" data-level="A.1.14" data-path="apcode.html"><a href="apcode.html#apcodenominal"><i class="fa fa-check"></i><b>A.1.14</b> nominal.R</a></li>
<li class="chapter" data-level="A.1.15" data-path="apcode.html"><a href="apcode.html#apcodesstress"><i class="fa fa-check"></i><b>A.1.15</b> sstress.R</a></li>
<li class="chapter" data-level="A.1.16" data-path="apcode.html"><a href="apcode.html#apcodeinverse"><i class="fa fa-check"></i><b>A.1.16</b> inverse.R</a></li>
<li class="chapter" data-level="A.1.17" data-path="apcode.html"><a href="apcode.html#apcodeglobal"><i class="fa fa-check"></i><b>A.1.17</b> global.R</a></li>
<li class="chapter" data-level="A.1.18" data-path="apcode.html"><a href="apcode.html#apcodemathadd"><i class="fa fa-check"></i><b>A.1.18</b> mathadd.R</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="apcode.html"><a href="apcode.html#c-code"><i class="fa fa-check"></i><b>A.2</b> C code</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="apcode.html"><a href="apcode.html#deboor.c"><i class="fa fa-check"></i><b>A.2.1</b> deboor.c</a></li>
<li class="chapter" data-level="A.2.2" data-path="apcode.html"><a href="apcode.html#cleanup.c"><i class="fa fa-check"></i><b>A.2.2</b> cleanup.c</a></li>
<li class="chapter" data-level="A.2.3" data-path="apcode.html"><a href="apcode.html#jacobi.c"><i class="fa fa-check"></i><b>A.2.3</b> jacobi.c</a></li>
<li class="chapter" data-level="A.2.4" data-path="apcode.html"><a href="apcode.html#jbkties.c"><i class="fa fa-check"></i><b>A.2.4</b> jbkTies.c</a></li>
<li class="chapter" data-level="A.2.5" data-path="apcode.html"><a href="apcode.html#matrix.c"><i class="fa fa-check"></i><b>A.2.5</b> matrix.c</a></li>
<li class="chapter" data-level="A.2.6" data-path="apcode.html"><a href="apcode.html#jeffrey.c"><i class="fa fa-check"></i><b>A.2.6</b> jeffrey.c</a></li>
<li class="chapter" data-level="A.2.7" data-path="apcode.html"><a href="apcode.html#mysort.c"><i class="fa fa-check"></i><b>A.2.7</b> mySort.c</a></li>
<li class="chapter" data-level="A.2.8" data-path="apcode.html"><a href="apcode.html#nextpc.c"><i class="fa fa-check"></i><b>A.2.8</b> nextPC.c</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="apdatasets.html"><a href="apdatasets.html"><i class="fa fa-check"></i><b>B</b> Data</a>
<ul>
<li class="chapter" data-level="B.1" data-path="apdatasets.html"><a href="apdatasets.html#apdatadsmall"><i class="fa fa-check"></i><b>B.1</b> Small</a></li>
<li class="chapter" data-level="B.2" data-path="apdatasets.html"><a href="apdatasets.html#apdatagruijter"><i class="fa fa-check"></i><b>B.2</b> De Gruijter</a></li>
<li class="chapter" data-level="B.3" data-path="apdatasets.html"><a href="apdatasets.html#apdataekman"><i class="fa fa-check"></i><b>B.3</b> Ekman</a></li>
<li class="chapter" data-level="B.4" data-path="apdatasets.html"><a href="apdatasets.html#apdataveg"><i class="fa fa-check"></i><b>B.4</b> Vegetables</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="apunlicense.html"><a href="apunlicense.html"><i class="fa fa-check"></i><b>C</b> Unlicense</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Least Squares Euclidean Multidimensional Scaling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inverse-multidimensional-scaling" class="section level1" number="22">
<h1><span class="header-section-number">22</span> Inverse Multidimensional Scaling</h1>
<p>In MDS we start with dissimilarities and we find a configuration that locally minimizes stress. We know that the equation we have to solve is <span class="math inline">\(B(X)X=VX\)</span>. MDS maps dissimilarities into configurations by finding one (or, ideally, all) solutions of this equation. In Inverse MDS (IMDS) we start wth the same equation
<span class="math inline">\(B(X)X=VX\)</span>, but now we find all dissimilarity matrices for which a given configuration is a local optimum, or at least a stationary point. Thus we solve for <span class="math inline">\(\Delta\)</span> for given <span class="math inline">\(X\)</span>, and we study the inverse of the MDS map.</p>
<p>Inverse MDS was first described in <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span>, R code was provided in <span class="citation"><a href="#ref-deleeuw_U_12b" role="doc-biblioref">De Leeuw</a> (<a href="#ref-deleeuw_U_12b" role="doc-biblioref">2012</a>)</span>, and some elaborations are in <span class="citation"><a href="#ref-deleeuw_groenen_mair_E_16f" role="doc-biblioref">De Leeuw, Groenen, and Mair</a> (<a href="#ref-deleeuw_groenen_mair_E_16f" role="doc-biblioref">2016d</a>)</span>. This chapter leans heavily on <span class="citation"><a href="#ref-deleeuw_groenen_mair_E_16f" role="doc-biblioref">De Leeuw, Groenen, and Mair</a> (<a href="#ref-deleeuw_groenen_mair_E_16f" role="doc-biblioref">2016d</a>)</span>, but we have reformulated some results and pruned some of the examples.</p>
<p>In studying the IMDS mapping we limit ourselves, unless explicitly stated otherwise, to configurations <span class="math inline">\(X\)</span> that are <em>regular</em>, in the sense that <span class="math inline">\(d_{ij}(X)&gt;0\)</span> for all <span class="math inline">\(i\not= j\)</span>.
This can be done without loss of generality. If some of the distances are zero, then the corresponding IMDS problem can be reduced to a regular problem with a smaller number of points (<span class="citation"><a href="#ref-deleeuw_groenen_mair_E_16g" role="doc-biblioref">De Leeuw, Groenen, and Mair</a> (<a href="#ref-deleeuw_groenen_mair_E_16g" role="doc-biblioref">2016f</a>)</span>). Also, an <span class="math inline">\(n\times p\)</span> configuration <span class="math inline">\(X\)</span> is <em>normalized</em> if it is column-centered and has rank <span class="math inline">\(p\)</span>. For such <span class="math inline">\(X\)</span> there exist <span class="math inline">\(n\times (n-p-1)\)</span> centered orthonormal matrix <span class="math inline">\(K\)</span> such that <span class="math inline">\(K&#39;X=0\)</span>. In IMDS we will always assume that <span class="math inline">\(X\)</span> is both regular and normalized. We also assume, unless it is explicitly stated otherwise, that all off-diagonal weights <span class="math inline">\(w_{ij}\)</span> are non-zero.</p>
<p>In <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span> two different basic IMDS versions are discussed. Both versions start with the stationary equation <span class="math inline">\(B(X)X=VX\)</span>. The first finds all <span class="math inline">\(W\)</span> and <span class="math inline">\(\Delta\)</span> for which a given <span class="math inline">\(X\)</span> is stationary. The second finds all <span class="math inline">\(\Delta\)</span> for a given <span class="math inline">\(X\)</span> and <span class="math inline">\(W\)</span> for which <span class="math inline">\(X\)</span> is stationary. In this chapter we only look at the second form of IMDS. As we shall see, the first version turns out introduce too many unknowns in <span class="math inline">\(W\)</span> and <span class="math inline">\(\Delta\)</span> to be useful. The second form also reflects the point of view that <span class="math inline">\(\Delta\)</span> are the data, while the <span class="math inline">\(W\)</span> are part of the definition of the loss function.</p>
<div id="basic-imds" class="section level2" number="22.1">
<h2><span class="header-section-number">22.1</span> Basic IMDS</h2>
<p>Suppose <span class="math inline">\(X\)</span> is a regular and normalized configuration satisfying the stationary equation <span class="math inline">\((V-B(X))X=0\)</span>.
Our first IMDS step is to describe the set <span class="math inline">\(\mathfrak{D}(X)\)</span> of all <span class="math inline">\(\Delta\)</span>E for which <span class="math inline">\(X\)</span> is stationary.</p>
<div class="lemma">
<p><span id="lem:syminv" class="lemma"><strong>Lemma 22.1  </strong></span>Suppose <span class="math inline">\(X\)</span> is an <span class="math inline">\(n\times p\)</span> matrix of rank <span class="math inline">\(p&lt;n\)</span>. Suppose <span class="math inline">\(K\)</span> is an <span class="math inline">\(n\times(n-p)\)</span> orthonormal matrix with <span class="math inline">\(K&#39;X=0\)</span>. Then a symmetric matrix <span class="math inline">\(A\)</span> satisfies <span class="math inline">\(AX=0\)</span> if and only if there is a symmetric <span class="math inline">\(S\)</span> such that <span class="math inline">\(A=KSK&#39;\)</span>. If <span class="math inline">\(\text{rank}(K&#39;AK)=r\)</span> then <span class="math inline">\(S\)</span> can be chosento be of order <span class="math inline">\(r\)</span>.</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-27" class="proof"><em>Proof</em>. </span>Suppose <span class="math inline">\(X=LT\)</span> with <span class="math inline">\(L\)</span> an orthonormal basis for the column space of <span class="math inline">\(X\)</span> and <span class="math inline">\(T\)</span> non-singular. Write <span class="math inline">\(A\)</span> as</p>
<p><span class="math display" id="eq:invasolve">\[\begin{equation}
A=\begin{bmatrix}L&amp;K\end{bmatrix}
\begin{bmatrix}
A_{11}&amp;A_{12}\\A_{21}&amp;A_{22}
\end{bmatrix}
\begin{bmatrix}L&#39;\\K&#39;\end{bmatrix}.
\tag{22.1}
\end{equation}\]</span></p>
<p>Then <span class="math inline">\(AX=LA_{11}T+KA_{21}=0\)</span> which is true if and only if <span class="math inline">\(A_{11}=0\)</span>
and <span class="math inline">\(A_{21}=0\)</span>, and by symmetry <span class="math inline">\(A_{12}=0\)</span>. Thus <span class="math inline">\(A=KA_{22}K&#39;\)</span>.</p>
</div>
<div class="theorem">
<p><span id="thm:keyresult" class="theorem"><strong>Theorem 22.1  </strong></span><span class="math inline">\(\Delta\in\mathfrak{D}(X)\)</span> if and only if there is a symmetric <span class="math inline">\(S\)</span> of order <span class="math inline">\(n-p-1\)</span> such that for all <span class="math inline">\(i\not= j\)</span></p>
<p><span class="math display" id="eq:invalldelta">\[\begin{equation}
\delta_{ij}=d_{ij}(X)\left\{1-\frac{k_i&#39;Sk_j^{\ }}{w_{ij}}\right\}.
\tag{22.2}
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span id="unlabeled-div-28" class="proof"><em>Proof</em>. </span>By lemma XXX we have <span class="math inline">\((V-B(X))X=0\)</span> if and only if there is a symmetric <span class="math inline">\(S\)</span> such that <span class="math inline">\(V-B(X)=KSK&#39;\)</span>. This can be rearranged to yield <a href="inverse-multidimensional-scaling.html#eq:invalldelta">(22.2)</a>. Since the vector <span class="math inline">\(e\)</span> satisfies both <span class="math inline">\(X&#39;e=0\)</span> and <span class="math inline">\((V-B(X))e=0\)</span> we can choose <span class="math inline">\(S\)</span> to be of order <span class="math inline">\(n-p-1\)</span>.</p>
</div>
<p>Thus <span class="math inline">\(\mathfrak{D}(X)\)</span> is a non-empty affine space, a translation of a linear subspace, closed under all linear combinations with coefficients that add up to one. Since <span class="math inline">\(S\)</span> is symmetric of order <span class="math inline">\(n-p-1\)</span>, equation <a href="inverse-multidimensional-scaling.html#eq:invalldelta">(22.2)</a> defines an affine subspace of dimension <span class="math inline">\(\frac12(n-p)(n-p-1)\)</span>. If <span class="math inline">\(n=3\)</span> and <span class="math inline">\(p=1\)</span>, or if <span class="math inline">\(n=4\)</span> and <span class="math inline">\(p=2\)</span>, the dimension is one. If <span class="math inline">\(n=4\)</span> and <span class="math inline">\(p=1\)</span> the dimension is three.</p>
<p>If <span class="math inline">\(\Delta_1,\cdots,\Delta_m\)</span> are in <span class="math inline">\(\mathfrak{D}(X)\)</span>, then so is the affine subspace spanned by the <span class="math inline">\(\Delta_j\)</span>. For all configurations <span class="math inline">\(X\)</span> we have <span class="math inline">\(D(X)\in\mathfrak{D}(X)\)</span>. Specifically, if we compute a solution to the stationary equations <span class="math inline">\(X\)</span> with some MDS algorithm such as smacof, then the whole line through the data <span class="math inline">\(\Delta\)</span> and <span class="math inline">\(D(X)\)</span> is in <span class="math inline">\(\mathfrak{D}(X)\)</span>.</p>
<p>The next result is corollary 6.3 in <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span>.</p>

<div class="corollary">
<span id="cor:unnamed-chunk-10" class="corollary"><strong>Corollary 22.1  </strong></span><strong><code>r corollary_nums("full_result", display = "f")</code></strong> If <span class="math inline">\(p=n-1\)</span> then <span class="math inline">\(\Delta\in\mathfrak{D}(X)\)</span> if and only if <span class="math inline">\(\Delta=D(X)\)</span> if and only if <span class="math inline">\(\sigma(X)=0\)</span>.
</div>
<div class="proof">
<p><span id="unlabeled-div-29" class="proof"><em>Proof</em>. </span>If <span class="math inline">\(p=n-1\)</span> then <span class="math inline">\(S\)</span> in theorem <a href="inverse-multidimensional-scaling.html#thm:keyresult">22.1</a> is of order zero.</p>
</div>
<p>For any two elements of <span class="math inline">\(\mathfrak{D}(X)\)</span>, one cannot be elementwise larger (or smaller) than the other. This is corollary 3.3 in <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span>.</p>

<div class="corollary">
<span id="cor:dominate" class="corollary"><strong>Corollary 22.2  </strong></span>If <span class="math inline">\(\Delta_1\)</span> and <span class="math inline">\(\Delta_2\)</span> are both in <span class="math inline">\(\mathfrak{DS}(X)\)</span> and <span class="math inline">\(\Delta_1\leq\Delta_2\)</span>, then <span class="math inline">\(\Delta_1=\Delta_2\)</span>.
</div>
<div class="proof">
<p><span id="unlabeled-div-30" class="proof"><em>Proof</em>. </span>With obvious notation <span class="math inline">\(\mathbf{tr}\ X&#39;(B_1(X)-B_2(X))X=0\)</span>, which can be written as</p>
<p><span class="math display" id="eq:invcompare">\[\begin{equation}
\mathop{\sum\sum}_{1\leq i&lt;j\leq n} w_{ij}\left(\delta_{1ij}-\delta_{2ij}\right)d_{ij}(X)=0,
\tag{22.3}
\end{equation}\]</span></p>
<p>and thus <span class="math inline">\(\Delta_1\leq\Delta_2\)</span> implies <span class="math inline">\(\Delta_1=\Delta_2\)</span>.</p>
</div>
</div>
<div id="non-negative-dissimilarities" class="section level2" number="22.2">
<h2><span class="header-section-number">22.2</span> Non-negative Dissimilarities</h2>
<p>From equation <a href="inverse-multidimensional-scaling.html#eq:invalldelta">(22.2)</a> it follows <span class="math inline">\(\delta_{ij}\)</span> is a decreasing function of <span class="math inline">\(\tau_{ij}\)</span>, and <span class="math inline">\(\delta_{ij}\geq 0\)</span> if and only if <span class="math inline">\(\tau_{ij}\leq w_{ij}\)</span>.</p>
<p>Convex cone, affine convex cone</p>

<div class="lemma">
<span id="lem:goldman" class="lemma"><strong>Lemma 22.2  </strong></span>A non-vacuous polyhedral convex set <span class="math inline">\(C=\{x\mid Ax\leq b\}\)</span> is bounded if and only if <span class="math inline">\(Q=\{x\mid Ax\leq 0\}=\{0\}\)</span>.
</div>
<div class="proof">
<p><span id="unlabeled-div-31" class="proof"><em>Proof</em>. </span>See <span class="citation"><a href="#ref-goldman_56" role="doc-biblioref">Goldman</a> (<a href="#ref-goldman_56" role="doc-biblioref">1956</a>)</span>, corollary 1B.</p>
</div>
<p>If <span class="math inline">\(C\)</span> satisfies the conditions of lemma <a href="inverse-multidimensional-scaling.html#lem:goldman">22.2</a> then it is a bounded convex polyhedron and is the convex hull of its finite set of extreme vectors.</p>
<p>There are, of course, affine combinations <span class="math inline">\(\Delta\)</span> with negative elements. We could decide that we are only interested in non-negative dissimilarities. In order to deal with non-negativity we define <span class="math inline">\(\Delta_+\)</span> as the polyhedral convex cone of all symmetric, hollow, and non-negative matrices.</p>

<div class="theorem">
<span id="thm:posresult" class="theorem"><strong>Theorem 22.2  </strong></span>We have <span class="math inline">\(\Delta\in\Delta(W,X)\cap\Delta_+\)</span> if and only if there is a symmetric <span class="math inline">\(S\)</span> such that @(eq:invalldelta) holds and such that
<span class="math display">\[\begin{equation}
\mathbf{low}\ (KSK&#39;)\leq \mathbf{low}\ (W).
\end{equation}\]</span>
Thus <span class="math inline">\(\Delta(W,X)\cap\Delta_+\)</span> is a convex polyhedron, closed under non-negative linear combinations with coefficients that add up to one.
</div>
<div class="proof">
<p><span id="unlabeled-div-32" class="proof"><em>Proof</em>. </span>Follows easily from the representation in theorem <a href="inverse-multidimensional-scaling.html#thm:keyresult">22.1</a>} display = “n”)`.</p>
</div>
<p>Of course the minimum of <span class="math inline">\(\sigma(X,W,\Delta)\)</span> over <span class="math inline">\(\Delta\in\Delta(W,X)\cap\Delta_+\)</span> is zero, attained at <span class="math inline">\(D(X)\)</span>. The maximum of stress, which is a convex quadratic in <span class="math inline">\(\Delta\)</span>, is attained at one of the vertices of <span class="math inline">\(\Delta(W,X)\cap\Delta_+\)</span>.</p>

<div class="theorem">
<span id="thm:bounded" class="theorem"><strong>Theorem 22.3  </strong></span><span class="math inline">\(\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span> is bounded, i.e. it is a convex polygon.
</div>
<div class="proof">
<p><span id="unlabeled-div-33" class="proof"><em>Proof</em>. </span>This is corollary 3.2 in <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span>, but the proof given there is incorrect. A hopefully correct proof goes as follows. A polyhedron is bounded if and only if its recession cone is the zero vector. If the polyhedron is defined by <span class="math inline">\(Ax\leq b\)</span> then the recession cone is the solution set of <span class="math inline">\(Ax\leq 0\)</span>. Thus, in our case, the recession cone consists of all matrices <span class="math inline">\(S\)</span> for which <span class="math inline">\(\text{low}\ (KSK&#39;)\leq 0\)</span>. Since <span class="math inline">\(U:=KSK&#39;\)</span> is doubly-centered, and <span class="math inline">\(K\)</span> is orthogonal to <span class="math inline">\(X\)</span>, we have</p>
<p><span class="math display">\[\begin{equation}
0=\text{tr}\ X&#39;UX=2\mathop{\sum\sum}_{1\leq i&lt;j\leq n}u_{ij}d_{ij}^2(X).\
\end{equation}\]</span></p>
<p>This implies <span class="math inline">\(U=0\)</span>, and the recession cone is the zero vector.</p>
</div>
<p>We can compute the vertices of <span class="math inline">\(\Delta(W,X)\cap\Delta_+\)</span> using the complete description method of <span class="citation"><a href="#ref-fukuda_15" role="doc-biblioref">Fukuda</a> (<a href="#ref-fukuda_15" role="doc-biblioref">2015</a>)</span>, with an <code>R</code> implementation in the <code>rcdd</code> package by <span class="citation"><a href="#ref-geyer_meeden_15" role="doc-biblioref">Geyer and Meeden</a> (<a href="#ref-geyer_meeden_15" role="doc-biblioref">2015</a>)</span>. Alternatively, as a check on our computations, we also use the <code>lrs</code> method of <span class="citation"><a href="#ref-avis_15" role="doc-biblioref">Avis</a> (<a href="#ref-avis_15" role="doc-biblioref">2015</a>)</span>, with an <code>R</code> implementation in the <code>vertexenum</code> package by <span class="citation"><a href="#ref-robere_15" role="doc-biblioref">Robere</a> (<a href="#ref-robere_15" role="doc-biblioref">2015</a>)</span>. Both methods convert the <em>H-representation</em> of the polygon, as the solution set of a number of linear inequalities, to the <em>V-representation</em>, as the convex combinations of a number of vertices.</p>
<p>There is also a brute-force method of converting H to V that is somewhat wasteful, but still practical for small examples. Start with the H-representation <span class="math inline">\(Ax\leq b\)</span>, where <span class="math inline">\(A\)</span> is <span class="math inline">\(n\times m\)</span> with <span class="math inline">\(n\geq m\)</span>. Then look at all <span class="math inline">\(\binom{n}{m}\)</span> choices of <span class="math inline">\(m\)</span> rows of <span class="math inline">\(A\)</span>. Each choice partitions <span class="math inline">\(A\)</span> into the <span class="math inline">\(m\times m\)</span> matrix <span class="math inline">\(A_1\)</span> and the <span class="math inline">\((n-m)\times m\)</span> matrix <span class="math inline">\(A_2\)</span> and <span class="math inline">\(b\)</span> into <span class="math inline">\(B-1\)</span> and <span class="math inline">\(b_2\)</span>. If <span class="math inline">\(rank(A_1)&lt;m\)</span> there is no extreme point associated with this partitioning. If <span class="math inline">\(rank(A_1)=m\)</span> we compute <span class="math inline">\(\hat v=A_1^{-1}b_1\)</span> and if <span class="math inline">\(A_2\hat v\leq b_2\)</span> then we add <span class="math inline">\(\hat v\)</span> to the V representation.</p>
</div>
<div id="zero-weights-andor-distances" class="section level2" number="22.3">
<h2><span class="header-section-number">22.3</span> Zero Weights and/or Distances</h2>
<p>If a distance is zero then the corresponding element of <span class="math inline">\(B(X)\)</span> must be zero as well. If a weight is zero, then the corresponding elements of both <span class="math inline">\(V\)</span> and <span class="math inline">\(B(X)\)</span> are zero. It is still true that <span class="math inline">\((V-B)X=0\)</span> if and only if there is an <span class="math inline">\(S\)</span> such that <span class="math inline">\(B=V-KSK&#39;\)</span>, but it may no longer be possible to find the <span class="math inline">\(\Delta\)</span> corresponding with some <span class="math inline">\(V+KSK&#39;\)</span>. In other words, not all solutions <span class="math inline">\(B\)</span> to <span class="math inline">\((V-B)X=0\)</span> correspond with a proper <span class="math inline">\(B(X)\)</span>. Specifically, zero weights and/or distances imply that one or more elements of <span class="math inline">\(B\)</span> are required to be zero. If these zero requirements are taken into account then not all matrices <span class="math inline">\(S\)</span> are allowed.</p>
<p>If, for example, <span class="math inline">\(X\)</span> is</p>
<pre><code>##      [,1]
## [1,] -0.5
## [2,] -0.5
## [3,]  0.5
## [4,]  0.5</code></pre>
<p>and the weights are all one,
then <span class="math inline">\(V-B\)</span> must be a linear combination of the three matrices, say <span class="math inline">\(P_{11}, P_{22}\)</span> and <span class="math inline">\(P_{12}\)</span>,</p>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1   -1    1   -1
## [2,]   -1    1   -1    1
## [3,]    1   -1    1   -1
## [4,]   -1    1   -1    1</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1   -1   -1    1
## [2,]   -1    1    1   -1
## [3,]   -1    1    1   -1
## [4,]    1   -1   -1    1</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   -2    2    0    0
## [2,]    2   -2    0    0
## [3,]    0    0    2   -2
## [4,]    0    0   -2    2</code></pre>
<p>and <span class="math inline">\(B\)</span> is <span class="math inline">\(V\)</span> minus the linear combination. For any <span class="math inline">\(B\)</span> computed this way we have <span class="math inline">\(BX=VX\)</span>, but we have
<span class="math inline">\(b_{12}=b_{34}=0\)</span> if and only if <span class="math inline">\(B=V-\alpha P_{11} + (1-\alpha) P_{22}\)</span>.</p>
</div>
<div id="examples-1" class="section level2" number="22.4">
<h2><span class="header-section-number">22.4</span> Examples</h2>
<div id="first-example" class="section level3" number="22.4.1">
<h3><span class="header-section-number">22.4.1</span> First Example</h3>
<p>As our first example we take <span class="math inline">\(X\)</span> equal to four points in the corners of a square. This example is also used in <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span> and <span class="citation"><a href="#ref-deleeuw_U_12b" role="doc-biblioref">De Leeuw</a> (<a href="#ref-deleeuw_U_12b" role="doc-biblioref">2012</a>)</span>. Here <span class="math inline">\(X\)</span> is</p>
<pre><code>##      [,1] [,2]
## [1,] -0.5 -0.5
## [2,] -0.5  0.5
## [3,]  0.5  0.5
## [4,]  0.5 -0.5</code></pre>
<p>with distances</p>
<pre><code>##          1        2        3
## 2 1.000000                  
## 3 1.414214 1.000000         
## 4 1.000000 1.414214 1.000000</code></pre>
<p>and <span class="math inline">\(K\)</span> is the vector</p>
<pre><code>## [1] -0.5  0.5 -0.5  0.5</code></pre>
<p>For unit weights we have <span class="math inline">\(\Delta\in\Delta(X,W)\)</span> if and only if
<span class="math inline">\(\Delta=D(X)\{W-\lambda kk&#39;\}\)</span>
for some real <span class="math inline">\(\lambda\)</span>. This means that <span class="math inline">\(\Delta\in\Delta(X,W)\cap\Delta_+\)</span> if and only if <span class="math inline">\(-4\leq\lambda\leq 4\)</span>. The endpoints of this interval correspond with the two dissimilarity matrices
<span class="math display">\[
\Delta_1:=2\sqrt{2}\begin{bmatrix}0&amp;0&amp;1&amp;0\\0&amp;0&amp;0&amp;1\\1&amp;0&amp;0&amp;0\\0&amp;1&amp;0&amp;0\end{bmatrix},
\]</span>
and
<span class="math display">\[
\Delta_2:=2\begin{bmatrix}0&amp;1&amp;0&amp;1\\1&amp;0&amp;1&amp;0\\0&amp;1&amp;0&amp;1\\1&amp;0&amp;1&amp;0\end{bmatrix}.
\]</span>
Thus <span class="math inline">\(\Delta(X,W)\cap\Delta_+\)</span> are the convex combinations
<span class="math display">\[
\Delta(\alpha):=\alpha\Delta_1+(1-\alpha)\Delta_2=
\begin{bmatrix}0&amp;2(1-\alpha)&amp;2\alpha\sqrt{2}&amp;2(1-\alpha)\\2(1-\alpha)&amp;0&amp;2(1-\alpha)&amp;2\alpha\sqrt{2}\\2\alpha\sqrt{2}&amp;2(1-\alpha)&amp;0&amp;2(1-\alpha)\\2(1-\alpha)&amp;2\alpha\sqrt{2}&amp;2(1-\alpha)&amp;0\end{bmatrix}.
\]</span>
This can be thought of as the distances between points on a (generally non-Euclidean) square with sides <span class="math inline">\(2(1-\alpha)\)</span> and diagonal <span class="math inline">\(2\alpha\sqrt{2}\)</span>. The triangle inequalities are satisfied if the length of the diagonal is less than twice the length of the sides, i.e. if
<span class="math inline">\(\alpha\leq\frac{2}{2+\sqrt{2}}\approx .585786\)</span>.</p>
<p>The distances are certainly Euclidean if Pythagoras is satisfied, i.e. if the square of the length of the diagonal is twice the square of the length of the sides. This gives <span class="math inline">\(\alpha=\frac12\)</span>, for which <span class="math inline">\(\Delta=D(X)\)</span>. For a more precise analysis, observe that the two binary matrices, say <span class="math inline">\(E_1\)</span> and <span class="math inline">\(E_2\)</span>, in the definition of <span class="math inline">\(\Delta_1\)</span> and <span class="math inline">\(\Delta_2\)</span> commute, and are both diagonalized by</p>
<p><span class="math display">\[
L:=\begin{bmatrix}
\frac12&amp;\frac12\sqrt{2}&amp;0&amp;\frac12\\
\frac12&amp;0&amp;\frac12\sqrt{2}&amp;-\frac12\\
\frac12&amp;-\frac12\sqrt{2}&amp;0&amp;\frac12\\
\frac12&amp;0&amp;-\frac12\sqrt{2}&amp;-\frac12
\end{bmatrix}
\]</span></p>
<p>The diagonal elements of <span class="math inline">\(L&#39;E_1L\)</span> are <span class="math inline">\(1,-1,-1,1\)</span> and those of <span class="math inline">\(L&#39;E_2 L\)</span> are <span class="math inline">\(2,0,0,-2\)</span>. Because <span class="math inline">\(L\)</span> diagonalizes <span class="math inline">\(E_1\)</span> and <span class="math inline">\(E_2\)</span>, it also diagonalizes <span class="math inline">\(\Delta_1\)</span> and <span class="math inline">\(\Delta_2\)</span>, as well as the elementwise squares <span class="math inline">\(\Delta^2_1\)</span> and <span class="math inline">\(\Delta^2_2\)</span>. And consequently also the Torgerson transform <span class="math inline">\(-\frac12 J\Delta^2(\alpha)J\)</span>, which has eigenvalues <span class="math inline">\(0,4\alpha^2,4\alpha^2,4(1-2\alpha)\)</span>. All eigenvalues are non-negative for <span class="math inline">\(\alpha\leq\frac12\)</span>.</p>
<p>We see that
<span class="math inline">\(\Delta(\alpha)\)</span> is two-dimensional Euclidean for <span class="math inline">\(\alpha=\frac12\)</span>, one-dimensional Euclidean for <span class="math inline">\(\alpha=0\)</span>, and three-dimensional Euclidean for <span class="math inline">\(0&lt;\alpha&lt;\frac12\)</span>. In particular for <span class="math inline">\(\alpha=\frac{1}{1+\sqrt{2}}\)</span> all dissimilarities are equal and <span class="math inline">\(\Delta(\alpha)\)</span> is the distance matrix of a regular simplex.</p>
<p>On the unit interval stress is the quadratic <span class="math inline">\(32(\alpha-\frac12)^2\)</span>, which attains its maximum equal to 8 at the endpoints.</p>
</div>
<div id="second-example" class="section level3" number="22.4.2">
<h3><span class="header-section-number">22.4.2</span> Second Example</h3>
<p>We next give another small example with four equally spaced points on the line, normalized to sum of squares one, and unit weights. Thus <span class="math inline">\(X\)</span> is</p>
<pre><code>##            [,1]
## [1,] -0.6708204
## [2,] -0.2236068
## [3,]  0.2236068
## [4,]  0.6708204</code></pre>
<p>and <span class="math inline">\(D(X)\)</span> is</p>
<pre><code>##          1        2        3
## 2 3.464102                  
## 3 4.472136 2.828427         
## 4 6.324555 4.472136 3.464102</code></pre>
<p>For <span class="math inline">\(S\)</span> we use the basis <span class="math inline">\(\begin{bmatrix}1&amp;0\\0&amp;0\end{bmatrix}\)</span>, <span class="math inline">\(\begin{bmatrix}0&amp;0\\0&amp;1\end{bmatrix}\)</span>, and <span class="math inline">\(\begin{bmatrix}0&amp;1\\1&amp;0\end{bmatrix}\)</span>. Thus <span class="math inline">\(\Delta(X,W)\)</span> are the affine linear combinations of <span class="math inline">\(D(X)\)</span> and
the three matrices</p>
<pre><code>##          1        2        3
## 2 4.330127                  
## 3 5.590170 2.121320         
## 4 4.743416 5.590170 4.330127</code></pre>
<pre><code>##          1        2        3
## 2 3.983717                  
## 3 3.801316 4.101219         
## 4 6.640783 3.801316 3.983717</code></pre>
<pre><code>##          1        2        3
## 2 1.914908                  
## 3 5.472136 2.828427         
## 4 6.324555 3.472136 5.013295</code></pre>
<p>Both <code>scdd()</code> from <code>rcdd</code> and <code>enumerate.vertices()</code> from <code>vertexenum</code> find the same seven vertices. All non-negative dissimilarity matrices for which <span class="math inline">\(x\)</span> is stationary are convex combinations of these seven matrices.</p>
<pre><code>##           1         2         3
## 2 20.784610                    
## 3  0.000000  5.656854          
## 4  0.000000 13.416408  0.000000
##           1         2         3
## 2 13.856406                    
## 3  4.472136  0.000000          
## 4  0.000000 13.416408  0.000000
##          1        2        3
## 2 20.78461                  
## 3  0.00000 22.62742         
## 4  0.00000  0.00000 20.78461
##           1         2         3
## 2  0.000000                    
## 3 13.416408  5.656854          
## 4  0.000000  0.000000 20.784610
##           1         2         3
## 2  0.000000                    
## 3 13.416408  0.000000          
## 4  0.000000  4.472136 13.856406
##          1        2        3
## 2 0.000000                  
## 3 4.472136 0.000000         
## 4 8.432738 4.472136 0.000000
##           1         2         3
## 2  0.000000                    
## 3  0.000000  5.656854          
## 4 12.649111  0.000000  0.000000</code></pre>
<p>The stress values for these seven vertices are</p>
<pre><code>## [1]  460.00000  248.00000 1072.00000  460.00000  248.00000   36.44444  112.00000</code></pre>
<p>and we know that 1072 is the maximum of stress over <span class="math inline">\(\Delta\in\Delta(X,W)\cap\Delta_+\)</span>.</p>
<p>In general the vanishing of the stationary equations does not imply that <span class="math inline">\(X\)</span> corresponds with a local minimum. It can also give a local maximum or a saddle point. We know, however, that the only local maximum of stress is the origin (<span class="citation"><a href="#ref-deleeuw_groenen_mair_E_16e" role="doc-biblioref">De Leeuw, Groenen, and Mair</a> (<a href="#ref-deleeuw_groenen_mair_E_16e" role="doc-biblioref">2016a</a>)</span>), and that in the one-dimensional case all solutions of the stationary equations that do not have tied coordinates are local minima (<span class="citation"><a href="#ref-deleeuw_C_05h" role="doc-biblioref">De Leeuw</a> (<a href="#ref-deleeuw_C_05h" role="doc-biblioref">2005c</a>)</span>).</p>
</div>
<div id="third-example" class="section level3" number="22.4.3">
<h3><span class="header-section-number">22.4.3</span> Third Example</h3>
<p>The number of extreme points of the polytope <span class="math inline">\(\Delta(W,X)\cap\Delta_+\)</span> grows very quickly if the problem becomes larger. In our next example we take six points equally spaced on the unit sphere. Due to the intricacies of floating point comparisons (testing for zero, testing for equality)
it can be difficult to determine exactly how many extreme points there are.</p>
<p><span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span> analyzed this example and found 42 extreme points. We repeat their analysis with our <code>R</code> function <code>bruteForce()</code> from the code section.
We select <span class="math inline">\(\binom{15}{6}=5005\)</span> sets of six linear equations from our 15 linear inequalities, test them for non-singularity, and solve them to see if they satisfy the remaining nine inequalities. This gives 1394 extreme points of the polytope, but many of them are duplicates. We use
our function <code>cleanUp()</code> to remove duplicates, which leaves 42 vertices, same number as found by <span class="citation"><a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">De Leeuw and Groenen</a> (<a href="#ref-deleeuw_groenen_A_97" role="doc-biblioref">1997</a>)</span>. The 42 stress values are</p>
<pre><code>##  [1] 24.00000 24.00000 24.00000 21.75000 12.00000 13.33333  6.66667 13.33333
##  [9] 17.33333 17.33333 19.68000 13.33333  6.66667 17.33333  6.66667 21.75000
## [17]  6.66667 60.00000 24.00000 21.75000 19.68000 17.33333 21.75000 13.33333
## [25] 19.68000 17.33333 17.33333 21.75000 17.33333 17.33333 13.33333  6.66667
## [33] 21.75000 17.33333 19.68000 13.33333 17.33333 19.68000 19.68000 17.33333
## [41]  6.66667 17.33333</code></pre>
<p>and their maximum is 60.</p>
<p>If we perform the calculations more efficiently in <code>rcdd</code>, using rational arithmetic, we come up with a list of 153 extreme points. Using <code>cleanUp()</code> to remove what seem to be duplicates leaves 43.
The <code>vertexenum</code> package, which uses a different conversion from float to rational and back, finds 147 extreme points, and removing what seem to be duplicates leaves 51.</p>
<p>The fact that we get different numbers of vertices with different methods is somewhat disconcerting. We test the vertices found by <code>rcdd</code> and <code>vertexenum</code> that are not found with the brute force method by using our function <code>rankTest()</code>. This test is based on the fact that a vector <span class="math inline">\(x\)</span>
satisfying the <span class="math inline">\(n\times m\)</span> system <span class="math inline">\(Ax\leq b\)</span> is an extreme point if and only if matrix with all rows <span class="math inline">\(a_i\)</span> for which <span class="math inline">\(a_i&#39;x=b_i\)</span> is of
rank <span class="math inline">\(m\)</span>. It turns out all the additional vertices found by <code>rcdd</code> and <code>vertexenum</code> do not satisfy this rank test, because the matrix of active constraints (satisfied as equalities) is of rank 5.</p>
</div>
<div id="fourth-example" class="section level3" number="22.4.4">
<h3><span class="header-section-number">22.4.4</span> Fourth Example</h3>
<p>This is an unfolding example with <span class="math inline">\(n=3+3\)</span> points, configuration</p>
<pre><code>##            [,1]       [,2]
## [1,]  0.0000000  0.0000000
## [2,]  0.0000000  0.0000000
## [3,]  0.0000000 -0.8164966
## [4,]  0.0000000  0.4082483
## [5,]  0.7071068  0.0000000
## [6,] -0.7071068  0.4082483</code></pre>
<p>and weight matrix</p>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    0    0    0    1    1    1
## [2,]    0    0    0    1    1    1
## [3,]    0    0    0    1    1    1
## [4,]    1    1    1    0    0    0
## [5,]    1    1    1    0    0    0
## [6,]    1    1    1    0    0    0</code></pre>
<p>Note that row-points one and two in <span class="math inline">\(X\)</span> are equal, and thus <span class="math inline">\(d_{12}(X)=0\)</span>. The example has both zero weights and zero distances. We now require that <span class="math inline">\((V-B(X))X=0\)</span>, but also that the elements of <span class="math inline">\(B(X)\)</span> in the two <span class="math inline">\(3\times 3\)</span> principal submatrices corresponding with the rows and columns are zero. This means that for the elements of <span class="math inline">\(B(X)\)</span> we require <span class="math inline">\(k_i&#39;Sk_j\leq 1\)</span> for <span class="math inline">\(w_{ij}=1\)</span> and both <span class="math inline">\(k_i&#39;Sk_j\leq 0\)</span> and <span class="math inline">\(-k_i&#39;Sk_j\leq 0\)</span> for <span class="math inline">\(w_{ij}=0\)</span>. We can then solve for edges of the off-diagonal block of dissimilarities. There are no constraints on the dissimilarities in the
diagonal blocks, because they are not part of the MDS problem.</p>
<p>Using our brute force method, we find the two edges</p>
<pre><code>##           4        5        6
## 1 0.0000000 1.414214 1.632993
## 2 0.8164966 0.000000 0.000000
## 3 1.2247449 1.080123 1.414214</code></pre>
<pre><code>##           4        5        6
## 1 0.8164966 0.000000 0.000000
## 2 0.0000000 1.414214 1.632993
## 3 1.2247449 1.080123 1.414214</code></pre>
<p>and the off-diagonal blocks for which <span class="math inline">\(X\)</span> is an unfolding solution are convex combinations of these two.</p>
</div>
</div>
<div id="mds-sensitivity" class="section level2" number="22.5">
<h2><span class="header-section-number">22.5</span> MDS Sensitivity</h2>
<p>Suppose <span class="math inline">\(X\)</span> is a solution to the MDS problem with dissimilarities <span class="math inline">\(\Delta\)</span>, found by some iterative algorithm such as <code>smacof</code>. We can then compute <span class="math inline">\(\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span>, which is a convex neighborhood of the data <span class="math inline">\(\Delta\)</span>, and consists of all non-negative dissimilarity matrices that have <span class="math inline">\(X\)</span> as a solution to the stationary equations. The size of this convex neighborhood can be thought of as a measure of <em>stability</em> or <em>sensitivity</em>.</p>
<p>For typical MDS examples there is no hope of computing all vertices of <span class="math inline">\(\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span>. Consider the data from <span class="citation"><a href="#ref-degruijter_67" role="doc-biblioref">De Gruijter</a> (<a href="#ref-degruijter_67" role="doc-biblioref">1967</a>)</span>, for example, with
<span class="math inline">\(n=9\)</span> objects, to be scaled in <span class="math inline">\(p=2\)</span> dimensions. We have <span class="math inline">\(\frac12 n(n-1)=36\)</span> dissimilarities, and because <span class="math inline">\(m=n-p-1=6\)</span> there are
<span class="math inline">\(\frac12 m(m+1)=21\)</span> variables. It suffices to consider that there are 5567902560 ways in which we can pick 21 rows from 36 rows to understand the number of potential vertices.</p>
<p>What we can do, however, is to optimize linear (or quadratic functions) over <span class="math inline">\(\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span>, because 36 linear inequalities in
21 variables define an easily manageable LP (or QP) problem. As an example, not necessarily a very sensible one, we solve 36 linear programs to maximize and minimize each of the <span class="math inline">\(\delta_{ij}\)</span> in <span class="math inline">\(\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span> separately. We use the <code>lpSolve</code> package (<span class="citation"><a href="#ref-berkelaar_15" role="doc-biblioref">Berkelaar, M. and others</a> (<a href="#ref-berkelaar_15" role="doc-biblioref">2015</a>)</span>), and collect the maximum and minimum <span class="math inline">\(\delta_{ij}\)</span> in a matrix. The range from the smallest possible
<span class="math inline">\(\delta_{ij}\)</span> to the largest possible <span class="math inline">\(\delta_{ij}\)</span> turns out to be quite large.</p>
<p>The data are</p>
<pre><code>##       KVP PvdA  VVD  ARP  CHU  CPN  PSP   BP  D66
## KVP  0.00 5.63 5.27 4.60 4.80 7.54 6.73 7.18 6.17
## PvdA 5.63 0.00 6.72 5.64 6.22 5.12 4.59 7.22 5.47
## VVD  5.27 6.72 0.00 5.46 4.97 8.13 7.55 6.90 4.67
## ARP  4.60 5.64 5.46 0.00 3.20 7.84 6.73 7.28 6.13
## CHU  4.80 6.22 4.97 3.20 0.00 7.80 7.08 6.96 6.04
## CPN  7.54 5.12 8.13 7.84 7.80 0.00 4.08 6.34 7.42
## PSP  6.73 4.59 7.55 6.73 7.08 4.08 0.00 6.88 6.36
## BP   7.18 7.22 6.90 7.28 6.96 6.34 6.88 0.00 7.36
## D66  6.17 5.47 4.67 6.13 6.04 7.42 6.36 7.36 0.00</code></pre>
<p>The optimal configuration found by <code>smacof</code> is</p>
<pre><code>##        [,1]   [,2]
##  [1,]  1.78  3.579
##  [2,] -1.46  2.297
##  [3,]  3.42 -2.776
##  [4,]  3.30  1.837
##  [5,]  3.84  0.308
##  [6,] -5.09 -0.044
##  [7,] -3.79  2.132
##  [8,] -2.86 -4.318
##  [9,]  0.86 -3.015</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:poldistconfplot"></span>
<img src="_main_files/figure-html/poldistconfplot-1.png" alt="De Gruijter Configuration" width="672" />
<p class="caption">
Figure 22.1: De Gruijter Configuration
</p>
</div>
<p>The maximum and minimum dissimilarities in <span class="math inline">\(\Delta(X,W)\cap\Delta_+\)</span> are</p>
<pre><code>##      KVP   PvdA  VVD   ARP   CHU   CPN   PSP   BP    D66  
## KVP    0.0  32.6   9.7   9.3  24.6  24.3  11.7  18.9  15.2
## PvdA  32.6   0.0  25.7  36.9  20.7  34.1  36.1  29.7  22.2
## VVD    9.7  25.7   0.0  17.4  32.0  34.4  22.3  23.5  20.4
## ARP    9.3  36.9  17.4   0.0  28.0  33.7  25.6  28.9  23.0
## CHU   24.6  20.7  32.0  28.0   0.0  20.8  31.9  33.3  26.3
## CPN   24.3  34.1  34.4  33.7  20.8   0.0  24.9  30.7  31.8
## PSP   11.7  36.1  22.3  25.6  31.9  24.9   0.0  23.7  27.7
## BP    18.9  29.7  23.5  28.9  33.3  30.7  23.7   0.0  35.0
## D66   15.2  22.2  20.4  23.0  26.3  31.8  27.7  35.0   0.0</code></pre>
<pre><code>##      KVP   PvdA  VVD   ARP   CHU   CPN   PSP   BP    D66  
## KVP   0.00  3.48  0.00  0.00  2.34  0.00  0.00  0.00  0.00
## PvdA  3.48  0.00  0.00  0.00  0.00  0.00  0.93  0.00  0.00
## VVD   0.00  0.00  0.00  0.00  0.83  0.00  0.00  0.00  0.00
## ARP   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00
## CHU   2.34  0.00  0.83  0.00  0.00  0.00  0.00  0.00  0.00
## CPN   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00
## PSP   0.00  0.93  0.00  0.00  0.00  0.00  0.00  0.00  0.00
## BP    0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00
## D66   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00</code></pre>
</div>
<div id="second-order-inverse-mds" class="section level2" number="22.6">
<h2><span class="header-section-number">22.6</span> Second Order Inverse MDS</h2>
<p>As we mentioned many times before, stationary values are not necessarily local minima. It is necessary for a local minimum that the stationary equations are satisfied, but it is also necessary that at a solution of the stationary equations the Hessian is positive semi-definite. Thus it becomes interesting to find the dissimilarities in <span class="math inline">\(\Delta(W,X)\cap\Delta_+\)</span> for which the Hessian is positive semi-definite. Define
<span class="math display">\[
\Delta_H(W,X):=\{\Delta\mid\mathcal{D}^2\sigma(X)\gtrsim 0\}.
\]</span>
We can now study <span class="math inline">\(\Delta(W,X)\cap\Delta_H(W,X)\)</span> or <span class="math inline">\(\Delta(W,X)\cap\Delta_H(W,X)\cap\Delta_+\)</span>.</p>

<div class="theorem">
<span id="thm:invconvset" class="theorem"><strong>Theorem 22.4  </strong></span><span class="math inline">\(\Delta_H(W,X)\)</span> is a convex non-polyhedral set.
</div>
<div class="proof">
<p><span id="unlabeled-div-34" class="proof"><em>Proof</em>. </span>In MDS the Hessian is <span class="math inline">\(2(V-H(x,W,\Delta))\)</span>, where
<span class="math display">\[\begin{equation}
H(x,W,\Delta):=\mathop{\sum\sum}_{1\leq i&lt;j\leq n}w_{ij}\frac{\delta_{ij}}{d_{ij}(x)}\left\{A_{ij}-\frac{A_{ij}xx&#39;A_{ij}}{x&#39;A_{ij}x}\right\}.
\end{equation}\]</span>
Here we use <span class="math inline">\(x:=\mathbf{vec}(X)\)</span>, and both <span class="math inline">\(A_{ij}\)</span> and <span class="math inline">\(V\)</span> are direct sums of <span class="math inline">\(p\)</span> copies of our previous <span class="math inline">\(A_{ij}\)</span> and <span class="math inline">\(V\)</span> (<span class="citation"><a href="#ref-deleeuw_groenen_mair_E_16c" role="doc-biblioref">De Leeuw, Groenen, and Mair</a> (<a href="#ref-deleeuw_groenen_mair_E_16c" role="doc-biblioref">2016e</a>)</span>). The Hessian is linear in <span class="math inline">\(\Delta\)</span>, which means that requiring it to be positive semi-definite defines a convex non-polyhedral set. The convex set is defined by the infinite system of linear inequalities <span class="math inline">\(y&#39;H(x,W,\Delta)y\geq 0\)</span>.</p>
</div>
<p>In example 3 the smallest eigenvalues of the Hessian at the 42 vertices are</p>
<pre><code>##  [1]   0.00000   0.00000   0.00000  -5.86238   0.00000  -2.96688   0.00000
##  [8]  -2.96688  -4.47894  -4.47894  -5.71312  -2.96688   0.00000  -5.00453
## [15]   0.00000  -5.86238   0.00000 -12.00000   0.00000  -5.86238  -5.71312
## [22]  -5.00453  -5.86238  -2.96688  -5.71312  -4.47894  -5.00453  -5.86238
## [29]  -5.00453  -5.00453  -2.96688   0.00000  -5.86238  -4.47894  -5.71312
## [36]  -2.96688  -5.00453  -5.71312  -5.71312  -4.47894   0.00000  -4.47894</code></pre>
<p>and thus there are at most 11 vertices corresponding with local minima.</p>
<p>The next step is to refine the polyhedral approximation to <span class="math inline">\(\Delta(W,X)\cap\Delta_H(W,X)\cap\Delta_+\)</span> by using cutting planes. We add linear inequalities to the H-representation by using the eigenvectors corresponding to the smallest eigenvalues of all
those vertices for which this smallest eigenvalue is negative. Thus, if the eigenvector is <span class="math inline">\(y\)</span>, we would add the inequality
<span class="math display">\[\begin{equation}
\mathop{\sum\sum}_{1\leq i&lt;j\leq n}\zeta_{ij}(w_{ij}-k_i&#39;Sk_j)\geq 0,
\end{equation}\]</span>
where
<span class="math display">\[
\zeta_{ij}:=y&#39;\left(A_{ij}-\frac{A_{ij}xx&#39;A_{ij}}{x&#39;A_{ij}x}\right)y.
\]</span>
It is clear, however, that adding a substantial number of linear inequalities will inevitably lead to a very large number of potential extreme points. We proceed conservatively by cutting off only the solution with the smallest negative eigenvalue in computing the new V representation, using our function <code>bruteForceOne()</code>.</p>
</div>
<div id="inverse-fds" class="section level2" number="22.7">
<h2><span class="header-section-number">22.7</span> Inverse FDS</h2>
<p>A configuration <span class="math inline">\(X\)</span> is a <em>full dimensional scaling</em> or <em>FDS</em> solution (<span class="citation"><a href="#ref-deleeuw_groenen_mair_E_16e" role="doc-biblioref">De Leeuw, Groenen, and Mair</a> (<a href="#ref-deleeuw_groenen_mair_E_16e" role="doc-biblioref">2016a</a>)</span>) if <span class="math inline">\((V-B(X))X=0\)</span> and <span class="math inline">\(V-B(X)\)</span> is positive semi-definite. In that case <span class="math inline">\(X\)</span> actually provides the global minimum of stress. The <em>inverse FDS</em> or <em>iFDS</em> problem is to find all <span class="math inline">\(\Delta\)</span> such that a given <span class="math inline">\(X\)</span> is the FDS solution.</p>
<p><code>{theorem&lt; label = "invfull"} $\Delta\in\Delta_F(W,X)$ if and only if there is a positive semi-definite $S$ such that for all $i\not= j$  \begin{equation} \delta_{ij}=d_{ij}(X)(1-\frac{1}{w_{ij}}k_i'Sk_j), \end{equation} Thus $\Delta_F(W,X)$ is a non-polyhedral convex set, closed under linear combinations with coefficients that add up to one.</code></p>
<div class="proof">
<p><span id="unlabeled-div-35" class="proof"><em>Proof</em>. </span>Of course <span class="math inline">\(\Delta_F(W,X)\subseteq\Delta(W,X)\)</span>. Thus <span class="math inline">\(V-B(X)=KSK&#39;\)</span> for some <span class="math inline">\(S\)</span>, and <span class="math inline">\(XX&#39;\)</span> and <span class="math inline">\(V-B(X)\)</span> must both be positive semi-definite, with complementary null spaces.</p>
</div>
<p>We reanalyze our second example, with the four points equally spaced on the line, requiring a positive semi-definite <span class="math inline">\(S\)</span>. We start with the original 7 vertices, for which the minimum eigenvalues of <span class="math inline">\(S\)</span> are</p>
<pre><code>## [1] -4.000 -2.899 -1.708 -3.333  8.000 -1.708 -2.899</code></pre>
<p>If the minimum eigenvalue is negative, with eigenvector <span class="math inline">\(y\)</span>, we add the constraints <span class="math inline">\(y&#39;Sy\geq 0\)</span>. This leads to 11 vertices with minimum eigenvalues</p>
<pre><code>##  [1]  8.0000 -0.0355  0.0000 -0.7911 -0.3834 -0.3834 -0.0355 -0.0853 -0.0853
## [10] -0.7911  0.0000</code></pre>
<p>We see that the negative eigenvalues are getting smaller. Repeating the procedure of adding constraints based on negative eigenvalues three more times gives 19, 37, and 79 vertices, with corresponding minimum eigenvalues</p>
<pre><code>##  [1]  8.000000 -0.000021  0.000000 -0.209852 -0.202322 -0.085642 -0.085642
##  [8] -0.000021 -0.106132 -0.018912 -0.008051 -0.023967 -0.008051 -0.023967
## [15] -0.106132 -0.018912 -0.209852 -0.202322  0.000000</code></pre>
<pre><code>##  [1]  8.000000 -0.000021  0.000000 -0.056872 -0.053562 -0.045307 -0.062028
##  [8] -0.020853 -0.020853 -0.000021 -0.028793 -0.004490 -0.001925 -0.006410
## [15] -0.001925 -0.006410 -0.028793 -0.004490 -0.000005 -0.002104 -0.021934
## [22] -0.024355 -0.021934 -0.024355 -0.000005 -0.002104 -0.004975 -0.005596
## [29] -0.005596 -0.004975 -0.002318 -0.002318 -0.056872 -0.053562 -0.045307
## [36] -0.062028  0.000000</code></pre>
<pre><code>##  [1]  8.000000 -0.000021  0.000000 -0.015026 -0.013698 -0.010861 -0.017838
##  [8] -0.013830 -0.013426 -0.012084 -0.013998 -0.018140 -0.005180 -0.005180
## [15] -0.000021 -0.007568 -0.001096 -0.000471 -0.001662 -0.000471 -0.001662
## [22] -0.007568 -0.001096 -0.000005 -0.000001 -0.000538 -0.000488 -0.005588
## [29] -0.005886 -0.005588 -0.005886 -0.000005 -0.000001 -0.000538 -0.000488
## [36] -0.001278 -0.001355 -0.001355 -0.001278 -0.000001 -0.000649 -0.000594
## [43] -0.005244 -0.005378 -0.005244 -0.005378 -0.000001 -0.000649 -0.000594
## [50] -0.006838 -0.006293 -0.001150 -0.001210 -0.000492 -0.000514 -0.000566
## [57] -0.001545 -0.001444 -0.000492 -0.000514 -0.000566 -0.001545 -0.001444
## [64] -0.006838 -0.006293 -0.001150 -0.001210 -0.000001 -0.000001 -0.015026
## [71] -0.013698 -0.010861 -0.017838 -0.013830 -0.013426 -0.012084 -0.013998
## [78] -0.018140  0.000000</code></pre>
<p>It should be noted that the last step already takes an uncomfortable number of minutes to compute. Although the number of vertices goes up
quickly, the diameter of the polygon (the maximum distance between two vertices) slowly goes down and will eventually converge to the diameter
of <span class="math inline">\(\Delta_F(W,X)\cap\Delta_+\)</span>. Diameters in subsequent steps are</p>
<pre><code>## [1] 5.657 5.086 5.065 5.061 5.060</code></pre>
</div>
<div id="multiple-solutions" class="section level2" number="22.8">
<h2><span class="header-section-number">22.8</span> Multiple Solutions</h2>
<p>If <span class="math inline">\(X_1,\cdots,X_s\)</span> are configurations with the same number of points, then the intersection <span class="math inline">\(\left\{\bigcap_{r=1}^s\Delta(W,X_r)\right\}\cap\Delta_+\)</span> is again a polygon, i.e. a closed and bounded convex polyhedron (which may be empty). If <span class="math inline">\(\Delta\)</span> is in this intersection then <span class="math inline">\(X_1,\cdots,X_s\)</span> are all solutions of the stationary equations for this <span class="math inline">\(\Delta\)</span> and <span class="math inline">\(W\)</span>.</p>
<p>Let’s look at the case of two configurations <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>. We must find vectors <span class="math inline">\(t_1\)</span> and <span class="math inline">\(t_2\)</span> such that
<span class="math display">\[
d_1\circ(e-w^\dagger\circ G_1t_1)=d_2\circ(e-w^\dagger\circ G_2t_2).
\]</span>
If <span class="math inline">\(H_1:=\mathbf{diag}(d_1\circ w^\dagger)G_1\)</span> and <span class="math inline">\(H_2:=\mathbf{diag}(d_2\circ w^\dagger)G_2\)</span> then this can be written as
<span class="math display">\[
\begin{bmatrix}H_1&amp;-H_2\end{bmatrix}\begin{bmatrix}t_1\\t_2\end{bmatrix}=d_1-d_2
\]</span>
This is a system of linear equations in <span class="math inline">\(t_1\)</span> and <span class="math inline">\(t_2\)</span>. If it is solvable we can intersect it with the convex sets <span class="math inline">\(G_1t_1\leq w\)</span> and <span class="math inline">\(G_2t_2\leq w\)</span> to find the non-negative dissimilarity matrices <span class="math inline">\(\Delta\)</span> for which both <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are stationary.</p>
<pre><code>## $delta1
##          [,1]
## [1,] 1.464102
## [2,] 1.464102
## [3,] 1.464102
## [4,] 1.464102
## [5,] 1.464102
## [6,] 1.464102
## 
## $delta2
##          [,1]
## [1,] 1.464102
## [2,] 1.464102
## [3,] 1.464102
## [4,] 1.464102
## [5,] 1.464102
## [6,] 1.464102
## 
## $res
## [1] 1.024137e-15
## 
## $rank
## [1] 2</code></pre>
<p>As a real simple example, suppose <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are four by two. They both have three points in the corners of an equilateral triangle, and one point in the centroid of the other three. In <span class="math inline">\(X\)</span> the fourth point is in the middle, in <span class="math inline">\(Y\)</span> the first point. The only solution to the linear equations is the matrix with all dissimilarities equal.</p>
<p>For a much more complicated example we can choose the De Gruijter data. We use <code>smacof</code> to find two stationary points in two dimensions. The matrices <span class="math inline">\(G_1\)</span> and <span class="math inline">\(G_2\)</span> are <span class="math inline">\(36\times 21\)</span>, and thus <span class="math inline">\(H:=(H_1\mid -H_2)\)</span> is <span class="math inline">\(36\times 42\)</span>. The solutions of the linear system <span class="math inline">\(Ht=d_1-d_2\)</span> are of the form
<span class="math inline">\(t_0-Lt\)</span>, with <span class="math inline">\(t_0\)</span> an arbitrary solution and <span class="math inline">\(L\)</span> a <span class="math inline">\(42\times 6\)</span> basis for the space of <span class="math inline">\(Ht=0\)</span>. To find the non-negative solutions we can use the H representation <span class="math inline">\(Lv\leq t_0\)</span>, and then compute the V representation, realizing of course that we can choose 6 rows from 42 rows in 5245786 ways.</p>
</div>
<div id="minimizing-istress" class="section level2" number="22.9">
<h2><span class="header-section-number">22.9</span> Minimizing iStress</h2>
<p>The IMDS approach can also be used to construct an alternative MDS loss function. We call it <em>iStress</em>, defined as</p>
<p><span class="math display">\[
\sigma_\iota(X,W,\Delta):=\min_{\tilde\Delta\in\Delta(W,X)\cap\Delta_+}\mathop{\sum\sum}_{1\leq i&lt;j\leq n}w_{ij}(\delta_{ij}-\tilde\delta_{ij})^2.
\]</span></p>
<p>Minimizing iStress means minimizing the projection distance between the observed dissimilarity matrix and the moving convex set of non-negative dissimilarity matrices for which <span class="math inline">\(X\)</span> satisfies the stationary equations. The convex set is moving, because it depends on <span class="math inline">\(X\)</span>. For each <span class="math inline">\(X\)</span> we have to solve the IMDS problem of finding <span class="math inline">\(\Delta(X,W)\cap\Delta_+\)</span>, and then solve the quadratic programming problem that computes the projection.</p>

<div class="theorem">
<span id="thm:invistress" class="theorem"><strong>Theorem 22.5  </strong></span><span class="math inline">\(\min_X\sigma_\iota(X,W,\Delta)=0\)</span> and the minimum is attained at all <span class="math inline">\(X\)</span> with <span class="math inline">\((V-B(X))X=0\)</span>.
</div>
<div class="proof">
<p><span id="unlabeled-div-36" class="proof"><em>Proof</em>. </span>If <span class="math inline">\(X\)</span> is a stationary point of stress then <span class="math inline">\(\Delta\in\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span> and thus iStress is zero. Conversely, if iStress is zero then <span class="math inline">\(\Delta\in\mathfrak{D}(X)\cap\mathfrak{D}_+\)</span> and <span class="math inline">\(X\)</span> is a stationary point of stress.</p>
</div>
<p>Minimizing iStress may not be a actual practical MDS method, but it has some conceptual interest, because it provides another way of looking at the relationship of MDS and IMDS.</p>
<p>We use the De Gruijter data for an example of iStress minimization. We use <code>optim</code> from base <code>R</code>, and the <code>quadprog</code> package of <span class="citation"><a href="#ref-turlach_weingessel_13" role="doc-biblioref">Turlach and Weingessel</a> (<a href="#ref-turlach_weingessel_13" role="doc-biblioref">2013</a>)</span>. Two different solutions are presented, the first with iterations starting at the classical MDS solution, the second starting at the <code>smacof</code> solution. In both cases iStress converges to zero, i.e. the configurations converge to a solution of the stationary equations for stress, and in the <code>smacof</code> case the initial solution already has stress equal to zero.</p>
<pre><code>## initial  value 106.624678 
## iter  10 value 0.205734
## iter  20 value 0.025163
## iter  30 value 0.018427
## iter  40 value 0.000116
## iter  50 value 0.000007
## iter  60 value 0.000000
## final  value 0.000000 
## converged</code></pre>
<pre><code>## initial  value 0.000000 
## iter  10 value 0.000000
## iter  20 value 0.000000
## final  value 0.000000 
## converged</code></pre>
<hr>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:istressplot"></span>
<img src="_main_files/figure-html/istressplot-1.png" alt="De Gruijter Minimim iStress Configuration" width="672" />
<p class="caption">
Figure 22.2: De Gruijter Minimim iStress Configuration
</p>
</div>
</div>
<div id="order-three" class="section level2" number="22.10">
<h2><span class="header-section-number">22.10</span> Order three</h2>
<p>We will now consider, in some detail, MDS of a dissimilarity matrix of order three..
The plan is as follows. Our MDS problem is of order three, i.e. there are only three objects, and three dissimilarities between them. Suppose, for simplicity, that all weights are one. At a stationary point of we have <span class="math inline">\(B(X)X=3X\)</span>. Thus the <span class="math inline">\(B\)</span> matrix has an eigenvalue equal to <span class="math inline">\(3\)</span> (in addition to having an eigenvalue equal to zero).</p>
<p>!! Not just eval 3, but also evecs X</p>
<p>If there are only three objects we can look at the set of doubly-centered matrices of order three with an eigenvalue equal to three. If three is the largest eigenvalue then the local minimum is global, if it is the second largest eigenvalue then it may or may not be global. If <span class="math inline">\(B\)</span> has two eigenvalues equal to three, then <span class="math inline">\(B=3J\)</span> and the two eigenvectors give the unique global minimum in two dimensions (an equilateriaL triangle).</p>
<p>A symmetric doubly-centered matrix of order three is a linear combination <span class="math inline">\(B=\alpha A_{12}+\beta A_{13}+\gamma A_{23}\)</span>
of three diff matrices (<a href="mathadd.html#difmat">25.2.3</a>), with <span class="math inline">\(\alpha, \beta, \gamma\)</span> all non-negative. Thus</p>
<p><span class="math display" id="eq:bgeneral">\[\begin{equation}
B=\begin{bmatrix}
\alpha+\beta&amp;-\alpha&amp;-\beta\\
-\alpha&amp;\alpha+\gamma&amp;-\gamma\\
-\beta&amp;-\gamma&amp;\beta+\gamma
\end{bmatrix}.
\tag{22.4}
\end{equation}\]</span></p>
<p><span class="math inline">\(B\)</span> has one eigenvalue equal to zero, and two real non-negative eigenvalues <span class="math inline">\(\lambda_1\)</span> and <span class="math inline">\(\lambda_2\)</span>. The characteristic equation is
<span class="math inline">\(f(\lambda):=\lambda(\lambda^2-2\tau\lambda+3\eta)=0,\)</span>
where <span class="math inline">\(\tau:=\alpha+\beta+\gamma\)</span> and
<span class="math inline">\(\eta:=\alpha\beta+\alpha\gamma+\beta\gamma.\)</span></p>
<p>Thus we have at least one eigenvalue equal to three if <span class="math inline">\(f(3)=0\)</span>, i.e. <span class="math inline">\(2\tau-\eta=3\)</span>. Both eigenvalues are equal to three if <span class="math inline">\(\eta=\tau=3\)</span>, which means <span class="math inline">\(\alpha=\beta=\gamma=1\)</span> and <span class="math inline">\(B=3J\)</span>.</p>
<p>The two eigenvalues are <span class="math inline">\(\tau\pm\sqrt{\tau^2-3\eta}\)</span>
Note that <span class="math inline">\(\tau^2-3\eta\geq 0\)</span> with equality if and only if
<span class="math inline">\(\tau=\eta=3\)</span> if and only if <span class="math inline">\(\alpha=\beta=\gamma=1\)</span>. This easily follows from <span class="math inline">\(\tau^2-3\eta=\alpha^2+\beta^2+\gamma^2-\eta\)</span>, while
<span class="math inline">\(\eta=\alpha\beta+\alpha\gamma+\beta\gamma\leq\alpha^2+\beta^2+\gamma^2\)</span> by applying AM/GM three times. Also note that if two out of the three of
<span class="math inline">\(\alpha,\beta,\gamma\)</span> are zero then <span class="math inline">\(\eta=0\)</span> and thus <span class="math inline">\(\lambda_1=2\tau\)</span>
and <span class="math inline">\(\lambda_2=0\)</span>.</p>
<p>Since <span class="math inline">\(\lambda_1\geq\lambda_2\)</span> we have the two possibilities <span class="math inline">\(\lambda_2\leq\lambda_1=3\)</span>
and <span class="math inline">\(3\geq\lambda_1\geq\lambda_2=3\)</span>
Now <span class="math inline">\(\lambda_1=3\)</span> iff <span class="math inline">\(\sqrt{\tau^2-3\eta}=3-\tau\)</span> iff <span class="math inline">\(\tau\leq 3\)</span> and <span class="math inline">\(2\tau-\eta=3\)</span>. And <span class="math inline">\(\lambda_2=3\)</span> iff <span class="math inline">\(\sqrt{\tau^2-3\eta}=\tau-3\)</span> iff <span class="math inline">\(\tau\geq 3\)</span> and <span class="math inline">\(2\tau-\eta=3\)</span>. It also follows that it is necessary for
<span class="math inline">\(\lambda=3\)</span> that <span class="math inline">\(\tau\geq\frac32\)</span>.</p>
<p>If we have <span class="math inline">\((\tau,\eta)\)</span> we can solve for <span class="math inline">\(\alpha,\beta\)</span> and <span class="math inline">\(\gamma\)</span> by
<span class="math display">\[
\alpha+\beta+\gamma=\tau,\\
\alpha^2+\beta^2+\gamma^2=\omega
\]</span>
Thus the set of <span class="math inline">\((\alpha,\beta,\gamma)\)</span> corresponding with
<span class="math inline">\(\tau,\eta\)</span> is the intersection of a sphere and an equilateral triangle in the
non-negative orthant of <span class="math inline">\(\mathbb{R}^3\)</span>.</p>
<p><span class="math display">\[
\gamma=\tau-\alpha-\beta\\
\alpha^2+\beta^2-\tau\alpha-\tau\beta+\alpha\beta=-\eta
\]</span></p>
<p>ellipse with center <span class="math inline">\(\frac13\tau e\)</span> and radius <span class="math inline">\(\frac13(\tau-3)^2\)</span></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="inverse-multidimensional-scaling.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">imdsSolver</span>(<span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="inverse-multidimensional-scaling.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">imdsSolver</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="inverse-multidimensional-scaling.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">imdsSolver</span>(<span class="dv">3</span>)</span>
<span id="cb60-2"><a href="inverse-multidimensional-scaling.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span> (<span class="dv">1</span>, <span class="dv">1</span>, <span class="at">col =</span> <span class="st">&quot;RED&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-3.png" width="672" /></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="inverse-multidimensional-scaling.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">imdsSolver</span>(<span class="dv">8</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-4.png" width="672" /></p>
</div>
<div id="order-four" class="section level2" number="22.11">
<h2><span class="header-section-number">22.11</span> Order Four</h2>
<p><span class="math display">\[
B=\alpha A_{12}+\beta A_{13}+\gamma A_{14}+\delta A_{23}+\epsilon A_{24}+\phi A_{34}
\]</span>
<span class="math display">\[
B=\begin{bmatrix}
\alpha+\beta+\gamma&amp;-\alpha&amp;-\beta&amp;-\gamma\\
-\alpha&amp;\alpha+\delta+\epsilon&amp;-\delta&amp;-\epsilon\\
-\beta&amp;-\delta&amp;\beta+\delta+\phi&amp;-\phi\\
-\gamma&amp;-\epsilon&amp;-\phi&amp;\gamma+\epsilon+\phi
\end{bmatrix}.
\]</span>
The characteristic equation is
<span class="math display">\[
f(\lambda)=\lambda(\lambda^3-2\tau\lambda^2+(3\eta+(\alpha\phi+\beta\epsilon+\gamma\delta))\lambda-Y).
\]</span>
<span class="math display">\[
Z=\frac12\begin{bmatrix}
+1&amp;+1&amp;+1&amp;+1\\
+1&amp;+1&amp;-1&amp;-1\\
+1&amp;-1&amp;+1&amp;-1\\
+1&amp;-1&amp;-1&amp;+1
\end{bmatrix}.
\]</span></p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-avis_15" class="csl-entry">
Avis, D. 2015. <em><span class="nocase">User’s Guide for lrs - Version 6.1</span></em>. <span>The Computational Geometry Lab at McGill</span>. <a href="http://cgm.cs.mcgill.ca/~avis/C/lrslib/USERGUIDE.html">http://cgm.cs.mcgill.ca/~avis/C/lrslib/USERGUIDE.html</a>.
</div>
<div id="ref-berkelaar_15" class="csl-entry">
Berkelaar, M. and others. 2015. <a href="{https://CRAN.R-project.org/package=lpSolve}">{https://CRAN.R-project.org/package=lpSolve}</a>.
</div>
<div id="ref-degruijter_67" class="csl-entry">
De Gruijter, D. N. M. 1967. <span>“<span class="nocase">The Cognitive Structure of Dutch Political Parties in 1966</span>.”</span> Report E019-67. Psychological Institute, University of Leiden.
</div>
<div id="ref-deleeuw_C_05h" class="csl-entry">
———. 2005c. <span>“<span>Unidimensional Scaling</span>.”</span> In <em>The Encyclopedia of Statistics in Behavioral Science</em>, edited by B. S. Everitt and D. C, 4:2095–97. New York, N.Y.: Wiley. <a href="http://deleeuwpdx.net/janspubs/2005/chapters/deleeuw_C_05h.pdf">http://deleeuwpdx.net/janspubs/2005/chapters/deleeuw_C_05h.pdf</a>.
</div>
<div id="ref-deleeuw_U_12b" class="csl-entry">
———. 2012. <span>“<span>Inverse Multidimensional Scaling</span>.”</span> UCLA Department of Statistics. <a href="http://deleeuwpdx.net/janspubs/2012/notes/deleeuw_U_12b.pdf">http://deleeuwpdx.net/janspubs/2012/notes/deleeuw_U_12b.pdf</a>.
</div>
<div id="ref-deleeuw_groenen_A_97" class="csl-entry">
De Leeuw, J., and P. J. F. Groenen. 1997. <span>“Inverse Multidimensional Scaling.”</span> <em>Journal of Classification</em> 14 (3–21). <a href="http://deleeuwpdx.net/janspubs/1997/articles/deleeuw_groenen_A_97.pdf">http://deleeuwpdx.net/janspubs/1997/articles/deleeuw_groenen_A_97.pdf</a>.
</div>
<div id="ref-deleeuw_groenen_mair_E_16e" class="csl-entry">
De Leeuw, J., P. Groenen, and P. Mair. 2016a. <span>“Full-Dimensional Scaling.”</span> 2016. <a href="http://deleeuwpdx.net/pubfolders/full/full.pdf">http://deleeuwpdx.net/pubfolders/full/full.pdf</a>.
</div>
<div id="ref-deleeuw_groenen_mair_E_16f" class="csl-entry">
———. 2016d. <span>“More on Inverse Multidimensional Scaling.”</span> 2016. <a href="https://doi.org/10.13140/RG.2.1.1454.5684">https://doi.org/10.13140/RG.2.1.1454.5684</a>.
</div>
<div id="ref-deleeuw_groenen_mair_E_16c" class="csl-entry">
———. 2016e. <span>“<span class="nocase">Second Derivatives of rStress, with Applications</span>.”</span> 2016. <a href="https://doi.org/10.13140/RG.2.1.1058.4081">https://doi.org/10.13140/RG.2.1.1058.4081</a>.
</div>
<div id="ref-deleeuw_groenen_mair_E_16g" class="csl-entry">
———. 2016f. <span>“Singularities and Zero Distances in Multidimensional Scaling.”</span> 2016. <a href="https://doi.org/10.13140/RG.2.1.3339.2403">https://doi.org/10.13140/RG.2.1.3339.2403</a>.
</div>
<div id="ref-fukuda_15" class="csl-entry">
Fukuda, K. 2015. <em><span class="nocase">cdd and cddplus Homepage</span></em>. <a href="https://www.inf.ethz.ch/personal/fukudak/cdd_home/">https://www.inf.ethz.ch/personal/fukudak/cdd_home/</a>.
</div>
<div id="ref-geyer_meeden_15" class="csl-entry">
Geyer, C. J., and G. D. Meeden. 2015. <span>“<span class="nocase">rcdd: Computational Geometry</span>.”</span> 2015. <a href="https://CRAN.R-project.org/package=rcdd">https://CRAN.R-project.org/package=rcdd</a>.
</div>
<div id="ref-goldman_56" class="csl-entry">
Goldman, A. J. 1956. <span>“<span class="nocase">Resolution and Separation Theorems for Polyhedral Convex Sets</span>.”</span> In <em>Linear Inequalities and Related Systems</em>, edited by Kuhn H. W. and A. W. Tucker, 41–51. Annals of Mathematics Studies 38. Princeton University Press.
</div>
<div id="ref-robere_15" class="csl-entry">
Robere, R. 2015. <em><span class="nocase">vertexenum: Vertex Enumeration of Polytopes</span></em>. <a href="https://CRAN.R-project.org/package=vertexenum">https://CRAN.R-project.org/package=vertexenum</a>.
</div>
<div id="ref-turlach_weingessel_13" class="csl-entry">
Turlach, B. A., and A. Weingessel. 2013. <em><span class="nocase">quadprog: Functions to solve Quadratic Programming Problems.</span></em> <a href="https://CRAN.R-project.org/package=quadprog">https://CRAN.R-project.org/package=quadprog</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="alternative-least-squares-loss.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="stability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "none"
},
"keep_md": true,
"toolbar": {
"position": "fixed"
},
"toc_depth": 5
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
